<?php
declare(strict_types=1);require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/health_network_v590.php';if(!hn590_enabled()){http_response_code(404);exit('Healthcare Network unavailable.');}$stats=hn590_stats();$pharmacies=array_slice(hn590_pharmacies(true),0,4);$labs=array_slice(hn590_labs(true),0,4);$ambulances=array_slice(hn590_ambulances(true),0,4);hn590_track('health_network_home');hn590_public_header('Healthcare Network Pro','Connected pharmacy, diagnostic lab, ambulance, doctor and blood-bank services for the city.');$em=hn590_setting('health_network_v590_emergency_number',hn590_setting('doctor_online_v580_emergency_number','1122'));
?>
<main>
<section class="hn590-hero"><div class="hn590-shell hn590-hero-grid"><div><span class="hn590-kicker">SHAHKOTPK · CONNECTED HEALTH SERVICES</span><h1>Healthcare around your city, <em>connected in one place.</em></h1><p>Find doctors, verified pharmacies and diagnostic labs, manage bookings and reports, request an ambulance, and keep your service history in one account.</p><div class="hn590-actions"><a class="hn590-btn primary" href="/doctor-online.php">✚ Find Doctor</a><a class="hn590-btn" href="/labs.php">◫ Book Lab Test</a><a class="hn590-btn danger" href="/ambulance.php">● Request Ambulance</a><a class="hn590-btn" href="/health-provider-signup.php">Join as Provider</a></div><div class="hn590-trust"><span>✓ Role-based providers</span><span>✓ Prescription verification workflow</span><span>✓ Private patient account</span></div></div><aside class="hn590-emergency-card"><div class="hn590-orb"><i></i><b>EMERGENCY</b></div><h2>Need urgent help?</h2><p>For life-threatening emergencies, call local emergency services instead of waiting for a web request.</p><a href="tel:<?=e(preg_replace('/[^0-9+]/','',$em)?:$em)?>">Call <?=e($em)?></a><a class="secondary" href="/ambulance.php">Open Ambulance Desk →</a></aside></div></section>
<section class="hn590-service-strip"><div class="hn590-shell hn590-service-grid"><a href="/doctor-online.php"><i>✚</i><b>Doctor Online</b><span>Appointments & consultation</span></a><a href="/blood-bank.php"><i>♥</i><b>Blood Bank</b><span>Donation & requests</span></a><a href="/pharmacies.php"><i>▣</i><b>Pharmacy</b><span>Verified pharmacy directory</span></a><a href="/labs.php"><i>◫</i><b>Diagnostic Labs</b><span>Tests & reports</span></a><a href="/ambulance.php"><i>●</i><b>Ambulance</b><span>Request & dispatch status</span></a><a href="/health-network-account.php"><i>◇</i><b>My Health Network</b><span>Unified service history</span></a></div></section>
<section class="hn590-section"><div class="hn590-shell"><div class="hn590-head"><div><span>NETWORK PULSE</span><h2>Connected healthcare services</h2><p>Live operational counts from the configured ShahkotPK healthcare network.</p></div></div><div class="hn590-stats"><div><i>▣</i><b><?=$stats['pharmacies']?></b><span>Pharmacies</span></div><div><i>◫</i><b><?=$stats['labs']?></b><span>Labs</span></div><div><i>●</i><b><?=$stats['available_ambulances']?></b><span>Ambulances available</span></div><div><i>◇</i><b><?=$stats['reports_ready']?></b><span>Reports ready</span></div></div></div></section>
<section class="hn590-section alt"><div class="hn590-shell"><div class="hn590-head"><div><span>PHARMACY NETWORK</span><h2>Verified local pharmacies</h2><p>Prescription-required items remain subject to pharmacy verification and a valid prescription.</p></div><a href="/pharmacies.php">View All →</a></div><div class="hn590-cards"><?php if(!$pharmacies):?><div class="hn590-empty">No verified pharmacies published yet.</div><?php endif;?><?php foreach($pharmacies as $p):?><article><div class="hn590-card-icon">▣</div><span class="hn590-badge">VERIFIED</span><h3><?=e($p['name'])?></h3><p>⌖ <?=e($p['address']?:$p['area']?:'City service area')?></p><div class="hn590-card-meta"><span><?=$p['delivery_available']?'Delivery':'Pickup only'?></span><span><?=$p['pickup_available']?'Pickup':'No pickup'?></span></div><a href="/pharmacy.php?id=<?=(int)$p['id']?>">Open Pharmacy →</a></article><?php endforeach;?></div></div></section>
<section class="hn590-section"><div class="hn590-shell"><div class="hn590-head"><div><span>DIAGNOSTICS</span><h2>Labs & home sample collection</h2><p>Book published tests, choose available home collection and receive reports in your private dashboard.</p></div><a href="/labs.php">View Labs →</a></div><div class="hn590-cards"><?php if(!$labs):?><div class="hn590-empty">No verified diagnostic labs published yet.</div><?php endif;?><?php foreach($labs as $l):?><article><div class="hn590-card-icon blue">◫</div><span class="hn590-badge blue">VERIFIED LAB</span><h3><?=e($l['name'])?></h3><p>⌖ <?=e($l['address']?:$l['area']?:'City service area')?></p><div class="hn590-card-meta"><span><?=$l['home_collection']?'Home collection':'Visit lab'?></span><span><?=e($l['phone']?:'Portal contact')?></span></div><a href="/lab.php?id=<?=(int)$l['id']?>">Tests & Booking →</a></article><?php endforeach;?></div></div></section>
<section class="hn590-section dark"><div class="hn590-shell hn590-ambulance-block"><div><span>AMBULANCE NETWORK</span><h2>Dispatch-ready fleet visibility</h2><p>Submit pickup and destination details to the local dispatch desk. Web availability is operational information; emergency response is controlled by the service provider.</p><a class="hn590-btn danger" href="/ambulance.php">Request Ambulance</a></div><div class="hn590-fleet"><?php if(!$ambulances):?><div class="hn590-empty dark">No ambulances currently marked available.</div><?php endif;?><?php foreach($ambulances as $a):?><div><i>●</i><span><b><?=e($a['vehicle_no'])?></b><small><?=e($a['vehicle_type']?:'Ambulance')?> · <?=e($a['base_location']?:'Local base')?></small></span><em>AVAILABLE</em></div><?php endforeach;?></div></div></section>
<section class="hn590-section"><div class="hn590-shell hn590-cta"><div><span>ONE PATIENT ACCOUNT</span><h2>Your connected health dashboard</h2><p>See Doctor Online appointments, pharmacy orders, lab bookings/reports, ambulance requests and shortcuts to Blood Bank services.</p></div><a class="hn590-btn primary" href="/health-network-account.php">Open My Health Network →</a></div></section>
</main>
<?php hn590_public_footer(); ?>
