<?php
declare(strict_types=1);

function ai710_tid(): int { if(isset($GLOBALS['AI710_TENANT_OVERRIDE']))return (int)$GLOBALS['AI710_TENANT_OVERRIDE'];if(isset($GLOBALS['V900_TENANT_OVERRIDE']))return (int)$GLOBALS['V900_TENANT_OVERRIDE'];if(isset($GLOBALS['V800_TENANT_OVERRIDE']))return (int)$GLOBALS['V800_TENANT_OVERRIDE'];return function_exists('tenant_id')?(int)tenant_id():0; }
function ai710_user(): ?array { return function_exists('current_user')?current_user():null; }
function ai710_table(string $table): bool { static $c=[]; if(isset($c[$table]))return $c[$table]; if(!preg_match('/^[a-zA-Z0-9_]+$/',$table))return false; try{$q=db()->prepare('SHOW TABLES LIKE ?');$q->execute([$table]);return $c[$table]=(bool)$q->fetchColumn();}catch(Throwable $e){return $c[$table]=false;} }
function ai710_columns(string $table): array { static $c=[]; if(isset($c[$table]))return $c[$table]; try{$q=db()->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`');$o=[];foreach($q->fetchAll()?:[] as $r)$o[(string)$r['Field']]=true;return $c[$table]=$o;}catch(Throwable $e){return $c[$table]=[];} }
function ai710_json($v,array $default=[]): array { if(is_array($v))return $v; $x=json_decode((string)$v,true); return is_array($x)?$x:$default; }
function ai710_clip(string $s,int $max=6000): string { $s=trim($s); return mb_strlen($s)>$max?mb_substr($s,0,$max).'…':$s; }
function ai710_tenant_settings(bool $refresh=false): array { static $cache=null;if($refresh)$cache=null;if($cache!==null)return $cache;if(!ai710_table('ai_tenant_settings_v710'))return $cache=[];try{$q=db()->prepare('SELECT settings_json FROM ai_tenant_settings_v710 WHERE tenant_id=? LIMIT 1');$q->execute([ai710_tid()]);return $cache=ai710_json($q->fetchColumn()?:'');}catch(Throwable $e){return $cache=[];} }
function ai710_setting(string $key,$default=null){$s=ai710_tenant_settings();if(array_key_exists($key,$s))return $s[$key];return function_exists('setting')?setting($key,$default):$default;}
function ai710_bool(string $key,bool $default=false): bool {return in_array(strtolower((string)ai710_setting($key,$default?'1':'0')),['1','true','yes','on'],true);}
function ai710_enabled(): bool { return ai710_bool('ai710_enabled',true); }
function ai710_save_tenant_settings(array $values,?int $by=null): void {$current=ai710_tenant_settings();foreach($values as $k=>$v)$current[(string)$k]=$v;db()->prepare('INSERT INTO ai_tenant_settings_v710(tenant_id,settings_json,updated_by,updated_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE settings_json=VALUES(settings_json),updated_by=VALUES(updated_by),updated_at=NOW()')->execute([ai710_tid(),json_encode($current,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$by]);ai710_tenant_settings(true);} 

function ai710_key_file(): string { return dirname(__DIR__).'/storage/ai710.key'; }
function ai710_secret_key(): string {
    $file=ai710_key_file();
    if(is_file($file)){$raw=@file_get_contents($file);if(is_string($raw)&&strlen($raw)>=32)return substr($raw,0,32);}
    $dir=dirname($file);if(!is_dir($dir)&&!@mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('AI secure storage directory is not writable.');
    $raw=random_bytes(32);if(@file_put_contents($file,$raw,LOCK_EX)===false)throw new RuntimeException('Unable to create the AI integration encryption key in storage/.');@chmod($file,0600);return $raw;
}
function ai710_encrypt(string $plain): string {
    if($plain==='')return '';
    if(!function_exists('openssl_encrypt'))throw new RuntimeException('OpenSSL is required to store API secrets safely.');
    $iv=random_bytes(12);$tag='';$enc=openssl_encrypt($plain,'aes-256-gcm',ai710_secret_key(),OPENSSL_RAW_DATA,$iv,$tag,'ShahkotPK-AI-v710');
    if($enc===false)throw new RuntimeException('Unable to encrypt integration secret.');
    return base64_encode($iv.$tag.$enc);
}
function ai710_decrypt(?string $cipher): string {
    $cipher=trim((string)$cipher);if($cipher==='')return '';$raw=base64_decode($cipher,true);if($raw===false||strlen($raw)<29)return '';
    $iv=substr($raw,0,12);$tag=substr($raw,12,16);$enc=substr($raw,28);$out=openssl_decrypt($enc,'aes-256-gcm',ai710_secret_key(),OPENSSL_RAW_DATA,$iv,$tag,'ShahkotPK-AI-v710');return $out===false?'':$out;
}
function ai710_secret_hint(string $secret): string { $n=strlen($secret); if($n<7)return str_repeat('•',max(4,$n));return substr($secret,0,3).'…'.substr($secret,-4); }

function ai710_provider_catalog(): array {
    return [
      'openai_responses'=>['OpenAI Responses API','https://api.openai.com/v1/responses','gpt-5-mini'],
      'openai_compatible'=>['OpenAI-Compatible API','https://api.openai.com/v1/chat/completions','gpt-5-mini'],
      'openrouter'=>['OpenRouter','https://openrouter.ai/api/v1/chat/completions','openai/gpt-5-mini'],
      'groq'=>['Groq','https://api.groq.com/openai/v1/chat/completions','llama-3.3-70b-versatile'],
      'anthropic'=>['Anthropic','https://api.anthropic.com/v1/messages','claude-sonnet-4-5'],
      'gemini'=>['Google Gemini','https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent','gemini-2.5-flash'],
      'mistral'=>['Mistral','https://api.mistral.ai/v1/chat/completions','mistral-small-latest'],
      'deepseek'=>['DeepSeek','https://api.deepseek.com/chat/completions','deepseek-chat'],
      'ollama'=>['Ollama / Local','http://127.0.0.1:11434/api/chat','llama3.2'],
      'custom'=>['Custom REST / Compatible','','']
    ];
}

function ai710_import_legacy_provider_once(?int $by=null): void {
    if(!ai710_table('ai_providers_v710'))return;
    try{$q=db()->prepare('SELECT COUNT(*) FROM ai_providers_v710 WHERE tenant_id=?');$q->execute([ai710_tid()]);if((int)$q->fetchColumn()>0)return;}catch(Throwable $e){return;}
    if(!function_exists('setting'))return;$oldProvider=strtolower(trim((string)setting('ai_provider','local')));$endpoint=trim((string)setting('ai_endpoint',''));$model=trim((string)setting('ai_model',''));$secret=trim((string)setting('ai_api_key',''));if($oldProvider==='local'||($endpoint===''&&$model===''))return;
    try{$type='openai_compatible';$name='Imported Legacy AI';$cipher=$secret!==''?ai710_encrypt($secret):null;$hint=$secret!==''?ai710_secret_hint($secret):null;db()->prepare('INSERT INTO ai_providers_v710(tenant_id,name,provider_type,base_url,secret_cipher,secret_hint,model,enabled,is_default,timeout_seconds,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,30,?,NOW(),NOW())')->execute([ai710_tid(),$name,$type,$endpoint?:null,$cipher,$hint,$model?:null,1,$by]);}catch(Throwable $e){}
}
function ai710_providers(bool $enabledOnly=false): array { if(!ai710_table('ai_providers_v710'))return [];try{$sql='SELECT * FROM ai_providers_v710 WHERE tenant_id IN (0,?)'.($enabledOnly?' AND enabled=1':'').' ORDER BY tenant_id DESC,is_default DESC,id DESC';$q=db()->prepare($sql);$q->execute([ai710_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function ai710_provider(?int $id=null): ?array { $rows=ai710_providers(true);if($id){foreach($rows as $r)if((int)$r['id']===$id)return $r;}foreach($rows as $r)if((int)$r['tenant_id']===ai710_tid()&&!empty($r['is_default']))return $r;foreach($rows as $r)if(!empty($r['is_default']))return $r;return $rows[0]??null; }
function ai710_private_ip(string $ip): bool { if(!filter_var($ip,FILTER_VALIDATE_IP))return false;return filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===false; }
function ai710_validate_endpoint(string $url,bool $allowLocal=false): void {
    if(!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a valid API endpoint URL.');$p=parse_url($url);$scheme=strtolower((string)($p['scheme']??''));if(!in_array($scheme,['https','http'],true))throw new RuntimeException('Only HTTP/HTTPS API endpoints are supported.');if($scheme!=='https'&&!$allowLocal)throw new RuntimeException('External AI/API endpoints must use HTTPS.');
    $host=strtolower((string)($p['host']??''));if($host==='')throw new RuntimeException('API endpoint hostname is missing.');if(!$allowLocal&&in_array($host,['localhost','127.0.0.1','::1'],true))throw new RuntimeException('Private/local endpoints are blocked for this provider type.');if(!$allowLocal){$ip=filter_var($host,FILTER_VALIDATE_IP)?$host:gethostbyname($host);if($ip!==$host||filter_var($host,FILTER_VALIDATE_IP)){if(ai710_private_ip($ip))throw new RuntimeException('Private/reserved API destinations are blocked for this integration.');}}
}
function ai710_http_json(string $url,array $headers,array $payload,int $timeout=30,bool $allowLocal=false): array {
    ai710_validate_endpoint($url,$allowLocal);if(!function_exists('curl_init'))throw new RuntimeException('PHP cURL extension is required for AI integrations.');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_HTTPHEADER=>array_merge(['Content-Type: application/json'],$headers),CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>min(15,$timeout),CURLOPT_TIMEOUT=>max(8,min(90,$timeout)),CURLOPT_SSL_VERIFYPEER=>$allowLocal?false:true,CURLOPT_SSL_VERIFYHOST=>$allowLocal?0:2]);$start=microtime(true);$body=(string)curl_exec($ch);$err=(string)curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$ms=(int)round((microtime(true)-$start)*1000);if($body===''&&$err!=='')throw new RuntimeException('Provider connection failed: '.$err);$j=json_decode($body,true);if($code<200||$code>=300){$msg=(string)($j['error']['message']??$j['message']??('HTTP '.$code));throw new RuntimeException('Provider error: '.ai710_clip($msg,350));}if(!is_array($j))throw new RuntimeException('Provider returned invalid JSON.');$j['_latency_ms']=$ms;return $j;
}
function ai710_provider_call(array $provider,array $messages,array $opts=[]): array {
    $type=(string)$provider['provider_type'];$model=trim((string)($opts['model']??$provider['model']??''));$url=trim((string)$provider['base_url']);$secret=ai710_decrypt((string)($provider['secret_cipher']??''));$timeout=max(8,min(90,(int)($provider['timeout_seconds']??30)));$temp=max(0,min(1.5,(float)($opts['temperature']??0.3)));$max=max(128,min(5000,(int)($opts['max_tokens']??1200)));$headers=[];$allowLocal=$type==='ollama';
    if($type==='gemini'){$url=$url?:'https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent';$url=str_replace('{model}',rawurlencode($model),$url);$headers=$secret!==''?['x-goog-api-key: '.$secret]:[];$contents=[];$system='';foreach($messages as $m){if(($m['role']??'')==='system'){$system.=(string)$m['content']."\n";continue;}$contents[]=['role'=>($m['role']==='assistant'?'model':'user'),'parts'=>[['text'=>(string)$m['content']]]];}$payload=['contents'=>$contents,'generationConfig'=>['temperature'=>$temp,'maxOutputTokens'=>$max]];if(trim($system)!=='')$payload['systemInstruction']=['parts'=>[['text'=>trim($system)]]];$j=ai710_http_json($url,$headers,$payload,$timeout,false);$text=(string)($j['candidates'][0]['content']['parts'][0]['text']??'');}
    elseif($type==='anthropic'){$url=$url?:'https://api.anthropic.com/v1/messages';$headers=['x-api-key: '.$secret,'anthropic-version: 2023-06-01'];$system='';$list=[];foreach($messages as $m){if(($m['role']??'')==='system'){$system.=(string)$m['content']."\n";continue;}$list[]=['role'=>($m['role']==='assistant'?'assistant':'user'),'content'=>(string)$m['content']];}$payload=['model'=>$model,'max_tokens'=>$max,'temperature'=>$temp,'messages'=>$list];if(trim($system)!=='')$payload['system']=trim($system);$j=ai710_http_json($url,$headers,$payload,$timeout,false);$text=(string)($j['content'][0]['text']??'');}
    elseif($type==='openai_responses'){$url=$url?:'https://api.openai.com/v1/responses';$headers=$secret!==''?['Authorization: Bearer '.$secret]:[];$system='';$input=[];foreach($messages as $m){if(($m['role']??'')==='system'){$system.=(string)$m['content']."\n";continue;}$input[]=['role'=>($m['role']==='assistant'?'assistant':'user'),'content'=>[['type'=>'input_text','text'=>(string)$m['content']]]];}$payload=['model'=>$model,'input'=>$input,'max_output_tokens'=>$max];if(trim($system)!=='')$payload['instructions']=trim($system);$j=ai710_http_json($url,$headers,$payload,$timeout,false);$text=(string)($j['output_text']??'');if($text===''){foreach(($j['output']??[]) as $o)foreach(($o['content']??[]) as $c)if(isset($c['text']))$text.=(string)$c['text'];}}
    elseif($type==='ollama'){$url=$url?:'http://127.0.0.1:11434/api/chat';$payload=['model'=>$model,'messages'=>$messages,'stream'=>false,'options'=>['temperature'=>$temp]];$j=ai710_http_json($url,[],$payload,$timeout,true);$text=(string)($j['message']['content']??'');}
    else {$defaults=ai710_provider_catalog();if($url===''&&isset($defaults[$type]))$url=(string)$defaults[$type][1];$headers=$secret!==''?['Authorization: Bearer '.$secret]:[];$extra=ai710_json($provider['config_json']??'');if($type==='openrouter'&&isset($extra['site_url']))$headers[]='HTTP-Referer: '.$extra['site_url'];$payload=['model'=>$model,'messages'=>$messages,'temperature'=>$temp,'max_tokens'=>$max];$j=ai710_http_json($url,$headers,$payload,$timeout,false);$text=(string)($j['choices'][0]['message']['content']??$j['output_text']??'');}
    $text=trim($text);if($text==='')throw new RuntimeException('AI provider returned an empty response.');return ['text'=>$text,'model'=>$model,'latency_ms'=>(int)($j['_latency_ms']??0),'raw'=>$j];
}
function ai710_test_provider(array $provider): array { $r=ai710_provider_call($provider,[['role'=>'system','content'=>'Reply with exactly: ShahkotPK AI connection OK'],['role'=>'user','content'=>'Connection test']],[ 'max_tokens'=>50,'temperature'=>0 ]);return ['ok'=>true,'message'=>ai710_clip($r['text'],180),'latency_ms'=>$r['latency_ms']]; }

function ai710_terms(string $q): array { $q=mb_strtolower($q);$q=preg_replace('/[^\pL\pN\s_-]+/u',' ',$q);$raw=preg_split('/\s+/u',$q,-1,PREG_SPLIT_NO_EMPTY)?:[];$stop=['the','and','for','with','what','how','please','mujhe','muje','hai','hain','ka','ki','ke','ko','main','mein'];$o=[];foreach($raw as $x)if(mb_strlen($x)>=2&&!in_array($x,$stop,true))$o[$x]=$x;return array_values($o); }
function ai710_score_text(string $text,array $terms): int { $t=mb_strtolower($text);$s=0;foreach($terms as $i=>$w)if(mb_strpos($t,$w)!==false)$s+=($i===0?12:7);return $s; }
function ai710_knowledge(string $query,int $limit=6): array { if(!ai710_table('ai_knowledge_v710'))return [];$terms=ai710_terms($query);try{$q=db()->prepare('SELECT * FROM ai_knowledge_v710 WHERE tenant_id IN(0,?) AND status=1 ORDER BY tenant_id DESC,priority DESC,id DESC LIMIT 160');$q->execute([ai710_tid()]);$rows=$q->fetchAll()?:[];$out=[];foreach($rows as $r){$score=ai710_score_text(($r['title']??'').' '.($r['tags']??'').' '.($r['content']??''),$terms)+(int)$r['priority']/10;if(!$terms)$score=(int)$r['priority']/10;if($score>0)$out[]=$r+['_score'=>$score];}usort($out,fn($a,$b)=>$b['_score']<=>$a['_score']);return array_slice($out,0,$limit);}catch(Throwable $e){return [];} }
function ai710_examples(string $query,int $limit=3): array { if(!ai710_table('ai_training_examples_v710'))return [];$terms=ai710_terms($query);try{$q=db()->prepare('SELECT * FROM ai_training_examples_v710 WHERE tenant_id IN(0,?) AND status=1 ORDER BY tenant_id DESC,id DESC LIMIT 120');$q->execute([ai710_tid()]);$rows=$q->fetchAll()?:[];$out=[];foreach($rows as $r){$score=ai710_score_text(($r['user_input']??'').' '.($r['tags']??''),$terms);if($score>0)$out[]=$r+['_score'=>$score];}usort($out,fn($a,$b)=>$b['_score']<=>$a['_score']);return array_slice($out,0,$limit);}catch(Throwable $e){return [];} }
function ai710_agents(): array { if(!ai710_table('ai_agents_v710'))return [];try{$q=db()->prepare('SELECT * FROM ai_agents_v710 WHERE tenant_id IN(0,?) AND enabled=1 ORDER BY tenant_id DESC,is_default DESC,id');$q->execute([ai710_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function ai710_agent(?int $id=null): array { $rows=ai710_agents();if($id)foreach($rows as $r)if((int)$r['id']===$id)return $r;foreach($rows as $r)if((int)$r['tenant_id']===ai710_tid()&&!empty($r['is_default']))return $r;foreach($rows as $r)if(!empty($r['is_default']))return $r;return $rows[0]??['id'=>0,'name'=>'ShahkotPK Assistant','slug'=>'fallback','system_prompt'=>'','allowed_tools_json'=>'[]','temperature'=>0.3,'max_output_tokens'=>1200]; }

function ai710_tool_registry(): array {
    return [
      'portal_search'=>['label'=>'Search ShahkotPK','risk'=>'read','permission'=>'','description'=>'Search businesses, products, doctors, education, tourism and other public portal records.'],
      'knowledge_search'=>['label'=>'Search AI Knowledge','risk'=>'read','permission'=>'','description'=>'Search manually trained ShahkotPK AI knowledge.'],
      'module_status'=>['label'=>'Check Module Status','risk'=>'read','permission'=>'ai.dashboard','description'=>'Check availability and basic record counts across platform modules.'],
      'dashboard_summary'=>['label'=>'Platform Summary','risk'=>'read','permission'=>'ai.dashboard','description'=>'Return a tenant-scoped operational summary.'],
      'draft_notification'=>['label'=>'Create Notification Draft','risk'=>'medium','permission'=>'ai.actions.execute','description'=>'Prepare and publish an in-app notification after approval.'],
      'update_safe_setting'=>['label'=>'Update AI Tenant Setting','risk'=>'high','permission'=>'ai.actions.execute','description'=>'Change a whitelisted AI tenant setting after admin approval.'],
      'tenant_feature_toggle'=>['label'=>'Toggle Tenant Feature','risk'=>'high','permission'=>'ai.actions.execute','description'=>'Enable or disable an approved tenant feature after admin approval.'],
      'custom_api_call'=>['label'=>'Call Approved Integration','risk'=>'high','permission'=>'ai.integrations.manage','description'=>'Call an AI-enabled custom integration only after approval.']
    ];
}
function ai710_module_counts(): array { $tid=ai710_tid();$defs=['Businesses'=>['businesses','status=\'active\''],'Products'=>['store_products','status=\'published\''],'Properties'=>['city_portal_items','content_type=\'property\' AND status=\'published\''],'Doctors'=>['health_doctors_v580','approval_status=\'approved\''],'Blood Requests'=>['blood_requests_v570',"status NOT IN ('fulfilled','closed','rejected')"],'Education'=>['edu_institutions_v700',"status='active'"],'Transport Bookings'=>['transport_bookings_v700','1=1'],'Tourism Bookings'=>['tourism_bookings_v700','1=1'],'Municipal Requests'=>['municipal_requests_v630',"status NOT IN ('resolved','closed','rejected')"]];$o=[];foreach($defs as $name=>$d){[$table,$where]=$d;if(!ai710_table($table)){$o[$name]=null;continue;}$cols=ai710_columns($table);$sql='SELECT COUNT(*) FROM `'.$table.'` WHERE '.$where;$p=[];if(isset($cols['tenant_id'])){$sql.=' AND tenant_id=?';$p[]=$tid;}try{$q=db()->prepare($sql);$q->execute($p);$o[$name]=(int)$q->fetchColumn();}catch(Throwable $e){$o[$name]=null;}}return $o; }
function ai710_execute_tool(string $key,array $input,?array $actor=null): array {
    $actor=$actor?:ai710_user();$tid=ai710_tid();
    if($key==='portal_search'){$q=trim((string)($input['query']??''));$rows=function_exists('sc630_super_search')?sc630_super_search($q,20):(function_exists('ai_smart_search')?ai_smart_search($q,20):[]);return ['ok'=>true,'results'=>$rows];}
    if($key==='knowledge_search')return ['ok'=>true,'results'=>ai710_knowledge((string)($input['query']??''),8)];
    if($key==='module_status'||$key==='dashboard_summary')return ['ok'=>true,'counts'=>ai710_module_counts()];
    if($key==='draft_notification'){if(!ai710_table('smart_notifications_v630'))throw new RuntimeException('Smart notification module is not available.');$title=trim((string)($input['title']??''));$message=trim((string)($input['message']??''));if($title===''||$message==='')throw new RuntimeException('Notification title and message are required.');$aud=in_array((string)($input['audience']??'citizen'),['all','citizen','user'],true)?(string)$input['audience']:'citizen';$priority=in_array((string)($input['priority']??'normal'),['normal','important','urgent'],true)?(string)$input['priority']:'normal';$uid=isset($input['user_id'])?(int)$input['user_id']:null;db()->prepare('INSERT INTO smart_notifications_v630(tenant_id,user_id,audience,channel,title,message,action_url,icon,priority,created_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())')->execute([$tid,$uid?:null,$aud,'in_app',mb_substr($title,0,220),$message,trim((string)($input['action_url']??''))?:null,'AI',$priority]);return ['ok'=>true,'notification_id'=>(int)db()->lastInsertId()];}
    if($key==='update_safe_setting'){$allow=['ai710_enabled','ai710_external_enabled','ai710_public_assistant_enabled','ai710_action_mode','ai710_default_language'];$settingKey=(string)($input['key']??'');if(!in_array($settingKey,$allow,true))throw new RuntimeException('This setting is not on the AI tenant-safe allowlist.');$value=(string)($input['value']??'');ai710_save_tenant_settings([$settingKey=>$value],$actor?(int)$actor['id']:null);return ['ok'=>true,'key'=>$settingKey,'value'=>$value,'tenant_id'=>$tid];}
    if($key==='tenant_feature_toggle'){$feature=preg_replace('/[^a-z0-9_-]/','',strtolower((string)($input['feature']??'')));$allow=['marketplace','property','news','blog','live','maps','services','directory','city_content','ai','mobile_api','seller_pos'];if(!in_array($feature,$allow,true))throw new RuntimeException('This tenant feature is not on the AI-safe allowlist.');if($tid<1)throw new RuntimeException('Tenant feature toggles require a selected non-master tenant.');if(!ai710_table('tenant_features'))throw new RuntimeException('Tenant feature table is unavailable.');$enabled=in_array(strtolower((string)($input['enabled']??'1')),['1','true','yes','on'],true)?1:0;db()->prepare('INSERT INTO tenant_features(tenant_id,feature_key,enabled,updated_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),updated_at=NOW()')->execute([$tid,$feature,$enabled]);return ['ok'=>true,'feature'=>$feature,'enabled'=>$enabled,'tenant_id'=>$tid];}
    if($key==='custom_api_call')return ai710_execute_integration((int)($input['integration_id']??0),(string)($input['path']??''),(array)($input['payload']??[]));
    throw new RuntimeException('Unknown AI tool.');
}
function ai710_queue_action(string $key,array $input,?array $actor=null,?int $agentId=null,string $conversationKey=''): array { $tools=ai710_tool_registry();if(!isset($tools[$key]))throw new RuntimeException('Unknown AI action.');$def=$tools[$key];$mode=(string)ai710_setting('ai710_action_mode','approval');$risk=$def['risk'];$auto=($risk==='read')||($mode==='auto_low_risk'&&$risk==='medium');if($auto)return ['status'=>'executed','result'=>ai710_execute_tool($key,$input,$actor)];$u=$actor?:ai710_user();$q=db()->prepare("INSERT INTO ai_action_queue_v710(tenant_id,requester_user_id,agent_id,conversation_key,action_key,action_label,risk_level,input_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'pending',NOW(),NOW())");$q->execute([ai710_tid(),$u?(int)$u['id']:null,$agentId?:null,$conversationKey?:null,$key,$def['label'],$risk,json_encode($input,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);return ['status'=>'pending','action_id'=>(int)db()->lastInsertId(),'message'=>'Action prepared and waiting for admin approval.']; }
function ai710_approve_action(int $id,int $approver,bool $approve=true): array {
    if(!$approve){$q=db()->prepare("UPDATE ai_action_queue_v710 SET status='rejected',approved_by=?,approved_at=NOW(),updated_at=NOW() WHERE id=? AND tenant_id=? AND status='pending'");$q->execute([$approver,$id,ai710_tid()]);if($q->rowCount()<1)throw new RuntimeException('AI action was already processed or not found.');return ['status'=>'rejected'];}
    $q=db()->prepare("UPDATE ai_action_queue_v710 SET status='processing',approved_by=?,approved_at=NOW(),updated_at=NOW() WHERE id=? AND tenant_id=? AND status='pending'");$q->execute([$approver,$id,ai710_tid()]);if($q->rowCount()<1)throw new RuntimeException('AI action was already processed or not found.');
    $q=db()->prepare('SELECT * FROM ai_action_queue_v710 WHERE id=? AND tenant_id=? LIMIT 1');$q->execute([$id,ai710_tid()]);$r=$q->fetch();if(!$r)throw new RuntimeException('AI action not found.');
    try{$input=ai710_json($r['input_json']);$result=ai710_execute_tool((string)$r['action_key'],$input,ai710_user());db()->prepare("UPDATE ai_action_queue_v710 SET status='executed',result_json=?,executed_at=NOW(),updated_at=NOW() WHERE id=?")->execute([json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$id]);return ['status'=>'executed','result'=>$result];}
    catch(Throwable $e){try{db()->prepare("UPDATE ai_action_queue_v710 SET status='failed',error_text=?,updated_at=NOW() WHERE id=?")->execute([mb_substr($e->getMessage(),0,1000),$id]);}catch(Throwable $ignore){}throw $e;}
}

function ai710_integrations(): array { if(!ai710_table('ai_integrations_v710'))return [];try{$q=db()->prepare('SELECT * FROM ai_integrations_v710 WHERE tenant_id IN(0,?) ORDER BY tenant_id DESC,id DESC');$q->execute([ai710_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function ai710_integration(int $id): ?array { foreach(ai710_integrations() as $r)if((int)$r['id']===$id)return $r;return null; }
function ai710_execute_integration(int $id,string $path,array $payload): array { $i=ai710_integration($id);if(!$i||empty($i['enabled'])||empty($i['ai_callable']))throw new RuntimeException('Integration is not enabled for AI calls.');if(ai710_tid()>0&&(int)$i['tenant_id']!==ai710_tid())throw new RuntimeException('This integration is not assigned to the current tenant.');$base=rtrim((string)$i['base_url'],'/');$path='/'.ltrim($path,'/');$url=$base.$path;$secret=ai710_decrypt((string)$i['secret_cipher']);$headers=[];$mode=(string)$i['auth_mode'];if($mode==='bearer'&&$secret!=='')$headers[]='Authorization: Bearer '.$secret;elseif($mode==='header'&&$secret!=='')$headers[]=((string)($i['auth_header']?:'X-API-Key')).': '.$secret;return ai710_http_json($url,$headers,$payload,30,false); }

function ai710_conversation(string $sessionKey,?int $agentId=null): int { $u=ai710_user();$tid=ai710_tid();try{db()->prepare("INSERT IGNORE INTO ai_conversations_v710(tenant_id,user_id,session_key,agent_id,title,channel,status,created_at,updated_at) VALUES(?,?,?,?,NULL,'web','active',NOW(),NOW())")->execute([$tid,$u?(int)$u['id']:null,$sessionKey,$agentId]);$q=db()->prepare('SELECT id FROM ai_conversations_v710 WHERE tenant_id=? AND session_key=? LIMIT 1');$q->execute([$tid,$sessionKey]);return (int)$q->fetchColumn();}catch(Throwable $e){return 0;} }
function ai710_store_message(int $conversationId,string $role,string $content,?array $provider=null,array $meta=[]): void { if(!$conversationId)return;try{db()->prepare('INSERT INTO ai_messages_v710(tenant_id,conversation_id,role,content,provider_id,model,prompt_tokens,completion_tokens,latency_ms,meta_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW())')->execute([ai710_tid(),$conversationId,$role,$content,$provider?(int)$provider['id']:null,$meta['model']??($provider['model']??null),$meta['prompt_tokens']??null,$meta['completion_tokens']??null,$meta['latency_ms']??null,$meta?json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null]);}catch(Throwable $e){} }
function ai710_chat(string $text,?array $u=null,?int $agentId=null,string $sessionKey=''): array {
    $text=trim($text);if(mb_strlen($text)<2)throw new RuntimeException('Write a question first.');if(mb_strlen($text)>4000)throw new RuntimeException('Message is too long.');$u=$u?:ai710_user();$agent=ai710_agent($agentId);$sessionKey=$sessionKey?:((session_id()?:'guest').'-ai710');$cid=ai710_conversation($sessionKey,(int)($agent['id']??0));ai710_store_message($cid,'user',$text);
    $knowledge=ai710_knowledge($text,6);$examples=ai710_examples($text,3);$context='';if($knowledge){$context.="\nVERIFIED / ADMIN-TRAINED KNOWLEDGE:\n";foreach($knowledge as $k)$context.='- '.$k['title'].': '.ai710_clip((string)$k['content'],1200)."\n";}if($examples){$context.="\nTRAINING EXAMPLES:\n";foreach($examples as $x)$context.='User: '.ai710_clip((string)$x['user_input'],350)."\nAssistant: ".ai710_clip((string)$x['assistant_output'],700)."\n";}
    $portalContext='';if(function_exists('sc630_super_search')){$hits=sc630_super_search($text,8);if($hits){$portalContext="\nLIVE PORTAL SEARCH RESULTS:\n";foreach($hits as $h)$portalContext.='- '.($h['type']??'Result').': '.($h['title']??'').' | '.($h['subtitle']??'').' | '.($h['url']??'')."\n";}}
    $system="You are ShahkotPK AI Command Assistant for a multi-tenant city platform. Be concise, useful and accurate. Prefer verified portal records and admin-trained knowledge. Never expose API keys, passwords, private health records or private user data. Never claim that you changed data unless a tool result confirms it. Any write, delete, publish, money, account, permission or configuration change must go through the approval/action system. Do not diagnose medical conditions; for emergencies direct users to emergency services. If knowledge is insufficient, say so rather than inventing facts.".($agent['system_prompt']?"\n\nAGENT INSTRUCTIONS:\n".$agent['system_prompt']:'').$context.$portalContext;
    $provider=null;$externalEnabled=ai710_bool('ai710_external_enabled',true);$reply='';$meta=[];
    if($externalEnabled){$provider=ai710_provider((int)($agent['provider_id']??0)?:null);if($provider){try{$res=ai710_provider_call($provider,[['role'=>'system','content'=>$system],['role'=>'user','content'=>$text]],[ 'model'=>(string)($agent['model_override']?:$provider['model']),'temperature'=>(float)($agent['temperature']??0.3),'max_tokens'=>(int)($agent['max_output_tokens']??1200) ]);$reply=$res['text'];$meta=['model'=>$res['model'],'latency_ms'=>$res['latency_ms'],'provider'=>$provider['name'],'mode'=>'external'];}catch(Throwable $e){$meta=['provider'=>$provider['name'],'mode'=>'fallback','warning'=>$e->getMessage()];}}
    }
    if($reply===''){$fallback=function_exists('sc630_assistant_reply')?sc630_assistant_reply($text,$u):['reply'=>'I can help you search and navigate ShahkotPK services.','links'=>[],'intent'=>'general'];$reply=(string)$fallback['reply'];$links=$fallback['links']??[];$meta['mode']='local';}else{$links=[];if(function_exists('sc630_super_search'))foreach(array_slice(sc630_super_search($text,5),0,5) as $h)$links[]=[($h['type']??'Result').' · '.($h['title']??''),(string)($h['url']??'#')];}
    ai710_store_message($cid,'assistant',$reply,$provider,$meta);return ['reply'=>$reply,'links'=>$links,'conversation_id'=>$cid,'provider'=>$meta['provider']??'Local ShahkotPK','model'=>$meta['model']??'Local rules/search','mode'=>$meta['mode']??'local','warning'=>$meta['warning']??null];
}

function ai710_stats(): array { $tid=ai710_tid();$out=['providers'=>0,'knowledge'=>0,'examples'=>0,'agents'=>0,'pending_actions'=>0,'messages_30d'=>0,'success_actions'=>0];$defs=['providers'=>['ai_providers_v710','enabled=1'],'knowledge'=>['ai_knowledge_v710','status=1'],'examples'=>['ai_training_examples_v710','status=1'],'agents'=>['ai_agents_v710','enabled=1'],'pending_actions'=>['ai_action_queue_v710',"status='pending'"],'messages_30d'=>['ai_messages_v710','created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)'],'success_actions'=>['ai_action_queue_v710',"status='executed'"]];foreach($defs as $k=>$d){[$t,$w]=$d;if(!ai710_table($t))continue;try{$q=db()->prepare("SELECT COUNT(*) FROM `{$t}` WHERE tenant_id IN(0,?) AND {$w}");$q->execute([$tid]);$out[$k]=(int)$q->fetchColumn();}catch(Throwable $e){}}return $out; }
