<?php
declare(strict_types=1);

function ai_v4_enabled(): bool { return setting_bool('ai_suite_enabled',true); }
function ai_rows(string $sql,array $p=[]): array {try{$q=db()->prepare($sql);$q->execute($p);return $q->fetchAll()?:[];}catch(Throwable $e){if(function_exists('runtime_log'))runtime_log('AI query failed',$e);return [];}}
function ai_scalar(string $sql,array $p=[],$default=0){try{$q=db()->prepare($sql);$q->execute($p);$v=$q->fetchColumn();return $v===false?$default:$v;}catch(Throwable $e){return $default;}}
function ai_table_exists(string $table): bool {
    static $cache=[];
    if(array_key_exists($table,$cache))return $cache[$table];
    if(!preg_match('/^[A-Za-z0-9_]+$/',$table))return false;
    try{$q=db()->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1');$q->execute([$table]);return $cache[$table]=(bool)$q->fetchColumn();}
    catch(Throwable $e){try{$quoted=db()->quote($table);$q=db()->query('SHOW TABLES LIKE '.$quoted);return $cache[$table]=(bool)$q->fetchColumn();}catch(Throwable $e2){return $cache[$table]=false;}}
}
function ai_log(string $feature,string $provider,string $input,bool $ok,int $latency,string $error=''): void {try{$u=current_user();db()->prepare('INSERT INTO ai_request_logs(user_id,feature,provider,model,input_excerpt,success,latency_ms,error_text) VALUES(?,?,?,?,?,?,?,?)')->execute([$u?(int)$u['id']:null,$feature,$provider,(string)setting('ai_model',''),runtime_excerpt($input,650),$ok?1:0,$latency,$error?:null]);}catch(Throwable $e){}}

function ai_external_call(string $system,string $prompt): string {
    if(is_file(__DIR__.'/ai_orchestrator_v710.php')){require_once __DIR__.'/ai_orchestrator_v710.php';if(function_exists('ai710_enabled')&&ai710_enabled()&&function_exists('ai710_bool')&&ai710_bool('ai710_external_enabled',true)){$p=ai710_provider();if($p){$r=ai710_provider_call($p,[['role'=>'system','content'=>$system],['role'=>'user','content'=>$prompt]],['temperature'=>0.35,'max_tokens'=>1400]);return trim((string)$r['text']);}}}
    $provider=strtolower(trim((string)setting('ai_provider','local')));if($provider==='local'||!ai_v4_enabled())return '';
    $endpoint=trim((string)setting('ai_endpoint',''));$key=trim((string)setting('ai_api_key',''));$model=trim((string)setting('ai_model',''));
    if($endpoint===''||$model==='')throw new RuntimeException('Configure AI endpoint and model in Admin → AI Studio.');
    if(!filter_var($endpoint,FILTER_VALIDATE_URL)||stripos($endpoint,'https://')!==0)throw new RuntimeException('AI endpoint must be a valid HTTPS URL.');
    if(!function_exists('curl_init'))throw new RuntimeException('PHP cURL extension is required for external AI.');
    $payload=['model'=>$model,'messages'=>[['role'=>'system','content'=>$system],['role'=>'user','content'=>$prompt]],'temperature'=>0.35];
    $start=microtime(true);$ch=curl_init($endpoint);$headers=['Content-Type: application/json'];if($key!=='')$headers[]='Authorization: Bearer '.$key;
    curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>max(8,min(60,setting_int('ai_timeout_seconds',25))),CURLOPT_SSL_VERIFYPEER=>true]);
    $resp=(string)curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=(string)curl_error($ch);curl_close($ch);$ms=(int)round((microtime(true)-$start)*1000);
    if($code<200||$code>=300){ai_log('external',$provider,$prompt,false,$ms,$err?:('HTTP '.$code));throw new RuntimeException('AI provider returned HTTP '.$code.'.');}
    $j=json_decode($resp,true);$text=(string)($j['choices'][0]['message']['content']??$j['output_text']??'');
    if(trim($text)===''){ai_log('external',$provider,$prompt,false,$ms,'Empty response');throw new RuntimeException('AI provider returned an empty response.');}
    ai_log('external',$provider,$prompt,true,$ms);return trim($text);
}

function ai_local_content(string $type,string $topic,string $language='en',string $tone='professional'): array {
    $topic=trim($topic);$language=strtolower($language)==='ur'?'ur':'en';$label=ucwords(str_replace('_',' ',$type));
    if($language==='ur'){$title=$topic.' — مکمل رہنمائی';$body="موضوع: {$topic}\n\nیہ {$label} کے لیے ایک ابتدائی ڈرافٹ ہے۔ اہم معلومات، مقامی تفصیل، رابطہ/عملی اقدامات اور تصدیق شدہ حقائق شامل کریں۔ شائع کرنے سے پہلے ایڈیٹر لازماً جائزہ لے۔";}
    else{$title=$topic.' — Local Guide';$body="Topic: {$topic}\n\nThis is a structured {$label} draft for ShahkotPK. Add verified local facts, useful context, clear next steps, contact/location details where relevant, and review everything before publishing.";}
    return ['title'=>$title,'body'=>$body,'provider'=>'local'];
}
function ai_generate_content(string $type,string $topic,string $language='en',string $tone='professional'): array {
    if(!setting_bool('ai_content_enabled',true))throw new RuntimeException('AI Content Assistant is disabled.');$topic=trim($topic);if($topic==='')throw new RuntimeException('Enter a topic.');
    $result=ai_local_content($type,$topic,$language,$tone);$provider=strtolower((string)setting('ai_provider','local'));if(is_file(__DIR__.'/ai_orchestrator_v710.php')){require_once __DIR__.'/ai_orchestrator_v710.php';if(function_exists('ai710_provider')&&($np=ai710_provider()))$provider=(string)($np['name']?:$np['provider_type']);}
    if($provider!=='local'&&($provider!=='')){$system='You are a careful city-platform content assistant. Draft original concise content. Never invent addresses, prices, medical claims, legal facts or breaking-news facts. Mark facts requiring verification. Do not publish automatically.';$prompt='Content type: '.$type."\nLanguage: ".$language."\nTone: ".$tone."\nTopic: ".$topic."\nReturn a title, then body.";try{$text=ai_external_call($system,$prompt);$lines=preg_split('/\R/',$text);$title=trim((string)array_shift($lines));$body=trim(implode("\n",$lines));if($body===''){$body=$text;$title=$topic;}$result=['title'=>trim($title,"# *\t"),'body'=>$body,'provider'=>$provider];}catch(Throwable $e){$result['warning']=$e->getMessage().' Local draft used instead.';}}
    $u=current_user();if($u){try{db()->prepare('INSERT INTO ai_content_drafts(user_id,content_type,language,topic,generated_title,generated_body,meta_text) VALUES(?,?,?,?,?,?,?)')->execute([(int)$u['id'],$type,$language,$topic,$result['title'],$result['body'],json_encode(['provider'=>$result['provider'],'tone'=>$tone],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){}}
    return $result;
}

function ai_number_value(string $number,string $unit=''): float {
    $v=(float)str_replace(',','',$number);$u=strtolower(trim($unit));
    if($u==='k')$v*=1000;elseif($u==='m')$v*=1000000;elseif(in_array($u,['lakh','lac'],true))$v*=100000;elseif(in_array($u,['crore','cr'],true))$v*=10000000;
    return $v;
}
function ai_extract_budget(string $q): array {
    $out=['min'=>null,'max'=>null];$clean=strtolower(str_replace(['pkr','rs.','rs '],'',$q));
    if(preg_match('/(?:between|from)\s*([0-9,.]+)\s*(k|m|lakh|lac|crore|cr)?\s*(?:and|to|-)\s*([0-9,.]+)\s*(k|m|lakh|lac|crore|cr)?/i',$clean,$m)){$out['min']=ai_number_value($m[1],$m[2]??'');$out['max']=ai_number_value($m[3],$m[4]??'');return $out;}
    if(preg_match('/(?:under|below|less than|upto|up to)\s*([0-9,.]+)\s*(k|m|lakh|lac|crore|cr)?/i',$clean,$m))$out['max']=ai_number_value($m[1],$m[2]??'');
    if(preg_match('/(?:over|above|more than|minimum|min)\s*([0-9,.]+)\s*(k|m|lakh|lac|crore|cr)?/i',$clean,$m))$out['min']=ai_number_value($m[1],$m[2]??'');
    return $out;
}
function ai_query_terms(string $query): array {
    $text=mb_strtolower(trim($query),'UTF-8');$text=preg_replace('/[^\pL\pN\s-]+/u',' ',$text);$raw=preg_split('/\s+/u',$text,-1,PREG_SPLIT_NO_EMPTY)?:[];
    $stop=['best','near','me','in','the','a','an','find','show','for','please','looking','need','want','under','below','above','over','from','to','and','shahkot','rs','pkr','ka','ki','kay','ke','main','mein','mujhe','muje'];$out=[];
    foreach($raw as $t){if(mb_strlen($t,'UTF-8')<2||in_array($t,$stop,true)||preg_match('/^[0-9,.]+$/',$t))continue;$out[$t]=$t;}
    return array_values($out);
}
function ai_detect_intent(string $query): array {
    $q=mb_strtolower($query,'UTF-8');$budget=ai_extract_budget($q);$types=[];
    foreach(['property'=>['property','house','home','plot','rent','apartment','flat'],'job'=>['job','jobs','vacancy','hiring','career'],'deal'=>['deal','discount','offer','sale'],'event'=>['event','events','festival','seminar'],'guide'=>['hospital','school','college','office','helpline','place'],'food'=>['food','restaurant','cafe','pizza','burger']] as $type=>$words){foreach($words as $w){if(mb_strpos($q,$w)!==false){$types[]=$type;break;}}}
    $productType=null;if(preg_match('/\bused\b/u',$q))$productType='used';elseif(preg_match('/\bdigital\b/u',$q))$productType='digital';elseif(preg_match('/\bnew\b/u',$q))$productType='new';
    $saleMode=(strpos($q,'auction')!==false||strpos($q,'bid')!==false)?'auction':null;
    return ['query'=>$query,'keywords'=>ai_query_terms($query),'budget'=>$budget,'content_types'=>array_values(array_unique($types)),'product_type'=>$productType,'sale_mode'=>$saleMode];
}
function ai_text_score(string $haystack,array $terms): float {
    $h=mb_strtolower($haystack,'UTF-8');$score=0.0;foreach($terms as $i=>$t){if($t===''||mb_strpos($h,$t)===false)continue;$score+=($i===0?24:14);if(preg_match('/\b'.preg_quote($t,'/').'\b/u',$h))$score+=8;}return $score;
}
function ai_track_search(string $query,array $intent,int $count,int $latency): void {
    if(!setting_bool('ai_search_learning_enabled',true)||!ai_table_exists('ai_search_events'))return;
    try{$u=current_user();db()->prepare('INSERT INTO ai_search_events(user_id,query_text,intent_json,result_count,duration_ms) VALUES(?,?,?,?,?)')->execute([$u?(int)$u['id']:null,mb_substr($query,0,500,'UTF-8'),json_encode($intent,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$count,$latency]);}catch(Throwable $e){}
}
function ai_smart_search(string $query,int $limit=30): array {
    if(!setting_bool('ai_smart_search_enabled',true))return ['businesses'=>[],'products'=>[],'city_content'=>[],'intent'=>[]];$q=trim($query);if($q==='')return ['businesses'=>[],'products'=>[],'city_content'=>[],'intent'=>[]];
    $start=microtime(true);$intent=ai_detect_intent($q);$terms=$intent['keywords'];if(!$terms)$terms=[mb_strtolower($q,'UTF-8')];$fetch=max(30,min(150,$limit*4));$city=function_exists('tenant_query_city_id')?tenant_query_city_id():0;
    $cacheKey = 'ai_search_'.md5($q.'_'.$limit.'_'.$city.json_encode($intent)); $cacheFile = sys_get_temp_dir().'/'.$cacheKey.'.json'; if(file_exists($cacheFile) && filemtime($cacheFile) > time() - 300) { $cached = json_decode(file_get_contents($cacheFile), true); if($cached) return $cached; }
    $likes=[];$params=[];foreach(array_slice($terms,0,6) as $t){$likes[]='(b.name LIKE ? OR b.description LIKE ? OR cat.name LIKE ? OR b.address LIKE ?)';$v='%'.$t.'%';array_push($params,$v,$v,$v,$v);}
    $businesses=[];if($likes){$where="b.status=1 AND (".implode(' OR ',$likes).')';if($city>0){$where.=' AND b.city_id=?';$params[]=$city;}$rows=ai_rows("SELECT b.id,b.name,b.slug,b.address,b.phone,b.verification_status,b.is_featured,b.city_id,b.category_id,COALESCE(b.image,'') image_url,COALESCE(c.name,'') city_name,COALESCE(cat.name,'') category_name FROM businesses b LEFT JOIN cities c ON c.id=b.city_id LEFT JOIN categories cat ON cat.id=b.category_id WHERE {$where} ORDER BY b.is_featured DESC,b.id DESC LIMIT {$fetch}",$params);foreach($rows as $r){$score=ai_text_score(($r['name']??'').' '.($r['category_name']??'').' '.($r['address']??''),$terms);if(($r['verification_status']??'')==='verified')$score+=18;if(!empty($r['is_featured']))$score+=12;$r['_score']=$score;$businesses[]=$r;}usort($businesses,fn($a,$b)=>$b['_score']<=>$a['_score']);$businesses=array_slice($businesses,0,$limit);}
    $plikes=[];$pp=[];foreach(array_slice($terms,0,6) as $t){$plikes[]='(p.title LIKE ? OR p.short_description LIKE ? OR sc.name LIKE ? OR p.location_text LIKE ?)';$v='%'.$t.'%';array_push($pp,$v,$v,$v,$v);} $products=[];
    if($plikes){$where="p.status='published' AND (".implode(' OR ',$plikes).')';if($intent['budget']['max']!==null){$where.=' AND p.price<=?';$pp[]=$intent['budget']['max'];}if($intent['budget']['min']!==null){$where.=' AND p.price>=?';$pp[]=$intent['budget']['min'];}if($intent['product_type']){$where.=' AND p.product_type=?';$pp[]=$intent['product_type'];}if($intent['sale_mode']){$where.=' AND p.sale_mode=?';$pp[]=$intent['sale_mode'];}if($city>0){$where.=' AND p.city_id=?';$pp[]=$city;}
        $rows=ai_rows("SELECT p.id,p.title,p.slug,p.price,p.product_type,p.sale_mode,p.image_url,p.featured,p.views,p.category_id,p.city_id,COALESCE(c.name,'') city_name,COALESCE(sc.name,'') category_name FROM store_products p JOIN store_categories sc ON sc.id=p.category_id LEFT JOIN cities c ON c.id=p.city_id WHERE {$where} ORDER BY p.featured DESC,p.views DESC,p.id DESC LIMIT {$fetch}",$pp);foreach($rows as $r){$score=ai_text_score(($r['title']??'').' '.($r['category_name']??''),$terms)+(min(20,log(1+(int)($r['views']??0))*3));if(!empty($r['featured']))$score+=14;if($intent['product_type']&&$intent['product_type']===$r['product_type'])$score+=15;$r['_score']=$score;$products[]=$r;}usort($products,fn($a,$b)=>$b['_score']<=>$a['_score']);$products=array_slice($products,0,$limit);}
    $clikes=[];$cp=[];foreach(array_slice($terms,0,6) as $t){$clikes[]='(title LIKE ? OR summary LIKE ? OR category LIKE ? OR address LIKE ?)';$v='%'.$t.'%';array_push($cp,$v,$v,$v,$v);} $content=[];
    if($clikes){$where="status='published' AND (".implode(' OR ',$clikes).')';$ct=array_values(array_intersect($intent['content_types'],['property','job','deal','event','guide']));if($ct){$ph=implode(',',array_fill(0,count($ct),'?'));$where.=" AND content_type IN ({$ph})";array_push($cp,...$ct);}if($city>0){$where.=' AND city_id=?';$cp[]=$city;}$rows=ai_rows("SELECT id,content_type,title,slug,summary,category,address,price,featured,city_id,image_url,created_at FROM city_portal_items WHERE {$where} ORDER BY featured DESC,id DESC LIMIT {$fetch}",$cp);foreach($rows as $r){$score=ai_text_score(($r['title']??'').' '.($r['category']??'').' '.($r['summary']??''),$terms);if(!empty($r['featured']))$score+=12;if(in_array($r['content_type'],$ct,true))$score+=18;$r['_score']=$score;$content[]=$r;}usort($content,fn($a,$b)=>$b['_score']<=>$a['_score']);$content=array_slice($content,0,$limit);}
    $total=count($businesses)+count($products)+count($content);$ms=(int)round((microtime(true)-$start)*1000);ai_track_search($q,$intent,$total,$ms); $res = ['businesses'=>$businesses,'products'=>$products,'city_content'=>$content,'intent'=>$intent,'meta'=>['count'=>$total,'duration_ms'=>$ms,'version'=>'5.0.0','tenant_id'=>function_exists('tenant_id')?tenant_id():0]]; file_put_contents($cacheFile, json_encode($res, JSON_UNESCAPED_UNICODE)); return $res;
}

function ai_build_user_profile(int $userId,bool $persist=true): array {
    $profile=['user_id'=>$userId,'cities'=>[],'business_categories'=>[],'product_categories'=>[],'product_types'=>[],'content_types'=>[],'signals'=>0];if($userId<=0)return $profile;
    $days=max(7,min(365,setting_int('ai_recommendation_window_days',45)));
    if(ai_table_exists('analytics_events')){$rows=ai_rows("SELECT event_type,entity_type,entity_id,business_id,COUNT(*) hits FROM analytics_events WHERE user_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL {$days} DAY) GROUP BY event_type,entity_type,entity_id,business_id ORDER BY hits DESC LIMIT 300",[$userId]);foreach($rows as $r){$w=max(1,(int)$r['hits']);$profile['signals']+=$w;if((int)($r['business_id']??0)>0){$b=ai_rows('SELECT city_id,category_id FROM businesses WHERE id=? LIMIT 1',[(int)$r['business_id']]);if($b){$profile['cities'][(int)$b[0]['city_id']]=($profile['cities'][(int)$b[0]['city_id']]??0)+$w;$profile['business_categories'][(int)$b[0]['category_id']]=($profile['business_categories'][(int)$b[0]['category_id']]??0)+$w;}}if(($r['entity_type']??'')==='product'&&(int)$r['entity_id']>0){$p=ai_rows('SELECT city_id,category_id,product_type FROM store_products WHERE id=? LIMIT 1',[(int)$r['entity_id']]);if($p){if((int)$p[0]['city_id']>0)$profile['cities'][(int)$p[0]['city_id']]=($profile['cities'][(int)$p[0]['city_id']]??0)+$w;$profile['product_categories'][(int)$p[0]['category_id']]=($profile['product_categories'][(int)$p[0]['category_id']]??0)+$w;$profile['product_types'][$p[0]['product_type']]=($profile['product_types'][$p[0]['product_type']]??0)+$w;}}}}
    if(ai_table_exists('store_orders')){$rows=ai_rows("SELECT p.city_id,p.category_id,p.product_type,SUM(oi.quantity) hits FROM store_orders o JOIN store_order_items oi ON oi.order_id=o.id JOIN store_products p ON p.id=oi.product_id WHERE o.buyer_user_id=? AND o.status<>'cancelled' GROUP BY p.city_id,p.category_id,p.product_type ORDER BY hits DESC LIMIT 80",[$userId]);foreach($rows as $r){$w=max(2,(int)$r['hits']*3);if((int)$r['city_id']>0)$profile['cities'][(int)$r['city_id']]=($profile['cities'][(int)$r['city_id']]??0)+$w;$profile['product_categories'][(int)$r['category_id']]=($profile['product_categories'][(int)$r['category_id']]??0)+$w;$profile['product_types'][$r['product_type']]=($profile['product_types'][$r['product_type']]??0)+$w;$profile['signals']+=$w;}}
    if(ai_table_exists('ai_recommendation_events')){$events=ai_rows("SELECT entity_type,entity_id,event_type,COUNT(*) hits FROM ai_recommendation_events WHERE user_id=? AND event_type IN('click','favorite','contact','order') AND created_at>=DATE_SUB(NOW(),INTERVAL {$days} DAY) GROUP BY entity_type,entity_id,event_type ORDER BY hits DESC LIMIT 180",[$userId]);$weights=['click'=>2,'favorite'=>5,'contact'=>6,'order'=>8];foreach($events as $ev){$w=max(1,(int)$ev['hits']*($weights[$ev['event_type']]??2));$et=(string)$ev['entity_type'];$eid=(int)$ev['entity_id'];if($et==='business'){$r=ai_rows('SELECT city_id,category_id FROM businesses WHERE id=? LIMIT 1',[$eid]);if($r){$profile['cities'][(int)$r[0]['city_id']]=($profile['cities'][(int)$r[0]['city_id']]??0)+$w;$profile['business_categories'][(int)$r[0]['category_id']]=($profile['business_categories'][(int)$r[0]['category_id']]??0)+$w;}}elseif($et==='product'){$r=ai_rows('SELECT city_id,category_id,product_type FROM store_products WHERE id=? LIMIT 1',[$eid]);if($r){if((int)$r[0]['city_id']>0)$profile['cities'][(int)$r[0]['city_id']]=($profile['cities'][(int)$r[0]['city_id']]??0)+$w;$profile['product_categories'][(int)$r[0]['category_id']]=($profile['product_categories'][(int)$r[0]['category_id']]??0)+$w;$profile['product_types'][$r[0]['product_type']]=($profile['product_types'][$r[0]['product_type']]??0)+$w;}}elseif(in_array($et,['guide','deal','event','job','property'],true)){$r=ai_rows('SELECT city_id FROM city_portal_items WHERE id=? LIMIT 1',[$eid]);if($r&&(int)$r[0]['city_id']>0)$profile['cities'][(int)$r[0]['city_id']]=($profile['cities'][(int)$r[0]['city_id']]??0)+$w;$profile['content_types'][$et]=($profile['content_types'][$et]??0)+$w;}$profile['signals']+=$w;}}
    if(ai_table_exists('favorite_businesses')){$rows=ai_rows('SELECT b.city_id,b.category_id FROM favorite_businesses f JOIN businesses b ON b.id=f.business_id WHERE f.user_id=? LIMIT 100',[$userId]);foreach($rows as $r){$profile['cities'][(int)$r['city_id']]=($profile['cities'][(int)$r['city_id']]??0)+5;$profile['business_categories'][(int)$r['category_id']]=($profile['business_categories'][(int)$r['category_id']]??0)+7;$profile['signals']+=7;}}
    foreach(['cities','business_categories','product_categories','product_types','content_types'] as $k){arsort($profile[$k]);$profile[$k]=array_slice($profile[$k],0,10,true);}
    if($persist&&setting_bool('ai_personalization_enabled',true)&&ai_table_exists('ai_user_profiles')){try{db()->prepare('INSERT INTO ai_user_profiles(user_id,profile_json,last_event_at,refreshed_at) VALUES(?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE profile_json=VALUES(profile_json),last_event_at=VALUES(last_event_at),refreshed_at=NOW()')->execute([$userId,json_encode($profile,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);if(ai_table_exists('ai_recommendation_cache'))db()->prepare('DELETE FROM ai_recommendation_cache WHERE user_id=?')->execute([$userId]);}catch(Throwable $e){}}
    return $profile;
}
function ai_user_profile(int $userId): array {
    if($userId<=0||!setting_bool('ai_personalization_enabled',true))return ['user_id'=>$userId,'cities'=>[],'business_categories'=>[],'product_categories'=>[],'product_types'=>[],'content_types'=>[],'signals'=>0];
    if(ai_table_exists('ai_user_profiles')){$r=ai_rows('SELECT profile_json,refreshed_at FROM ai_user_profiles WHERE user_id=? LIMIT 1',[$userId]);if($r&&strtotime((string)$r[0]['refreshed_at'])>time()-max(5,setting_int('ai_recommendation_cache_minutes',20))*60){$j=json_decode((string)$r[0]['profile_json'],true);if(is_array($j))return $j;}}
    return ai_build_user_profile($userId,true);
}
function ai_popularity_map(string $entityType,int $days=30): array {
    if(!ai_table_exists('analytics_events'))return [];$days=max(7,min(180,$days));$rows=ai_rows("SELECT entity_id,COUNT(*) hits FROM analytics_events WHERE entity_type=? AND entity_id IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL {$days} DAY) GROUP BY entity_id ORDER BY hits DESC LIMIT 500",[$entityType]);$out=[];foreach($rows as $r)$out[(int)$r['entity_id']]=(int)$r['hits'];return $out;
}
function ai_rec_link(array $r): string {
    if(($r['entity_type']??'')==='product')return '/product.php?slug='.urlencode((string)$r['slug']);
    if(($r['entity_type']??'')==='business')return '/business.php?slug='.urlencode((string)$r['slug']);
    $type=(string)($r['content_type']??$r['entity_type']??'guide');$routes=['guide'=>'/city-guide.php','deal'=>'/deals.php','event'=>'/events.php','job'=>'/jobs.php','property'=>'/property.php'];$route=$routes[$type]??'/city-guide.php';return $route.'?slug='.urlencode((string)$r['slug']);
}
function ai_rec_cache_get(int $userId,string $key): ?array {
    if(!ai_table_exists('ai_recommendation_cache'))return null;
    try{$q=db()->prepare('SELECT payload_json FROM ai_recommendation_cache WHERE user_id=? AND cache_key=? AND expires_at>NOW() LIMIT 1');$q->execute([$userId,$key]);$raw=$q->fetchColumn();if(!$raw)return null;$j=json_decode((string)$raw,true);return is_array($j)?$j:null;}catch(Throwable $e){return null;}
}
function ai_rec_cache_put(int $userId,string $key,array $rows): void {
    if(!ai_table_exists('ai_recommendation_cache'))return;$minutes=max(5,min(1440,setting_int('ai_recommendation_cache_minutes',20)));try{db()->prepare("INSERT INTO ai_recommendation_cache(user_id,cache_key,payload_json,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL {$minutes} MINUTE)) ON DUPLICATE KEY UPDATE payload_json=VALUES(payload_json),expires_at=VALUES(expires_at),updated_at=NOW()")->execute([$userId,$key,json_encode($rows,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){}
}
function ai_track_recommendation_event(?int $userId,string $entityType,int $entityId,string $eventType='impression',float $score=0): void {
    if(!setting_bool('ai_learning_enabled',true)||!ai_table_exists('ai_recommendation_events')||$entityId<=0)return;$allowed=['impression','click','favorite','contact','order','dismiss'];if(!in_array($eventType,$allowed,true))$eventType='impression';try{db()->prepare('INSERT INTO ai_recommendation_events(user_id,entity_type,entity_id,event_type,score) VALUES(?,?,?,?,?)')->execute([$userId?:null,$entityType,$entityId,$eventType,$score]);}catch(Throwable $e){}
}
function ai_recommendations(?int $userId=null,int $limit=8): array {
    if(!setting_bool('ai_recommendations_enabled',true))return [];$limit=max(1,min(40,$limit));$cacheUser=$userId?:0;$city=function_exists('tenant_query_city_id')?tenant_query_city_id():0;$tenantId=function_exists('tenant_id')?tenant_id():0;$cacheKey='tenant-'.$tenantId.'-city-'.$city.'-recommendations-'.$limit;$cached=ai_rec_cache_get($cacheUser,$cacheKey);if($cached!==null){if($userId){foreach($cached as $r)ai_track_recommendation_event($userId,(string)($r['entity_type']??'business'),(int)($r['entity_id']??0),'impression',(float)($r['score']??0));}return $cached;}$profile=$userId?ai_user_profile($userId):['cities'=>[],'business_categories'=>[],'product_categories'=>[],'product_types'=>[],'signals'=>0];$personal=setting_bool('ai_personalization_enabled',true)&&$userId&&($profile['signals']??0)>0;$popWeight=max(0,min(50,setting_int('ai_trending_weight',20)));$affWeight=max(0,min(80,setting_int('ai_affinity_weight',35)));$rows=[];
    $bPop=ai_popularity_map('business');$bp=[];$bw="b.status=1";if($city>0){$bw.=' AND b.city_id=?';$bp[]=$city;}$businesses=ai_rows("SELECT b.id,b.name title,b.slug,COALESCE(b.image,'') image_url,COALESCE(c.name,'') city_name,b.city_id,b.category_id,b.verification_status,b.is_featured FROM businesses b LEFT JOIN cities c ON c.id=b.city_id WHERE {$bw} ORDER BY b.is_featured DESC,b.id DESC LIMIT 160",$bp);foreach($businesses as $r){$s=62.0+(($r['verification_status']??'')==='verified'?18:0)+(!empty($r['is_featured'])?12:0);$hits=$bPop[(int)$r['id']]??0;$s+=min($popWeight,log(1+$hits)*5);if($personal){if(isset($profile['cities'][(int)$r['city_id']]))$s+=min(18,$affWeight*0.45);if(isset($profile['business_categories'][(int)$r['category_id']]))$s+=min(28,$affWeight*0.8);}$rows[]=['entity_type'=>'business','entity_id'=>(int)$r['id'],'title'=>$r['title'],'slug'=>$r['slug'],'image_url'=>$r['image_url'],'city_name'=>$r['city_name'],'score'=>round($s,2),'reason'=>$personal?'Matched to your local activity':'Verified and popular locally'];}
    $pPop=ai_popularity_map('product');$pp=[];$pw="p.status='published'";if($city>0){$pw.=' AND p.city_id=?';$pp[]=$city;}$products=ai_rows("SELECT p.id,p.title,p.slug,COALESCE(p.image_url,'') image_url,COALESCE(c.name,'') city_name,p.city_id,p.category_id,p.product_type,p.featured,p.views FROM store_products p LEFT JOIN cities c ON c.id=p.city_id WHERE {$pw} ORDER BY p.featured DESC,p.views DESC,p.id DESC LIMIT 180",$pp);foreach($products as $r){$s=58.0+(!empty($r['featured'])?14:0)+min(14,log(1+(int)$r['views'])*2.2);$hits=$pPop[(int)$r['id']]??0;$s+=min($popWeight,log(1+$hits)*5);if($personal){if(isset($profile['cities'][(int)$r['city_id']]))$s+=min(15,$affWeight*0.4);if(isset($profile['product_categories'][(int)$r['category_id']]))$s+=min(30,$affWeight*0.85);if(isset($profile['product_types'][$r['product_type']]))$s+=min(12,$affWeight*0.35);}$rows[]=['entity_type'=>'product','entity_id'=>(int)$r['id'],'title'=>$r['title'],'slug'=>$r['slug'],'image_url'=>$r['image_url'],'city_name'=>$r['city_name'],'score'=>round($s,2),'reason'=>$personal?'Based on products you explore':'Trending marketplace pick'];}
    if(ai_table_exists('city_portal_items')){$cp=[];$cw="p.status='published'";if($city>0){$cw.=' AND p.city_id=?';$cp[]=$city;}$content=ai_rows("SELECT p.id,p.content_type,p.title,p.slug,COALESCE(p.image_url,'') image_url,COALESCE(c.name,'') city_name,p.city_id,p.featured,p.created_at FROM city_portal_items p LEFT JOIN cities c ON c.id=p.city_id WHERE {$cw} ORDER BY p.featured DESC,p.id DESC LIMIT 120",$cp);foreach($content as $r){$s=50.0+(!empty($r['featured'])?12:0);$age=max(0,(time()-strtotime((string)$r['created_at']))/86400);$s+=max(0,10-min(10,$age/3));if($personal&&isset($profile['cities'][(int)$r['city_id']]))$s+=min(16,$affWeight*0.45);$rows[]=['entity_type'=>$r['content_type'],'content_type'=>$r['content_type'],'entity_id'=>(int)$r['id'],'title'=>$r['title'],'slug'=>$r['slug'],'image_url'=>$r['image_url'],'city_name'=>$r['city_name'],'score'=>round($s,2),'reason'=>'Fresh local '.$r['content_type']];}}
    usort($rows,fn($a,$b)=>$b['score']<=>$a['score']);if(setting_bool('ai_recommendation_diversity_enabled',true)){$div=[];$counts=[];foreach($rows as $r){$k=$r['entity_type'];if(($counts[$k]??0)>=max(2,(int)ceil($limit/2)))continue;$div[]=$r;$counts[$k]=($counts[$k]??0)+1;if(count($div)>=$limit)break;}$rows=$div;}else $rows=array_slice($rows,0,$limit);
    $rows=array_slice($rows,0,$limit);ai_rec_cache_put($cacheUser,$cacheKey,$rows);if($userId){foreach($rows as $r)ai_track_recommendation_event($userId,(string)$r['entity_type'],(int)$r['entity_id'],'impression',(float)$r['score']);}
    return $rows;
}

function ai_automation_tick(bool $manual=false): array {
    $start=microtime(true);$out=['profiles'=>0,'search_pruned'=>0,'cache_pruned'=>0,'status'=>'ok'];if(!setting_bool('ai_automation_enabled',true)&&!$manual)return $out;
    try{if(ai_table_exists('ai_user_profiles')&&ai_table_exists('analytics_events')){$ids=ai_rows('SELECT user_id,MAX(id) last_id FROM analytics_events WHERE user_id IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL 60 DAY) GROUP BY user_id ORDER BY last_id DESC LIMIT 120');foreach($ids as $r){ai_build_user_profile((int)$r['user_id'],true);$out['profiles']++;}}if(ai_table_exists('ai_search_events'))$out['search_pruned']=(int)db()->exec('DELETE FROM ai_search_events WHERE created_at<DATE_SUB(NOW(),INTERVAL 180 DAY)');if(ai_table_exists('ai_recommendation_cache'))$out['cache_pruned']=(int)db()->exec('DELETE FROM ai_recommendation_cache WHERE expires_at<NOW()');}
    catch(Throwable $e){$out['status']='partial';$out['error']=$e->getMessage();if(function_exists('runtime_log'))runtime_log('AI automation tick failed',$e);}
    $ms=(int)round((microtime(true)-$start)*1000);$out['duration_ms']=$ms;if(ai_table_exists('ai_automation_runs')){try{db()->prepare('INSERT INTO ai_automation_runs(run_type,status,processed_count,duration_ms,summary_json) VALUES(?,?,?,?,?)')->execute([$manual?'manual':'scheduled',$out['status'],$out['profiles'],$ms,json_encode($out,JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){}}
    return $out;
}
