<?php
declare(strict_types=1);
require_once __DIR__.'/api_v1.php';

function api_v2_enabled(): bool { return setting_bool('mobile_api_v2_enabled',setting_bool('api_v2_enabled',true)); }
function api_v2_page(): array { $page=max(1,(int)($_GET['page']??1));$per=max(1,min(100,(int)($_GET['per_page']??20)));return [$page,$per,($page-1)*$per]; }
function api_v2_meta(int $page,int $per,int $total): array { return ['page'=>$page,'per_page'=>$per,'total'=>$total,'pages'=>$per>0?(int)ceil($total/$per):0,'has_more'=>$page*$per<$total]; }
function api_v2_ip(): string { return function_exists('security_client_ip')?security_client_ip():substr((string)($_SERVER['REMOTE_ADDR']??''),0,64); }
function api_v2_request_id(): string { static $id='';if($id==='')$id='req_'.bin2hex(random_bytes(8));return $id; }
function api_v2_log(?int $uid,int $status): void { try{db()->prepare('INSERT INTO mobile_api_logs(user_id,endpoint,method,status_code,ip_address,duration_ms) VALUES(?,?,?,?,?,0)')->execute([$uid,substr((string)($_SERVER['REQUEST_URI']??''),0,190),substr((string)($_SERVER['REQUEST_METHOD']??'GET'),0,12),$status,api_v2_ip()]);}catch(Throwable $e){} }
function api_v2_send(array $payload,int $status=200,?int $uid=null): void { api_v2_log($uid,$status);header('X-ShahkotPK-API: v2');header('X-Request-ID: '.api_v2_request_id());api_json(array_merge(['ok'=>$status<400,'api'=>'v2','request_id'=>api_v2_request_id()],$payload),$status); }
function api_v2_ok(array $payload=[],?int $uid=null): void { api_v2_send($payload,200,$uid); }
function api_v2_error(string $message,int $status=400,array $extra=[]): void { api_v2_send(array_merge(['error'=>$message],$extra),$status,null); }
function api_v2_require_enabled(): void { if(!api_v2_enabled())api_v2_error('Mobile API v2 is disabled.',503);if(setting_bool('mobile_app_maintenance',false))api_v2_error('Mobile services are temporarily in maintenance mode.',503,['maintenance'=>true]); }
function api_v2_rate_limit(): void { $limit=max(30,min(1200,setting_int('mobile_api_rate_limit_per_minute',120)));try{$q=db()->prepare("SELECT COUNT(*) FROM mobile_api_logs WHERE ip_address=? AND created_at>=DATE_SUB(NOW(),INTERVAL 1 MINUTE)");$q->execute([api_v2_ip()]);if((int)$q->fetchColumn()>=$limit)api_v2_error('Too many requests. Please retry shortly.',429,['retry_after'=>60]);}catch(Throwable $e){} }
function api_v2_user(string $scope=''): array { api_v2_require_enabled();api_v2_rate_limit();$u=api_user();if($scope!=='')api_scope($u,$scope);return $u; }
function api_v2_table(string $name): bool { static $cache=[];if(isset($cache[$name]))return $cache[$name];if(!preg_match('/^[A-Za-z0-9_]+$/',$name))return false;try{$q=db()->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1');$q->execute([$name]);return $cache[$name]=(bool)$q->fetchColumn();}catch(Throwable $e){return $cache[$name]=false;} }
function api_v2_app_type(array $input=[]): string { $v=strtolower(trim((string)($input['app_type']??$_SERVER['HTTP_X_APP_TYPE']??'customer')));return in_array($v,['customer','seller'],true)?$v:'customer'; }
function api_v2_device_id(array $input=[]): string { $id=trim((string)($input['device_id']??$_SERVER['HTTP_X_DEVICE_ID']??''));return substr($id,0,190); }
function api_v2_access_scopes(string $appType,array $u): string { if($appType==='seller')return 'profile,catalog,orders,seller_products,seller_orders,seller_inventory,seller_finance,pos,notifications';return 'profile,catalog,orders,favorites,notifications'; }
function api_v2_issue_access_token(int $uid,string $device,string $scopes): array { $plain='shp2_'.bin2hex(random_bytes(32));$hash=hash('sha256',$plain);$prefix=substr($plain,0,18);$days=max(1,min(30,setting_int('mobile_access_token_days',7)));db()->prepare("INSERT INTO mobile_api_tokens(user_id,token_hash,token_prefix,device_name,scopes,expires_at) VALUES(?,?,?,?,?,DATE_ADD(NOW(),INTERVAL {$days} DAY))")->execute([$uid,$hash,$prefix,substr($device?:'Mobile App',0,160),$scopes]);return ['access_token'=>$plain,'token_type'=>'Bearer','expires_in'=>$days*86400,'scopes'=>array_values(array_filter(array_map('trim',explode(',',$scopes))))]; }
function api_v2_issue_refresh_token(int $uid,string $deviceId,string $appType): array { $plain='shr_'.bin2hex(random_bytes(40));$hash=hash('sha256',$plain);$prefix=substr($plain,0,18);$days=max(7,min(365,setting_int('mobile_refresh_token_days',90)));db()->prepare("INSERT INTO mobile_api_refresh_tokens(user_id,device_id,app_type,token_hash,token_prefix,expires_at) VALUES(?,?,?,?,?,DATE_ADD(NOW(),INTERVAL {$days} DAY))")->execute([$uid,$deviceId!==''?$deviceId:'unknown',$appType,$hash,$prefix]);return ['refresh_token'=>$plain,'refresh_expires_in'=>$days*86400]; }
function api_v2_issue_session(array $u,array $input): array { $appType=api_v2_app_type($input);$deviceId=api_v2_device_id($input);$deviceName=trim((string)($input['device_name']??ucfirst($appType).' App'))?:ucfirst($appType).' App';$scopes=api_v2_access_scopes($appType,$u);$auth=array_merge(api_v2_issue_access_token((int)$u['id'],$deviceName,$scopes),api_v2_issue_refresh_token((int)$u['id'],$deviceId,$appType));api_v2_register_device((int)$u['id'],$input,$appType);return $auth; }
function api_v2_register_device(int $uid,array $input,string $appType='customer'): void { if(!api_v2_table('mobile_app_devices'))return;$device=api_v2_device_id($input);if($device==='')return;$platform=strtolower((string)($input['platform']??'web'));if(!in_array($platform,['android','ios','web'],true))$platform='web';$ip=api_v2_ip();try{db()->prepare("INSERT INTO mobile_app_devices(user_id,device_id,app_type,platform,device_name,os_version,app_version,build_number,locale,timezone,push_token,last_ip,last_seen_at,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW(),1) ON DUPLICATE KEY UPDATE platform=VALUES(platform),device_name=VALUES(device_name),os_version=VALUES(os_version),app_version=VALUES(app_version),build_number=VALUES(build_number),locale=VALUES(locale),timezone=VALUES(timezone),push_token=COALESCE(VALUES(push_token),push_token),last_ip=VALUES(last_ip),last_seen_at=NOW(),status=1")->execute([$uid,$device,$appType,$platform,substr(trim((string)($input['device_name']??'')),0,190)?:null,substr(trim((string)($input['os_version']??'')),0,90)?:null,substr(trim((string)($input['app_version']??'')),0,60)?:null,(int)($input['build_number']??0)?:null,substr(trim((string)($input['locale']??'')),0,30)?:null,substr(trim((string)($input['timezone']??'')),0,80)?:null,trim((string)($input['push_token']??''))?:null,$ip?:null]);}catch(Throwable $e){} }
function api_v2_event(?int $uid,string $event,array $meta=[]): void { if(!api_v2_table('mobile_app_events'))return;try{db()->prepare('INSERT INTO mobile_app_events(user_id,device_id,app_type,event_key,screen_name,app_version,meta_json) VALUES(?,?,?,?,?,?,?)')->execute([$uid,api_v2_device_id($meta)?:null,api_v2_app_type($meta),substr($event,0,100),substr((string)($meta['screen_name']??''),0,120)?:null,substr((string)($meta['app_version']??''),0,60)?:null,json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){} }
function api_v2_seller_context(array $u,string $permission=''): array { $uid=(int)$u['user_id'];if(($u['role']??'')==='shopkeeper')return ['owner_id'=>$uid,'is_staff'=>false,'permissions'=>['*'],'user'=>$u];try{$q=db()->prepare('SELECT owner_user_id,permissions_json FROM seller_staff WHERE staff_user_id=? AND status=1 ORDER BY id');$q->execute([$uid]);foreach($q->fetchAll() as $r){$p=json_decode((string)$r['permissions_json'],true);$p=is_array($p)?$p:[];if($permission===''||in_array('*',$p,true)||in_array($permission,$p,true))return ['owner_id'=>(int)$r['owner_user_id'],'is_staff'=>true,'permissions'=>$p,'user'=>$u];}}catch(Throwable $e){}api_v2_error('Seller access is not assigned to this account.',403); }
function api_v2_seller_can(array $ctx,string $permission): bool { return empty($ctx['is_staff'])||in_array('*',$ctx['permissions']??[],true)||in_array($permission,$ctx['permissions']??[],true); }
function api_v2_user_public(array $u): array { return ['id'=>(int)($u['user_id']??$u['id']??0),'name'=>(string)($u['name']??''),'email'=>(string)($u['email']??''),'phone'=>(string)($u['phone']??''),'role'=>(string)($u['role']??'user')]; }
function api_v2_active_release(string $appType,string $platform): ?array { if(!api_v2_table('mobile_app_releases'))return null;try{$q=db()->prepare("SELECT app_type,platform,version_name,build_number,min_supported_version,force_update,store_url,release_notes,published_at FROM mobile_app_releases WHERE app_type=? AND platform=? AND status='active' ORDER BY build_number DESC,id DESC LIMIT 1");$q->execute([$appType,$platform]);return $q->fetch()?:null;}catch(Throwable $e){return null;} }
function api_v2_idempotency_get(int $uid,string $key,string $endpoint): ?array { if($key===''||!api_v2_table('mobile_api_idempotency'))return null;try{$q=db()->prepare('SELECT response_json FROM mobile_api_idempotency WHERE user_id=? AND idempotency_key=? AND endpoint=? AND expires_at>NOW() LIMIT 1');$q->execute([$uid,$key,$endpoint]);$j=$q->fetchColumn();$d=$j?json_decode((string)$j,true):null;return is_array($d)?$d:null;}catch(Throwable $e){return null;} }
function api_v2_idempotency_save(int $uid,string $key,string $endpoint,array $response): void { if($key===''||!api_v2_table('mobile_api_idempotency'))return;try{db()->prepare("INSERT INTO mobile_api_idempotency(user_id,idempotency_key,endpoint,response_json,expires_at) VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR)) ON DUPLICATE KEY UPDATE response_json=VALUES(response_json),expires_at=VALUES(expires_at)")->execute([$uid,$key,$endpoint,json_encode($response,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){} }
