<?php
declare(strict_types=1);
/** ShahkotPK v12.7.8 — unified public visibility + map indexing for manual and imported businesses. */
if(!function_exists('bs1278_table')){
function bs1278_table(string $t): bool {static $c=[];if(isset($c[$t]))return $c[$t];if(!preg_match('/^[A-Za-z][A-Za-z0-9_]{0,63}$/',$t))return false;try{$q=db()->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1');$q->execute([$t]);return $c[$t]=(bool)$q->fetchColumn();}catch(Throwable $e){return $c[$t]=false;}}
function bs1278_cols(string $t): array {static $c=[];if(isset($c[$t]))return $c[$t];if(!bs1278_table($t))return $c[$t]=[];try{$q=db()->prepare('SELECT COLUMN_NAME,DATA_TYPE,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$t]);$o=[];foreach($q->fetchAll()?:[] as $r)$o[(string)$r['COLUMN_NAME']]=$r;return $c[$t]=$o;}catch(Throwable $e){return $c[$t]=[];}}
function bs1281_status_value(array $col,$v){$type=strtolower((string)($col['DATA_TYPE']??''));$sv=strtolower(trim((string)$v));if(in_array($type,['tinyint','smallint','mediumint','int','bigint','bit'],true)){if(in_array($sv,['active','published','approved','public','enabled','verified','yes','true','1'],true))return 1;if(in_array($sv,['inactive','pending','draft','disabled','deleted','rejected','hidden','no','false','0',''],true))return 0;}return $v;}
function bs1281_status_public($v,array $col=[]): bool {$type=strtolower((string)($col['DATA_TYPE']??''));if(in_array($type,['tinyint','smallint','mediumint','int','bigint','bit'],true))return (int)$v===1;$sv=strtolower(trim((string)$v));if($sv==='')return true;return in_array($sv,['active','published','approved','public','enabled','verified','1'],true);}
function bs1278_tid(): int {try{if(function_exists('tenant_id'))return max(0,(int)tenant_id());if(function_exists('current_tenant')){$t=current_tenant();return max(0,(int)($t['id']??0));}}catch(Throwable $e){}return 0;}
function bs1278_now(): string{return date('Y-m-d H:i:s');}
function bs1278_filter(string $t,array $d): array {$c=bs1278_cols($t);$o=[];foreach($d as $k=>$v)if(isset($c[$k])){$type=strtolower((string)($c[$k]['DATA_TYPE']??''));if(in_array($k,['status','listing_status','publish_status','moderation_status','approval_status','visibility'],true))$v=bs1281_status_value($c[$k],$v);if($v===''&&($c[$k]['IS_NULLABLE']??'NO')==='YES')$v=null;if(in_array($type,['tinyint','smallint','mediumint','int','bigint','bit'],true)&&$v!==null&&$v!=='')$v=(int)$v;if(in_array($type,['decimal','float','double'],true)&&$v!==null&&$v!=='')$v=(float)$v;$o[$k]=$v;}return $o;}
function bs1278_update(string $t,int $id,array $d): void {$d=bs1278_filter($t,$d);unset($d['id']);if($id<1||!$d)return;$set=[];foreach(array_keys($d) as $k)$set[]='`'.$k.'`=?';$q=db()->prepare('UPDATE `'.$t.'` SET '.implode(',',$set).' WHERE id=? LIMIT 1');$q->execute([...array_values($d),$id]);}
function bs1278_insert(string $t,array $d): int {$d=bs1278_filter($t,$d);if(!$d)return 0;$ks=array_keys($d);$q=db()->prepare('INSERT INTO `'.$t.'` (`'.implode('`,`',$ks).'`) VALUES ('.implode(',',array_fill(0,count($ks),'?')).')');$q->execute(array_values($d));return (int)db()->lastInsertId();}
function bs1278_business(int $bid): array {if($bid<1||!bs1278_table('businesses'))return [];try{$q=db()->prepare('SELECT * FROM businesses WHERE id=? LIMIT 1');$q->execute([$bid]);return $q->fetch()?:[];}catch(Throwable $e){return [];}}
function bs1278_shahkot_city_id(): int {if(!bs1278_table('cities'))return 0;$c=bs1278_cols('cities');$name=isset($c['name'])?'name':(isset($c['city_name'])?'city_name':(isset($c['title'])?'title':''));if($name==='')return 0;try{$sql="SELECT id FROM cities WHERE LOWER(REPLACE(REPLACE(TRIM(`$name`),' ',''),'-','')) IN ('shahkot','shahkott') ORDER BY id ASC LIMIT 1";return (int)(db()->query($sql)->fetchColumn()?:0);}catch(Throwable $e){return 0;}}
function bs1278_valid_geo($lat,$lng): bool {$lat=(float)$lat;$lng=(float)$lng;return $lat>=31.45&&$lat<=31.70&&$lng>=73.35&&$lng<=73.65;}
function bs1278_parse_map_url(string $url): array {$url=trim($url);if($url==='')return [0.0,0.0];foreach(['/[@!](-?\d{1,2}\.\d+),(-?\d{1,3}\.\d+)/','/[?&](?:q|query|ll)=(-?\d{1,2}\.\d+)%?2C(-?\d{1,3}\.\d+)/i'] as $re){if(preg_match($re,$url,$m)){return [(float)$m[1],(float)$m[2]];}}return [0.0,0.0];}
function bs1278_name_norm(string $s): string {$s=mb_strtolower(trim($s));$s=preg_replace('/[^a-z0-9\x{0600}-\x{06ff}]+/u',' ',$s);return trim(preg_replace('/\s+/',' ',$s));}
function bs1278_phone_norm(string $s): string {$s=preg_replace('/\D+/','',$s);if(str_starts_with($s,'0092'))$s=substr($s,2);if(str_starts_with($s,'0'))$s='92'.substr($s,1);return $s;}
function bs1278_google_geo(array $b): array {
 $imp=__DIR__.'/business_source_import_v1270.php';if(is_file($imp))require_once $imp;
 if(!function_exists('bs1270_google_search')||!function_exists('bs1270_google_detail')||!function_exists('bs1270_shahkot_check'))return ['ok'=>false,'reason'=>'Google Places helper is unavailable.'];
 try{if(function_exists('bs1270_google_key')&&trim((string)bs1270_google_key())==='')return ['ok'=>false,'reason'=>'Server Places API key is not configured.'];}catch(Throwable $e){return ['ok'=>false,'reason'=>'Google Places key is not available.'];}
 $name=trim((string)($b['name']??''));if($name==='')return ['ok'=>false,'reason'=>'Business name is missing.'];$addr=trim((string)($b['address']??''));$area=trim((string)($b['area']??''));$query=$name.' '.($addr?:$area).' Shahkot Punjab Pakistan';
 try{$s=bs1270_google_search($query);$best=[];$bestScore=0.0;$target=bs1278_name_norm($name);$targetPhone=bs1278_phone_norm((string)($b['phone']??''));foreach(array_slice((array)($s['ids']??[]),0,5) as $pid){$g=bs1270_google_detail((string)$pid);$geo=bs1270_shahkot_check($g);if(empty($geo['ok']))continue;$gn=bs1278_name_norm((string)($g['displayName']['text']??''));similar_text($target,$gn,$pct);$score=(float)$pct;$gp=bs1278_phone_norm((string)($g['nationalPhoneNumber']??$g['internationalPhoneNumber']??''));if($targetPhone!==''&&$gp!==''&&$targetPhone===$gp)$score+=15;$gaddr=mb_strtolower((string)($g['formattedAddress']??''));if($addr!==''&&str_contains($gaddr,mb_strtolower(mb_substr($addr,0,min(18,mb_strlen($addr))))))$score+=6;if($score>$bestScore){$bestScore=$score;$best=['g'=>$g,'place_id'=>$pid];}}
   if(!$best||$bestScore<90)return ['ok'=>false,'reason'=>'No high-confidence Google location match was found.','score'=>$bestScore];$g=$best['g'];$lat=(float)($g['location']['latitude']??0);$lng=(float)($g['location']['longitude']??0);if(!bs1278_valid_geo($lat,$lng))return ['ok'=>false,'reason'=>'Matched Google coordinates are outside Shahkot safety bounds.'];return ['ok'=>true,'lat'=>$lat,'lng'=>$lng,'map_url'=>(string)($g['googleMapsUri']??''),'place_id'=>(string)$best['place_id'],'score'=>$bestScore];
 }catch(Throwable $e){return ['ok'=>false,'reason'=>$e->getMessage()];}
}
function bs1278_upsert_details(int $bid,array $b,float $lat,float $lng,string $mapUrl): void {if(!bs1278_table('business_details'))return;try{$q=db()->prepare('SELECT id FROM business_details WHERE business_id=? LIMIT 1');$q->execute([$bid]);$id=(int)($q->fetchColumn()?:0);$d=['business_id'=>$bid,'latitude'=>$lat?:null,'longitude'=>$lng?:null,'lat'=>$lat?:null,'lng'=>$lng?:null,'map_latitude'=>$lat?:null,'map_longitude'=>$lng?:null,'map_url'=>$mapUrl,'google_maps_url'=>$mapUrl,'address'=>(string)($b['address']??''),'website'=>(string)($b['website']??'')];if($id)bs1278_update('business_details',$id,$d);else bs1278_insert('business_details',$d);}catch(Throwable $e){}}
function bs1278_microsite(int $bid): void {if(!bs1278_table('business_microsites_v1130'))return;$tid=bs1278_tid();try{$q=db()->prepare('SELECT id FROM business_microsites_v1130 WHERE business_id=? AND tenant_id IN (?,0) ORDER BY tenant_id DESC LIMIT 1');$q->execute([$bid,$tid]);$id=(int)($q->fetchColumn()?:0);$d=['tenant_id'=>$tid,'business_id'=>$bid,'enabled'=>1,'theme_mode'=>'auto','theme_key'=>'auto','layout_variant'=>'auto','updated_at'=>bs1278_now()];if($id)bs1278_update('business_microsites_v1130',$id,$d);else{$d['created_at']=bs1278_now();bs1278_insert('business_microsites_v1130',$d);}}catch(Throwable $e){}}
function bs1278_health_save(int $bid,array $d): void {if(!bs1278_table('business_publish_health_v1278'))return;$tid=bs1278_tid();try{$q=db()->prepare('SELECT id FROM business_publish_health_v1278 WHERE tenant_id=? AND business_id=? LIMIT 1');$q->execute([$tid,$bid]);$id=(int)($q->fetchColumn()?:0);$d=array_merge(['tenant_id'=>$tid,'business_id'=>$bid,'updated_at'=>bs1278_now()],$d);if($id)bs1278_update('business_publish_health_v1278',$id,$d);else{$d['created_at']=bs1278_now();bs1278_insert('business_publish_health_v1278',$d);}}catch(Throwable $e){}}
function bs1278_health(int $bid): array {if($bid<1||!bs1278_table('business_publish_health_v1278'))return [];try{$q=db()->prepare('SELECT * FROM business_publish_health_v1278 WHERE business_id=? AND tenant_id IN (?,0) ORDER BY tenant_id DESC,id DESC LIMIT 1');$q->execute([$bid,bs1278_tid()]);return $q->fetch()?:[];}catch(Throwable $e){return [];}}
function bs1278_finalize_business(int $bid,string $source='manual',bool $tryGoogle=false): array {
 $b=bs1278_business($bid);if(!$b)throw new RuntimeException('Business record could not be loaded.');$tid=bs1278_tid();$city=(int)($b['city_id']??0);if($city<1)$city=bs1278_shahkot_city_id();$category=(int)($b['category_id']??0);$bcols=bs1278_cols('businesses');$public=!isset($bcols['status'])?true:bs1281_status_public($b['status']??null,$bcols['status']);
 $lat=0.0;$lng=0.0;foreach(['latitude','lat','map_latitude','location_lat'] as $k)if(isset($b[$k])&&(float)$b[$k]){$lat=(float)$b[$k];break;}foreach(['longitude','lng','map_longitude','location_lng'] as $k)if(isset($b[$k])&&(float)$b[$k]){$lng=(float)$b[$k];break;}$mapUrl='';foreach(['map_url','google_maps_url'] as $k)if(!empty($b[$k])){$mapUrl=(string)$b[$k];break;}
 if((!$lat||!$lng)&&bs1278_table('business_details')){try{$q=db()->prepare('SELECT * FROM business_details WHERE business_id=? LIMIT 1');$q->execute([$bid]);$det=$q->fetch()?:[];foreach(['latitude','lat','map_latitude'] as $k)if(!$lat&&!empty($det[$k]))$lat=(float)$det[$k];foreach(['longitude','lng','map_longitude'] as $k)if(!$lng&&!empty($det[$k]))$lng=(float)$det[$k];if($mapUrl===''&&!empty($det['map_url']))$mapUrl=(string)$det['map_url'];}catch(Throwable $e){}}
 if((!$lat||!$lng)&&$mapUrl!==''){[$pl,$pg]=bs1278_parse_map_url($mapUrl);if(bs1278_valid_geo($pl,$pg)){$lat=$pl;$lng=$pg;}}
 $geoSource=($lat&&$lng)?'manual_or_existing':'';$geoReason='';$googlePlace='';if((!bs1278_valid_geo($lat,$lng))&&$tryGoogle){$g=bs1278_google_geo($b);if(!empty($g['ok'])){$lat=(float)$g['lat'];$lng=(float)$g['lng'];$mapUrl=(string)($g['map_url']??$mapUrl);$geoSource='google_confident';$googlePlace=(string)($g['place_id']??'');}else{$geoReason=(string)($g['reason']??'Location could not be resolved.');}}
 $mapReady=bs1278_valid_geo($lat,$lng);$issues=[];if($tid>0&&empty($b['tenant_id']))$issues[]='tenant repaired';if($city<1)$issues[]='Shahkot city_id missing';if($category<1)$issues[]='category missing';if(!$mapReady)$issues[]='map coordinates missing';if(!$public)$issues[]='status is not public';
 $d=['tenant_id'=>$tid?:($b['tenant_id']??null),'city_id'=>$city?:null,'updated_at'=>bs1278_now()];if($mapReady)$d += ['latitude'=>$lat,'longitude'=>$lng,'lat'=>$lat,'lng'=>$lng,'map_latitude'=>$lat,'map_longitude'=>$lng,'location_lat'=>$lat,'location_lng'=>$lng,'map_url'=>$mapUrl,'google_maps_url'=>$mapUrl];if($public)$d += ['status'=>'active','listing_status'=>'active','publish_status'=>'published','moderation_status'=>'approved','approval_status'=>'approved','active'=>1,'is_active'=>1,'published'=>1,'is_published'=>1,'approved'=>1,'is_approved'=>1,'hidden'=>0,'is_hidden'=>0,'deleted'=>0,'is_deleted'=>0,'visibility'=>'public','published_at'=>bs1278_now(),'approved_at'=>bs1278_now()];bs1278_update('businesses',$bid,$d);$b=bs1278_business($bid);bs1278_upsert_details($bid,$b,$mapReady?$lat:0,$mapReady?$lng:0,$mapUrl);if($public)bs1278_microsite($bid);
 $ready=$public&&$city>0&&$category>0;$health=['source_mode'=>$source,'public_ready'=>$ready?1:0,'map_ready'=>$mapReady?1:0,'city_id'=>$city?:null,'latitude'=>$mapReady?$lat:null,'longitude'=>$mapReady?$lng:null,'geo_source'=>$geoSource?:null,'google_place_id'=>$googlePlace?:null,'issues_json'=>json_encode($issues,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'last_error'=>$geoReason?:null,'last_checked_at'=>bs1278_now()];bs1278_health_save($bid,$health);return array_merge(['business_id'=>$bid,'issues'=>$issues,'message'=>$ready?($mapReady?'Public + map ready':'Public ready; map needs coordinates'):'Needs attention'],$health);
}
function bs1278_repair_batch(int $limit=20,bool $tryGoogle=true): array {$limit=max(1,min(20,$limit));if(!bs1278_table('businesses'))return ['processed'=>0,'map_ready'=>0,'errors'=>[]];$cols=bs1278_cols('businesses');$w=[];$p=[];$tid=bs1278_tid();if($tid>0&&isset($cols['tenant_id'])){$w[]='(tenant_id=? OR tenant_id IS NULL OR tenant_id=0)';$p[]=$tid;}if(isset($cols['status']))$w[]="CAST(status AS CHAR) NOT IN ('deleted','rejected')";try{$q=db()->prepare('SELECT id FROM businesses'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY id DESC LIMIT '.$limit);$q->execute($p);$ids=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)?:[]);}catch(Throwable $e){return ['processed'=>0,'map_ready'=>0,'errors'=>[$e->getMessage()]];}$ok=0;$map=0;$errors=[];foreach($ids as $bid){try{$h=bs1278_finalize_business($bid,'repair',$tryGoogle);$ok++;if(!empty($h['map_ready']))$map++;}catch(Throwable $e){$errors[]='#'.$bid.' '.$e->getMessage();}}return ['processed'=>$ok,'map_ready'=>$map,'errors'=>$errors];}
function bs1281_recover_public_status(int $limit=100): array {$limit=max(1,min(500,$limit));if(!bs1278_table('businesses'))return ['processed'=>0,'errors'=>[]];$cols=bs1278_cols('businesses');if(!isset($cols['status']))return ['processed'=>0,'errors'=>[]];$tid=bs1278_tid();$numeric=in_array(strtolower((string)($cols['status']['DATA_TYPE']??'')),['tinyint','smallint','mediumint','int','bigint','bit'],true);$where=[];$p=[];if($tid>0&&isset($cols['tenant_id'])){$where[]='(b.tenant_id=? OR b.tenant_id=0 OR b.tenant_id IS NULL)';$p[]=$tid;}$where[]=$numeric?'CAST(b.status AS SIGNED)=0':"LOWER(CAST(b.status AS CHAR)) NOT IN ('active','published','approved','public','enabled','1')";$join='';if(bs1278_table('business_publish_health_v1278')){$join=' LEFT JOIN business_publish_health_v1278 h ON h.business_id=b.id AND h.tenant_id IN (?,0)';array_unshift($p,$tid);$where[]='COALESCE(h.public_ready,0)=1';}else{return ['processed'=>0,'errors'=>['Publish health table is unavailable; no automatic status recovery was attempted.']];}try{$q=db()->prepare('SELECT DISTINCT b.id FROM businesses b'.$join.' WHERE '.implode(' AND ',$where).' ORDER BY b.id DESC LIMIT '.$limit);$q->execute($p);$ids=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)?:[]);}catch(Throwable $e){return ['processed'=>0,'errors'=>[$e->getMessage()]];}$ok=0;$errors=[];foreach($ids as $bid){try{bs1278_update('businesses',$bid,['status'=>'active','active'=>1,'is_active'=>1,'published'=>1,'is_published'=>1,'approved'=>1,'is_approved'=>1,'hidden'=>0,'is_hidden'=>0,'visibility'=>'public','updated_at'=>bs1278_now()]);bs1278_finalize_business($bid,'visibility_recovery',false);$ok++;}catch(Throwable $e){$errors[]='#'.$bid.' '.$e->getMessage();}}return ['processed'=>$ok,'errors'=>$errors];}

}
