<?php
if(!isset($portalType)||!isset(city_portal_types()[$portalType])){http_response_code(404);exit('Not found');}
require_once __DIR__.'/ads_public.php';
$def=city_portal_type($portalType);
$slug=trim((string)($_GET['slug']??''));
$item=$slug?city_portal_item($slug):null;
$filterQ=trim((string)($_GET['q']??''));$filterCity=trim((string)($_GET['city']??''));$filterCategory=trim((string)($_GET['category']??''));
$items=$item?[]:city_portal_filtered_items($portalType,['q'=>$filterQ,'city'=>$filterCity,'category'=>$filterCategory],100);
$stats=city_portal_type_stats($portalType);$featured=city_portal_featured_item($portalType);$cityMix=city_portal_grouped_cities($portalType,6);$categoryMix=city_portal_grouped_categories($portalType,8);$filterCategories=city_portal_filter_categories($portalType);$cities=city_portal_cities();$related=$item?city_portal_related_items($portalType,(string)$item['slug'],3):[];
$typeUi=[
 'guide'=>['eyebrow'=>'CITY ESSENTIALS & PLACES','headline'=>'A complete guide to '.setting('default_city','Shahkot'),'description'=>'Discover hospitals, schools, public offices, markets, landmarks and practical city information in one organized local guide.','primary'=>'Explore city information','secondary'=>'Browse businesses','accent'=>'#0f766e','gradient'=>'linear-gradient(135deg,#062b24,#0f766e 55%,#0891b2)','ad'=>'city_guide'],
 'deal'=>['eyebrow'=>'LOCAL DEALS & PROMOTIONS','headline'=>'Save more with deals from local businesses','description'=>'Explore discounts, flash offers, launch promotions and sponsored local campaigns with clear pricing and expiry information.','primary'=>'View active deals','secondary'=>'Advertise an offer','accent'=>'#7c3aed','gradient'=>'linear-gradient(135deg,#26113b,#6d28d9 52%,#ec4899)','ad'=>'deals'],
 'event'=>['eyebrow'=>'CITY EVENTS & ANNOUNCEMENTS','headline'=>'See what is happening around '.setting('default_city','Shahkot'),'description'=>'Opening ceremonies, launches, community programs, local notices and events arranged in an easy city calendar.','primary'=>'Upcoming events','secondary'=>'Explore City Guide','accent'=>'#0284c7','gradient'=>'linear-gradient(135deg,#0c2b3c,#0369a1 50%,#0f766e)','ad'=>'events'],
 'job'=>['eyebrow'=>'LOCAL JOBS & HIRING','headline'=>'Find work opportunities close to home','description'=>'Discover local vacancies with employer, salary, employment type, requirements and application deadline details.','primary'=>'Browse jobs','secondary'=>'Browse businesses','accent'=>'#d97706','gradient'=>'linear-gradient(135deg,#301b08,#b45309 50%,#f59e0b)','ad'=>'jobs'],
 'property'=>['eyebrow'=>'PROPERTY & RENTALS','headline'=>'Find houses, shops, offices and plots in '.setting('default_city','Shahkot'),'description'=>'Browse property for rent or sale with pricing, type, area, location and direct owner/business contact details.','primary'=>'Browse property','secondary'=>'Explore city businesses','accent'=>'#0369a1','gradient'=>'linear-gradient(135deg,#082f49,#0369a1 50%,#0f766e)','ad'=>'property'],
];
$ui=$typeUi[$portalType]??$typeUi['guide'];$allTypes=city_portal_types();$latestAt=!empty($stats['latest_at'])?date('d M Y',strtotime((string)$stats['latest_at'])):'New';$sponsor=feature_enabled('advertisements_enabled',true)?active_ad_for_placement($ui['ad']):null;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($item?$item['title']:$def['label'].' — '.setting('site_name','ShahkotPK'))?></title><meta name="description" content="<?=e($item?($item['summary']?:mb_strimwidth((string)$item['description'],0,155,'…')):$ui['description'])?>"><link rel="stylesheet" href="/assets/themes/landing/base.css?v=240"><link rel="stylesheet" href="/assets/city-verticals-3.0.1.css?v=301"></head>
<body class="cityv-page cityv-<?=e($portalType)?>">
<?php require_once __DIR__.'/views/header.php'; ?>
<?php if($item):$m=$item['meta'];?>
<section class="cityv-detail-hero" style="--cityv-gradient:<?=$ui['gradient']?>;<?php if($item['image_url']):?>--cityv-image:url('<?=e($item['image_url'])?>');<?php endif;?>"><div class="cityv-shell"><div class="cityv-breadcrumb"><a href="/">Home</a><span>›</span><a href="<?=e($def['url'])?>"><?=e($def['label'])?></a><span>›</span><b><?=e($item['title'])?></b></div><div class="cityv-detail-layout"><article><span class="cityv-kicker"><?=e($ui['eyebrow'])?></span><h1><?=e($item['title'])?></h1><p><?=e($item['summary']?:mb_strimwidth((string)$item['description'],0,200,'…'))?></p><div class="cityv-pills"><span><?=e($item['category']?:$def['label'])?></span><span><?=e($item['city_name'])?></span><?php if($item['featured']):?><span>Featured</span><?php endif;?></div></article><aside class="cityv-glass-card"><h3>Quick Information</h3><?php if($item['business_name']):?><div><span>Business</span><b><?=e($item['business_name'])?></b></div><?php endif;?><?php if($item['address']):?><div><span>Location</span><b><?=e($item['address'])?></b></div><?php endif;?><?php if($item['starts_at']):?><div><span><?=$portalType==='job'?'Posted':'Starts'?></span><b><?=e(date('d M Y · h:i A',strtotime((string)$item['starts_at'])))?></b></div><?php endif;?><?php if($item['ends_at']):?><div><span><?=$portalType==='job'?'Deadline':'Ends'?></span><b><?=e(date('d M Y · h:i A',strtotime((string)$item['ends_at'])))?></b></div><?php endif;?><?php if($portalType==='job'&&!empty($m['salary_text'])):?><div><span>Salary</span><b><?=e($m['salary_text'])?></b></div><?php endif;?><?php if(in_array($portalType,['deal','property'],true)&&(float)$item['price']>0):?><div><span><?=$portalType==='deal'?'Original Price':'Price'?></span><b>Rs <?=e(number_format((float)$item['price']))?></b></div><?php endif;?></aside></div></div></section>
<section class="cityv-section"><div class="cityv-shell cityv-detail-content"><article class="cityv-card cityv-article"><span class="cityv-section-kicker">DETAILS</span><h2>About this <?=e($def['label'])?></h2><div class="cityv-rich"><?=nl2br(e((string)$item['description']))?></div><?php if($portalType==='deal'&&!empty($m['terms'])):?><div class="cityv-note"><b>Offer Terms</b><p><?=e($m['terms'])?></p></div><?php endif;?><?php if($portalType==='job'&&!empty($m['requirements'])):?><div class="cityv-note"><b>Requirements</b><p><?=nl2br(e($m['requirements']))?></p></div><?php endif;?></article><aside class="cityv-card cityv-contact-card"><span class="cityv-section-kicker">CONTACT & ACTIONS</span><h3>Connect directly</h3><div class="cityv-info-list"><?php if($item['phone']):?><div><small>Phone</small><b><?=e($item['phone'])?></b></div><?php endif;?><?php if($item['whatsapp']):?><div><small>WhatsApp</small><b><?=e($item['whatsapp'])?></b></div><?php endif;?><?php if(!empty($m['venue'])):?><div><small>Venue</small><b><?=e($m['venue'])?></b></div><?php endif;?><?php if(!empty($m['property_type'])):?><div><small>Property</small><b><?=e($m['property_type'])?><?=!empty($m['area_text'])?' · '.e($m['area_text']):''?></b></div><?php endif;?></div><div class="cityv-actions"><?php if($item['phone']):?><a class="primary" href="tel:<?=e($item['phone'])?>">Call Now</a><?php endif;?><?php if($item['whatsapp']):?><a target="_blank" href="https://wa.me/<?=e(preg_replace('/\D/','',(string)$item['whatsapp']))?>">WhatsApp</a><?php endif;?><?php if($item['website_url']):?><a target="_blank" href="<?=e($item['website_url'])?>"><?=$portalType==='job'?'Apply / Open':'Website'?></a><?php endif;?><?php if($item['map_url']):?><a target="_blank" href="<?=e($item['map_url'])?>">Directions</a><?php endif;?></div></aside></div></section>
<?php if(google_maps_ready()&&setting_bool('google_maps_vertical_pages_enabled',true))google_maps_public_module($item['title'].' Location',[$portalType],'View this item and other '.strtolower($def['label']).' locations on the map.');?>
<?php if($related):?><section class="cityv-section cityv-muted"><div class="cityv-shell"><div class="cityv-title-row"><div><span>MORE TO EXPLORE</span><h2>Related <?=e($def['label'])?></h2></div><a href="<?=e($def['url'])?>">View all →</a></div><div class="cityv-grid"><?php foreach($related as $r):?><article class="cityv-listing-card"><div class="cityv-card-media"<?php if($r['image_url']):?> style="background-image:url('<?=e($r['image_url'])?>')"<?php endif;?>><span><?=e($r['category']?:$def['label'])?></span></div><div class="cityv-card-body"><small><?=e($r['business_name']?:$r['city_name'])?></small><h3><?=e($r['title'])?></h3><p><?=e($r['summary']?:mb_strimwidth((string)$r['description'],0,120,'…'))?></p><a href="<?=e($def['url'])?>?slug=<?=urlencode((string)$r['slug'])?>">View details →</a></div></article><?php endforeach;?></div></div></section><?php endif;?>
<?php else:?>
<section class="cityv-hero" style="--cityv-gradient:<?=$ui['gradient']?>"><div class="cityv-shell cityv-hero-grid"><article><span class="cityv-kicker"><?=e($ui['eyebrow'])?></span><h1><?=e($ui['headline'])?></h1><p><?=e($ui['description'])?></p><div class="cityv-hero-actions"><a class="primary" href="#browse"><?=e($ui['primary'])?></a><a href="/businesses.php"><?=e($ui['secondary'])?></a></div><div class="cityv-pills"><?php foreach($categoryMix as $c):?><span><?=e($c['category_name'])?> <em><?=e($c['total'])?></em></span><?php endforeach;?></div></article><aside class="cityv-glass-card cityv-dashboard-card"><span class="cityv-dashboard-label">LIVE <?=e(strtoupper($def['label']))?> DASHBOARD</span><div class="cityv-stat-grid"><div><strong><?=e((string)($stats['published_count']??0))?></strong><span>Published</span></div><div><strong><?=e((string)($stats['featured_count']??0))?></strong><span>Featured</span></div><div><strong><?=e((string)($stats['city_count']??0))?></strong><span>Cities</span></div><div><strong><?=e($latestAt)?></strong><span>Latest Update</span></div></div><div class="cityv-city-list"><?php foreach($cityMix as $c):?><div><span><?=e($c['city_name'])?></span><b><?=e($c['total'])?> items</b></div><?php endforeach;?><?php if(!$cityMix):?><div><span><?=e(setting('default_city','Shahkot'))?></span><b>Ready for content</b></div><?php endif;?></div></aside></div></section>
<?php if($sponsor):?><section class="cityv-sponsor"><div class="cityv-shell"><a href="/ad-click.php?id=<?=e($sponsor['id'])?>"><div class="cityv-sponsor-img"<?php if($sponsor['image_url']):?> style="background-image:url('<?=e($sponsor['image_url'])?>')"<?php endif;?>></div><div><span>SPONSORED</span><h3><?=e($sponsor['title'])?></h3><p><?=e($sponsor['description']?:($sponsor['business_name']?:'Local promotion'))?></p></div><b>View Promotion →</b></a></div></section><?php endif;?>
<section id="browse" class="cityv-section cityv-filter-section"><div class="cityv-shell"><div class="cityv-title-row"><div><span>DISCOVER <?=e(strtoupper($def['label']))?></span><h2>Explore local <?=e(strtolower($def['label']))?></h2><p>Use filters or browse featured and recent content from the city.</p></div><a href="/businesses.php">Business Directory →</a></div><form class="cityv-filter" method="get"><div><label>Search</label><input name="q" value="<?=e($filterQ)?>" placeholder="Search title, business or keyword..."></div><div><label>City</label><select name="city"><option value="">All cities</option><?php foreach($cities as $c):?><option value="<?=e($c['slug'])?>" <?=$filterCity===$c['slug']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div><label>Category</label><select name="category"><option value="">All categories</option><?php foreach($filterCategories as $c):?><option value="<?=e($c['category'])?>" <?=$filterCategory===$c['category']?'selected':''?>><?=e($c['category'])?> (<?=e($c['total'])?>)</option><?php endforeach;?></select></div><button>Apply Filters</button><?php if($filterQ!==''||$filterCity!==''||$filterCategory!==''):?><a href="<?=e($def['url'])?>">Clear</a><?php endif;?></form>
<?php if($featured && !$filterQ && !$filterCity && !$filterCategory):?><div class="cityv-featured"><div class="cityv-featured-copy"><span>FEATURED <?=e(strtoupper($def['label']))?></span><h2><?=e($featured['title'])?></h2><p><?=e($featured['summary']?:mb_strimwidth((string)$featured['description'],0,175,'…'))?></p><a class="primary" href="<?=e($def['url'])?>?slug=<?=urlencode((string)$featured['slug'])?>">Explore Featured</a></div><div class="cityv-featured-media"<?php if($featured['image_url']):?> style="background-image:url('<?=e($featured['image_url'])?>')"<?php endif;?>></div></div><?php endif;?>
<div class="cityv-grid cityv-grid-<?=e($portalType)?>"><?php foreach($items as $r):$m=$r['meta'];?><article class="cityv-listing-card"><div class="cityv-card-media"<?php if($r['image_url']):?> style="background-image:url('<?=e($r['image_url'])?>')"<?php endif;?>><span><?=e($r['category']?:$def['label'])?></span><?php if($r['featured']):?><em>Featured</em><?php endif;?></div><div class="cityv-card-body"><div class="cityv-card-meta"><small><?=e($r['business_name']?:$r['city_name'])?></small><?php if($r['starts_at']):?><b><?=e(date('d M',strtotime((string)$r['starts_at'])))?></b><?php endif;?></div><h3><?=e($r['title'])?></h3><p><?=e($r['summary']?:mb_strimwidth((string)$r['description'],0,120,'…'))?></p><?php if($portalType==='deal'&&(float)$r['secondary_price']>0):?><div class="cityv-price"><strong>Rs <?=e(number_format((float)$r['secondary_price']))?></strong><del>Rs <?=e(number_format((float)$r['price']))?></del></div><?php elseif($portalType==='job'&&!empty($m['salary_text'])):?><div class="cityv-price"><strong><?=e($m['salary_text'])?></strong><span><?=e($m['employment_type']??'Local job')?></span></div><?php elseif($portalType==='property'&&(float)$r['price']>0):?><div class="cityv-price"><strong>Rs <?=e(number_format((float)$r['price']))?></strong><span><?=e(($m['property_type']??'Property').' · '.($m['area_text']??$r['city_name']))?></span></div><?php endif;?><a href="<?=e($def['url'])?>?slug=<?=urlencode((string)$r['slug'])?>">View Details →</a></div></article><?php endforeach;?></div>
<?php if(!$items):?><div class="cityv-empty"><div>⌖</div><h3>No matching <?=e(strtolower($def['label']))?> are live yet</h3><p>Fresh local content is being prepared. You can explore the business directory, another city section, or check back again soon.</p><div><a class="primary" href="/businesses.php">Explore Businesses</a><a href="/">Back to Home</a></div></div><?php endif;?></div></section>
<section class="cityv-section cityv-muted"><div class="cityv-shell"><div class="cityv-title-row"><div><span>MORE FROM SHAHKOTPK</span><h2>Your city in one portal</h2></div></div><div class="cityv-link-grid"><?php foreach($allTypes as $tk=>$tm):if($tk===$portalType)continue;?><a href="<?=e($tm['url'])?>"><i><?=e($tm['icon'])?></i><span><b><?=e($tm['label'])?></b><small>Open local <?=e(strtolower($tm['label']))?></small></span><em>→</em></a><?php endforeach;?><a href="/businesses.php"><i>▦</i><span><b>Businesses</b><small>Local shops & services</small></span><em>→</em></a></div></div></section>
<?php endif;?>
<?php require_once __DIR__.'/views/footer.php'; ?>
<script>(function(){const b=document.querySelector('[data-cityv-menu]'),n=document.querySelector('[data-cityv-nav]');b?.addEventListener('click',()=>n?.classList.toggle('open'));})();</script><?php if(google_maps_ready()&&setting_bool('google_maps_vertical_pages_enabled',true))render_google_maps_assets();?>
</body></html>