<?php
declare(strict_types=1);

function growth_enabled(string $key='growth_suite_enabled',bool $default=true): bool {return setting_bool($key,$default);}
function growth_rows(string $sql,array $params=[]): array {try{$q=db()->prepare($sql);$q->execute($params);return $q->fetchAll();}catch(Throwable $e){return [];}}
function growth_row(string $sql,array $params=[]): ?array {try{$q=db()->prepare($sql);$q->execute($params);return $q->fetch()?:null;}catch(Throwable $e){return null;}}
function growth_scalar(string $sql,array $params=[]): float {try{$q=db()->prepare($sql);$q->execute($params);return (float)($q->fetchColumn()?:0);}catch(Throwable $e){return 0;}}
function growth_owned_businesses(int $userId): array {return growth_rows("SELECT id,name,slug,verification_status FROM businesses WHERE owner_id=? AND status=1 ORDER BY name",[$userId]);}
function growth_business_owner(int $businessId): int {return (int)growth_scalar("SELECT owner_id FROM businesses WHERE id=?",[$businessId]);}
function growth_business_owned_by(int $businessId,int $userId): bool {return growth_business_owner($businessId)===$userId;}
function growth_clean_phone(string $v): string {return preg_replace('/[^0-9+]/','',$v)?:'';}
function growth_safe_slug(string $title): string {$base=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','-',$title),'-'))?:'listing';$slug=$base;$n=2;while(growth_scalar("SELECT COUNT(*) FROM classifieds WHERE slug=?",[$slug])>0)$slug=$base.'-'.$n++;return $slug;}
function growth_session_hash(): string {if(session_status()!==PHP_SESSION_ACTIVE)@session_start();return hash('sha256',session_id().'|'.($_SERVER['HTTP_USER_AGENT']??''));}
function growth_rate_limit(string $key,int $seconds=20): void {if(session_status()!==PHP_SESSION_ACTIVE)@session_start();$k='_growth_rate_'.$key;$last=(int)($_SESSION[$k]??0);if($last&&time()-$last<$seconds)throw new RuntimeException('Please wait a few seconds before submitting again.');$_SESSION[$k]=time();}

function growth_review_stats(int $businessId): array {
    $r=growth_row("SELECT COUNT(*) total,COALESCE(AVG(rating),0) average_rating,SUM(rating=5) five_star FROM business_reviews WHERE business_id=? AND status='published'",[$businessId]);
    return $r?:['total'=>0,'average_rating'=>0,'five_star'=>0];
}
function growth_reviews(int $businessId,int $limit=20): array {return growth_rows("SELECT r.*,u.name user_name FROM business_reviews r JOIN users u ON u.id=r.user_id WHERE r.business_id=? AND r.status='published' ORDER BY r.id DESC LIMIT ".max(1,min(100,$limit)),[$businessId]);}
function growth_top_rated(int $limit=6): array {return growth_rows("SELECT b.id,b.name,b.slug,b.image,b.address,c.name city_name,cat.name category_name,COUNT(r.id) review_count,COALESCE(AVG(r.rating),0) rating FROM businesses b JOIN cities c ON c.id=b.city_id JOIN categories cat ON cat.id=b.category_id JOIN business_reviews r ON r.business_id=b.id AND r.status='published' WHERE b.status=1 GROUP BY b.id ORDER BY rating DESC,review_count DESC LIMIT ".max(1,min(24,$limit)));}
function growth_submit_review(int $businessId,int $userId,int $rating,string $title,string $body): int {
    if(!growth_enabled('reviews_enabled',true))throw new RuntimeException('Reviews are disabled.');
    $rating=max(1,min(5,$rating));$u=growth_row("SELECT role FROM users WHERE id=?",[$userId]);if(!$u||!in_array($u['role'],['user','customer'],true))throw new RuntimeException('Only customer/user accounts can submit reviews.');
    if(growth_business_owner($businessId)===$userId)throw new RuntimeException('Business owners cannot review their own business.');
    growth_rate_limit('review_'.$businessId,20);
    $existing=(int)growth_scalar("SELECT id FROM business_reviews WHERE business_id=? AND user_id=?",[$businessId,$userId]);
    $status=setting_bool('reviews_require_moderation',true)?'pending':'published';
    db()->prepare("INSERT INTO business_reviews(business_id,user_id,rating,title,body,status) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),title=VALUES(title),body=VALUES(body),status=VALUES(status),updated_at=NOW()")->execute([$businessId,$userId,$rating,trim($title)?:null,trim($body)?:null,$status]);
    $id=$existing?:((int)db()->lastInsertId());
    if(!$existing&&$status==='published'&&growth_enabled('loyalty_enabled',true))growth_wallet_post_once($userId,setting_int('loyalty_points_per_review',20),0,'review','business_review',$id,'Reward for published business review');
    return $id;
}
function growth_reply_review(int $reviewId,int $ownerId,string $reply): void {
    $r=growth_row("SELECT r.id,b.owner_id FROM business_reviews r JOIN businesses b ON b.id=r.business_id WHERE r.id=?",[$reviewId]);if(!$r||(int)$r['owner_id']!==$ownerId)throw new RuntimeException('Review not found.');db()->prepare("UPDATE business_reviews SET owner_reply=?,replied_at=NOW() WHERE id=?")->execute([trim($reply),$reviewId]);
}

function growth_verification_status(int $businessId): array {return growth_row("SELECT * FROM business_verifications WHERE business_id=? ORDER BY id DESC LIMIT 1",[$businessId])?:['status'=>'not_submitted'];}
function growth_request_verification(int $businessId,int $userId,string $type,string $notes='',?string $doc=null): int {
    if(!growth_enabled('verification_enabled',true))throw new RuntimeException('Verification is disabled.');if(!growth_business_owned_by($businessId,$userId))throw new RuntimeException('You can only verify your own business.');
    if(!in_array($type,['identity','business','physical','phone'],true))$type='business';$fee=max(0,(float)setting('verification_fee','0'));
    db()->prepare("INSERT INTO business_verifications(business_id,submitted_by,verification_type,document_path,notes,status,fee_amount) VALUES(?,?,?,?,?,'pending',?)")->execute([$businessId,$userId,$type,$doc,$notes?:null,$fee]);return (int)db()->lastInsertId();
}

function growth_create_booking(int $businessId,?int $userId,string $service,string $date,string $time,string $name,string $phone,string $email='',string $notes=''): int {
    if(!growth_enabled('bookings_enabled',true))throw new RuntimeException('Bookings are disabled.');if((int)growth_scalar("SELECT COUNT(*) FROM businesses WHERE id=? AND status=1",[$businessId])<1)throw new RuntimeException('Business is not available.');growth_rate_limit('booking_'.$businessId,15);if($service===''||$name===''||$phone==='')throw new RuntimeException('Service, name and phone are required.');if(strtotime($date.' '.$time)<time()-3600)throw new RuntimeException('Booking date/time must be in the future.');
    db()->prepare("INSERT INTO business_bookings(business_id,user_id,service_name,booking_date,booking_time,customer_name,customer_phone,customer_email,notes) VALUES(?,?,?,?,?,?,?,?,?)")->execute([$businessId,$userId,$service,$date,$time,$name,growth_clean_phone($phone),$email?:null,$notes?:null]);$id=(int)db()->lastInsertId();
    growth_track('booking_created','booking',$id,$businessId,['service'=>$service]);growth_whatsapp_queue('booking_created',$phone,['business'=>(string)(growth_row("SELECT name FROM businesses WHERE id=?",[$businessId])['name']??'Business'),'service'=>$service,'date'=>$date,'time'=>$time]);return $id;
}
function growth_create_lead(int $businessId,?int $userId,string $type,string $name,string $phone,string $email,string $message,string $source='business_profile'): int {
    if(!growth_enabled('leads_enabled',true))throw new RuntimeException('Business inquiries are disabled.');if((int)growth_scalar("SELECT COUNT(*) FROM businesses WHERE id=? AND status=1",[$businessId])<1)throw new RuntimeException('Business is not available.');growth_rate_limit('lead_'.$businessId,12);if($name===''||($phone===''&&$email===''))throw new RuntimeException('Name and phone or email are required.');if(!in_array($type,['inquiry','quote','call','whatsapp','booking','service'],true))$type='inquiry';
    db()->prepare("INSERT INTO business_leads(business_id,user_id,lead_type,customer_name,customer_phone,customer_email,message,source) VALUES(?,?,?,?,?,?,?,?)")->execute([$businessId,$userId,$type,$name,growth_clean_phone($phone)?:null,$email?:null,$message?:null,$source]);$id=(int)db()->lastInsertId();growth_track('lead_created','lead',$id,$businessId,['lead_type'=>$type]);return $id;
}

function growth_wallet(int $userId): array {db()->prepare("INSERT IGNORE INTO loyalty_wallets(user_id) VALUES(?)")->execute([$userId]);return growth_row("SELECT * FROM loyalty_wallets WHERE user_id=?",[$userId])?:['user_id'=>$userId,'points'=>0,'credit_balance'=>0];}
function growth_wallet_post(int $userId,int $points,float $credit,string $type,string $refType='',?int $refId=null,string $description=''): void {
    if(!$userId)return;db()->beginTransaction();try{db()->prepare("INSERT INTO loyalty_wallets(user_id,points,credit_balance) VALUES(?,?,?) ON DUPLICATE KEY UPDATE points=points+VALUES(points),credit_balance=credit_balance+VALUES(credit_balance)")->execute([$userId,$points,$credit]);db()->prepare("INSERT INTO loyalty_transactions(user_id,points_delta,credit_delta,transaction_type,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)")->execute([$userId,$points,$credit,$type,$refType?:null,$refId,$description?:null]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}
}

function growth_wallet_post_once(int $userId,int $points,float $credit,string $type,string $refType='',?int $refId=null,string $description=''): bool {
    if(!$userId)return false;
    if($refType!==''&&$refId!==null){
        $exists=(int)growth_scalar("SELECT COUNT(*) FROM loyalty_transactions WHERE user_id=? AND transaction_type=? AND reference_type=? AND reference_id=?",[$userId,$type,$refType,$refId]);
        if($exists>0)return false;
    }
    growth_wallet_post($userId,$points,$credit,$type,$refType,$refId,$description);return true;
}
function growth_referral_code(int $userId): string {return 'SHP-'.strtoupper(base_convert((string)$userId,10,36)).'-'.strtoupper(substr(hash('sha256','ref|'.$userId),0,5));}
function growth_referral_user_id(string $code): int {if(!preg_match('/^SHP-([0-9A-Z]+)-[0-9A-F]{5}$/i',trim($code),$m))return 0;return (int)base_convert(strtoupper($m[1]),36,10);}
function growth_register_referral_click(string $code): void {$uid=growth_referral_user_id($code);if(!$uid)return;if(session_status()!==PHP_SESSION_ACTIVE)@session_start();$_SESSION['referral_code']=$code;setcookie('shahkot_referral',$code,['expires'=>time()+2592000,'path'=>'/','secure'=>!empty($_SERVER['HTTPS']),'httponly'=>true,'samesite'=>'Lax']);}
function growth_attach_referral(int $newUserId): void {
    if(!growth_enabled('referrals_enabled',true))return;if(session_status()!==PHP_SESSION_ACTIVE)@session_start();$code=(string)($_SESSION['referral_code']??$_COOKIE['shahkot_referral']??'');$referrer=growth_referral_user_id($code);if(!$referrer||$referrer===$newUserId)return;
    try{$q=db()->prepare("INSERT IGNORE INTO referrals(referrer_user_id,referred_user_id,referral_code,status,reward_points,qualified_at,rewarded_at) VALUES(?,?,?,'rewarded',?,NOW(),NOW())");$q->execute([$referrer,$newUserId,$code,setting_int('referral_reward_points',100)]);if($q->rowCount()>0)growth_wallet_post_once($referrer,setting_int('referral_reward_points',100),0,'referral_reward','user',$newUserId,'Referral reward');}catch(Throwable $e){}
}

function growth_track(string $event,string $entityType='',?int $entityId=null,?int $businessId=null,array $meta=[]): void {
    if(!growth_enabled('analytics_enabled',true))return;try{$u=current_user();db()->prepare("INSERT INTO analytics_events(user_id,session_hash,event_type,entity_type,entity_id,business_id,meta_json) VALUES(?,?,?,?,?,?,?)")->execute([$u['id']??null,growth_session_hash(),$event,$entityType?:null,$entityId,$businessId,$meta?json_encode($meta,JSON_UNESCAPED_SLASHES):null]);}catch(Throwable $e){}
}
function growth_coupon(string $code): ?array {return growth_row("SELECT c.*,b.name business_name,b.slug business_slug,ci.name city_name FROM business_coupons c JOIN businesses b ON b.id=c.business_id JOIN cities ci ON ci.id=b.city_id WHERE c.code=? AND c.status='active' AND (c.starts_at IS NULL OR c.starts_at<=NOW()) AND (c.ends_at IS NULL OR c.ends_at>=NOW()) LIMIT 1",[strtoupper(trim($code))]);}

function growth_analytics_summary(?int $businessId=null,int $days=30): array {
    $days=max(1,min(365,$days));$where="created_at>=DATE_SUB(NOW(),INTERVAL {$days} DAY)";$params=[];if($businessId){$where.=' AND business_id=?';$params[]=$businessId;}
    $rows=growth_rows("SELECT event_type,COUNT(*) total FROM analytics_events WHERE {$where} GROUP BY event_type ORDER BY total DESC",$params);$out=[];foreach($rows as $r)$out[$r['event_type']]=(int)$r['total'];return $out;
}

function growth_emergency_services(?int $cityId=null,int $limit=50): array {$where='status=1';$p=[];if($cityId){$where.=' AND city_id=?';$p[]=$cityId;}return growth_rows("SELECT e.*,c.name city_name FROM emergency_services e JOIN cities c ON c.id=e.city_id WHERE {$where} ORDER BY priority ASC,is_24_7 DESC,name LIMIT ".max(1,min(100,$limit)),$p);}
function growth_restaurants(int $limit=18): array {$boost=(function_exists('v41_table_exists')&&v41_table_exists('listing_boosts'))?"(SELECT COUNT(*) FROM listing_boosts lb WHERE lb.entity_type='business' AND lb.entity_id=b.id AND lb.status='active' AND lb.starts_at<=NOW() AND lb.ends_at>=NOW()) DESC,":'';return growth_rows("SELECT b.*,c.name city_name,cat.name category_name,COALESCE(rs.avg_rating,0) rating,COALESCE(rs.review_count,0) review_count FROM businesses b JOIN cities c ON c.id=b.city_id JOIN categories cat ON cat.id=b.category_id LEFT JOIN (SELECT business_id,AVG(rating) avg_rating,COUNT(*) review_count FROM business_reviews WHERE status='published' GROUP BY business_id) rs ON rs.business_id=b.id WHERE b.status=1 AND (LOWER(cat.name) LIKE '%restaurant%' OR LOWER(cat.name) LIKE '%food%' OR LOWER(cat.slug) LIKE '%restaurant%' OR EXISTS(SELECT 1 FROM restaurant_menus m WHERE m.business_id=b.id AND m.status=1)) ORDER BY {$boost}b.is_featured DESC,rating DESC,b.id DESC LIMIT ".max(1,min(50,$limit)));}
function growth_restaurant_menu(int $businessId): array {return growth_rows("SELECT mi.*,m.title menu_title FROM restaurant_menu_items mi JOIN restaurant_menus m ON m.id=mi.menu_id WHERE m.business_id=? AND m.status=1 AND mi.available=1 ORDER BY m.sort_order,mi.category_name,mi.sort_order,mi.name",[$businessId]);}
function growth_service_requests(?int $userId=null,int $limit=50): array {$where="sr.status IN ('open','assigned')";$p=[];if($userId){$where.=' AND sr.user_id=?';$p[]=$userId;}return growth_rows("SELECT sr.*,c.name city_name,u.name customer_name,(SELECT COUNT(*) FROM service_quotes sq WHERE sq.request_id=sr.id) quote_count FROM service_requests sr JOIN cities c ON c.id=sr.city_id JOIN users u ON u.id=sr.user_id WHERE {$where} ORDER BY sr.id DESC LIMIT ".max(1,min(100,$limit)),$p);}
function growth_classifieds(string $status='published',int $limit=30): array {$where=$status!==''?'cl.status=?':'1=1';$p=$status!==''?[$status]:[];$boost=(function_exists('v41_table_exists')&&v41_table_exists('listing_boosts'))?"(SELECT COUNT(*) FROM listing_boosts lb WHERE lb.entity_type='classified' AND lb.entity_id=cl.id AND lb.status='active' AND lb.starts_at<=NOW() AND lb.ends_at>=NOW()) DESC,":'';return growth_rows("SELECT cl.*,c.name city_name,u.name seller_name,b.name business_name FROM classifieds cl JOIN cities c ON c.id=cl.city_id JOIN users u ON u.id=cl.user_id LEFT JOIN businesses b ON b.id=cl.business_id WHERE {$where} AND (cl.expires_at IS NULL OR cl.expires_at>=NOW()) ORDER BY {$boost}cl.featured DESC,cl.id DESC LIMIT ".max(1,min(100,$limit)),$p);}

function growth_user_active_plan(int $userId): ?array {return growth_row("SELECT sp.*,s.id subscription_id,s.end_date FROM subscriptions s JOIN businesses b ON b.id=s.business_id JOIN subscription_plans sp ON sp.id=s.plan_id WHERE b.owner_id=? AND s.status='active' AND s.end_date>=CURDATE() ORDER BY sp.price DESC,s.end_date DESC LIMIT 1",[$userId]);}
function growth_plan_entitlement(int $planId,string $key,$default=null) {$r=growth_row("SELECT entitlement_value FROM plan_entitlements WHERE plan_id=? AND entitlement_key=?",[$planId,$key]);return $r?$r['entitlement_value']:$default;}
function growth_entitled(int $userId,string $key,$default=true): bool {$p=growth_user_active_plan($userId);if(!$p)return (bool)$default;$v=growth_plan_entitlement((int)$p['id'],$key,$default?'1':'0');return !in_array(strtolower((string)$v),['0','false','off','no','disabled'],true);}
function growth_entitlement_limit(int $userId,string $key,int $default=999999): int {$p=growth_user_active_plan($userId);if(!$p)return $default;$v=growth_plan_entitlement((int)$p['id'],$key,(string)$default);return max(0,(int)$v);}

function growth_seller_staff_permissions(int $staffUserId): array {$rows=growth_rows("SELECT owner_user_id,permissions_json FROM seller_staff WHERE staff_user_id=? AND status=1",[$staffUserId]);$out=[];foreach($rows as $r){$p=json_decode((string)$r['permissions_json'],true);$out[(int)$r['owner_user_id']]=is_array($p)?$p:[];}return $out;}
function growth_seller_context(string $permission=''): array {
    $u=require_login();$uid=(int)$u['id'];if(($u['role']??'')==='shopkeeper')return ['user'=>$u,'owner_id'=>$uid,'is_staff'=>false,'permissions'=>['*']];
    $staff=growth_seller_staff_permissions($uid);foreach($staff as $owner=>$perms)if($permission===''||in_array('*',$perms,true)||in_array($permission,$perms,true))return ['user'=>$u,'owner_id'=>$owner,'is_staff'=>true,'permissions'=>$perms];
    http_response_code(403);exit('Seller Center access is not assigned to this account.');
}
function growth_seller_can(array $ctx,string $permission): bool {return !$ctx['is_staff']||in_array('*',$ctx['permissions'],true)||in_array($permission,$ctx['permissions'],true);}

function growth_seo_meta(string $type,int $id,array $fallback=[]): array {$r=growth_row("SELECT * FROM seo_meta WHERE entity_type=? AND entity_id=?",[$type,$id])?:[];return array_merge($fallback,$r);}
function growth_render_seo(string $type,int $id,array $fallback=[]): string {
    if(!growth_enabled('seo_automation_enabled',true))return '';$m=growth_seo_meta($type,$id,$fallback);$title=trim((string)($m['meta_title']??$fallback['title']??''));$desc=trim((string)($m['meta_description']??$fallback['description']??''));$canonical=trim((string)($m['canonical_url']??''));$og=trim((string)($m['og_image']??$fallback['image']??''));$schema=trim((string)($m['schema_json']??''));$html='';if($title)$html.='<title>'.e($title).'</title>';if($desc)$html.='<meta name="description" content="'.e($desc).'">';if($canonical)$html.='<link rel="canonical" href="'.e($canonical).'">';if($title)$html.='<meta property="og:title" content="'.e($title).'">';if($desc)$html.='<meta property="og:description" content="'.e($desc).'">';if($og)$html.='<meta property="og:image" content="'.e($og).'">';if($schema)$html.='<script type="application/ld+json">'.str_replace('</','<\/',$schema).'</script>';return $html;
}
function growth_moderation_report(?int $userId,string $type,int $id,string $reason,string $details=''): int {if(!growth_enabled('moderation_center_enabled',true))return 0;growth_rate_limit('report_'.$type.'_'.$id,20);db()->prepare("INSERT INTO moderation_reports(reporter_user_id,entity_type,entity_id,reason,details) VALUES(?,?,?,?,?)")->execute([$userId,$type,$id,$reason,$details?:null]);return (int)db()->lastInsertId();}

function growth_whatsapp_template(string $key): ?array {return growth_row("SELECT * FROM whatsapp_templates WHERE template_key=? AND status=1",[$key]);}
function growth_whatsapp_queue(string $templateKey,string $recipient,array $vars=[]): int {
    if(!growth_enabled('whatsapp_automation_enabled',false))return 0;$tpl=growth_whatsapp_template($templateKey);if(!$tpl)return 0;$message=(string)$tpl['message_template'];foreach($vars as $k=>$v)$message=str_replace('{{'.$k.'}}',(string)$v,$message);$recipient=growth_clean_phone($recipient);if($recipient==='')return 0;db()->prepare("INSERT INTO whatsapp_queue(template_key,recipient,message_text,status) VALUES(?,?,?,'queued')")->execute([$templateKey,$recipient,$message]);return (int)db()->lastInsertId();
}
function growth_whatsapp_dispatch(int $queueId): bool {
    $row=growth_row("SELECT * FROM whatsapp_queue WHERE id=? AND status='queued'",[$queueId]);if(!$row)return false;if(!function_exists('curl_init'))throw new RuntimeException('PHP cURL extension is required for WhatsApp provider dispatch.');$endpoint=trim((string)setting('whatsapp_api_endpoint',''));$token=trim((string)setting('whatsapp_access_token',''));if($endpoint===''||!filter_var($endpoint,FILTER_VALIDATE_URL))throw new RuntimeException('Configure a WhatsApp provider API endpoint first.');
    $payload=json_encode(['to'=>$row['recipient'],'message'=>$row['message_text']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$ch=curl_init($endpoint);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_HTTPHEADER=>array_filter(['Content-Type: application/json',$token!==''?'Authorization: Bearer '.$token:null]),CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20]);$resp=(string)curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);$ok=$code>=200&&$code<300;db()->prepare("UPDATE whatsapp_queue SET status=?,attempts=attempts+1,provider_response=?,sent_at=IF(?,NOW(),sent_at) WHERE id=?")->execute([$ok?'sent':'failed',mb_substr($resp?:$err,0,4000),$ok?1:0,$queueId]);return $ok;
}

function growth_dashboard_stats(): array {return [
    'reviews'=>(int)growth_scalar("SELECT COUNT(*) FROM business_reviews"),'rating'=>round(growth_scalar("SELECT AVG(rating) FROM business_reviews WHERE status='published'"),1),'verification_pending'=>(int)growth_scalar("SELECT COUNT(*) FROM business_verifications WHERE status='pending'"),'bookings'=>(int)growth_scalar("SELECT COUNT(*) FROM business_bookings WHERE booking_date>=CURDATE()"),'leads_new'=>(int)growth_scalar("SELECT COUNT(*) FROM business_leads WHERE status='new'"),'wallet_points'=>(int)growth_scalar("SELECT COALESCE(SUM(points),0) FROM loyalty_wallets"),'referrals'=>(int)growth_scalar("SELECT COUNT(*) FROM referrals WHERE status IN ('registered','qualified','rewarded')"),'services'=>(int)growth_scalar("SELECT COUNT(*) FROM service_requests WHERE status='open'"),'classifieds'=>(int)growth_scalar("SELECT COUNT(*) FROM classifieds WHERE status='published'"),'reports'=>(int)growth_scalar("SELECT COUNT(*) FROM moderation_reports WHERE status IN ('open','reviewing')")];}

function growth_upgrade_homepage(): void {
    if(!growth_enabled('growth_home_enabled',true))return;try{if(setting_int('growth_homepage_version',0)>=350)return;$page=cms_home_page();if(!$page)return;$sections=cms_page_sections($page);$has=false;foreach($sections as $s)if(($s['type']??'')==='growth_widget')$has=true;if(!$has)$sections[]=['id'=>'growth_suite_widget','type'=>'growth_widget','enabled'=>1,'order'=>109,'title'=>'Trusted Local Discovery','subtitle'=>'Reviews, services & rewards','content'=>'Top-rated businesses, useful local services and community features.','image'=>'','items'=>''];usort($sections,fn($a,$b)=>(int)($a['order']??0)<=>(int)($b['order']??0));$json=cms_encode_layout($sections);db()->prepare("UPDATE cms_pages SET layout_json=?,updated_at=NOW() WHERE id=?")->execute([$json,$page['id']]);save_setting('homepage_sections',$json);save_setting('growth_homepage_version','350');}catch(Throwable $e){}
}
function lt_growth_widget(array $sections): void {
    $s=lt_section($sections,'growth_widget');if(!$s||!growth_enabled('growth_home_enabled',true))return;$rated=growth_top_rated(4);$emergency=growth_emergency_services(null,4);echo '<section class="growth-home"><div class="lt-shell"><div class="growth-home-head"><div><span>'.e($s['subtitle']??'TRUSTED LOCAL DISCOVERY').'</span><h2>'.e($s['title']??'Top Rated & Useful Around You').'</h2><p>'.e($s['content']??'Reviews, services, rewards and emergency information in one place.').'</p></div><a href="/businesses.php">Explore Businesses →</a></div><div class="growth-home-grid">';foreach($rated as $b)echo '<a class="growth-rated" href="/business.php?slug='.urlencode($b['slug']).'"><div class="growth-rated-img" '.($b['image']?'style="background-image:url(\''.e($b['image']).'\')"':'').'></div><div><span>★ '.e(number_format((float)$b['rating'],1)).' · '.e($b['review_count']).' reviews</span><h3>'.e($b['name']).'</h3><p>'.e($b['category_name']).' · '.e($b['city_name']).'</p></div></a>';if(!$rated)echo '<div class="growth-empty"><div class="growth-empty-icon" aria-hidden="true">★</div><div class="growth-empty-copy"><b>Shahkot trusted list is growing</b><span>Top-rated businesses will appear here as published reviews come in.</span></div><a href="/businesses.php">Browse Businesses →</a></div>';echo '</div><div class="growth-quick-links"><a href="/food.php"><b>🍽 Food & Menus</b><span>Browse restaurant menus</span></a><a href="/services.php"><b>🛠 Request a Service</b><span>Get local provider quotes</span></a><a href="/classifieds.php"><b>🏷 Classifieds</b><span>Local buy, sell & wanted</span></a><a href="/rewards.php"><b>★ Rewards</b><span>Loyalty points & referrals</span></a></div>';if($emergency){echo '<div class="growth-emergency-strip"><strong>Emergency & Useful Numbers</strong>';foreach($emergency as $x)echo '<a href="tel:'.e($x['phone']).'"><span>'.e($x['name']).'</span><b>'.e($x['phone']).'</b></a>';echo '<a class="all" href="/emergency.php">All Services →</a></div>';}echo '</div></section>';
}
