<?php
declare(strict_types=1);
require_once __DIR__.'/global_brand_v704.php';

function hn590_tid(): int { return function_exists('tenant_id') ? (int)tenant_id() : 0; }
function hn590_enabled(): bool { return !function_exists('setting_bool') || setting_bool('health_network_v590_enabled', true); }
function hn590_setting(string $k,string $d=''): string { return function_exists('setting') ? (string)setting($k,$d) : $d; }
function hn590_bool(string $k,bool $d=false): bool { return function_exists('setting_bool') ? setting_bool($k,$d) : $d; }
function hn590_int(string $k,int $d=0): int { return function_exists('setting_int') ? setting_int($k,$d) : $d; }
function hn590_money(float $n): string { return 'Rs '.number_format($n,0); }
function hn590_table_exists(string $name): bool { try{$q=db()->prepare('SHOW TABLES LIKE ?');$q->execute([$name]);return (bool)$q->fetchColumn();}catch(Throwable $e){return false;} }
function hn590_json(array $v): string { return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?:'{}'; }
function hn590_slug(string $v): string {$v=mb_strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/u','-',$v)??'';return trim($v,'-')?:('item-'.bin2hex(random_bytes(3)));}
function hn590_safe_redirect(string $url): never { header('Location: '.$url,true,302);exit; }
function hn590_require_login(string $back): array {$u=current_user();if(!$u)hn590_safe_redirect('/login.php?redirect='.urlencode($back));return $u;}
function hn590_set(string $key,string $value): void { if(function_exists('set_setting')){set_setting($key,$value);return;} try{db()->prepare('INSERT INTO settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)')->execute([$key,$value]);}catch(Throwable $e){} }
function hn590_track(string $event,string $entity='',?int $entityId=null,array $meta=[]): void { if(!hn590_table_exists('health_network_activity_v590'))return;try{$u=current_user();$raw=(string)($_SERVER['REMOTE_ADDR']??'').(string)($_SERVER['HTTP_USER_AGENT']??'').date('Y-m-d');$hash=hash('sha256',$raw.'|health-network-v590');db()->prepare('INSERT INTO health_network_activity_v590(tenant_id,user_id,visitor_hash,event_type,entity_type,entity_id,meta_json,created_at) VALUES(?,?,?,?,?,?,?,NOW())')->execute([hn590_tid(),$u?(int)$u['id']:null,$hash,$event,$entity?:null,$entityId,$meta?hn590_json($meta):null]);}catch(Throwable $e){} }
function hn590_next_no(string $prefix,string $table): string {return $prefix.'-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));}

function hn590_pharmacies(bool $public=true): array {try{$sql="SELECT * FROM health_pharmacies_v590 WHERE tenant_id=?".($public?" AND status='active' AND verified=1":"")." ORDER BY featured DESC,name";$q=db()->prepare($sql);$q->execute([hn590_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_pharmacy(int $id): ?array {try{$q=db()->prepare('SELECT * FROM health_pharmacies_v590 WHERE id=? AND tenant_id=? LIMIT 1');$q->execute([$id,hn590_tid()]);return $q->fetch()?:null;}catch(Throwable $e){return null;} }
function hn590_pharmacy_products(int $pharmacyId,string $q=''): array {try{$sql="SELECT * FROM health_pharmacy_products_v590 WHERE tenant_id=? AND pharmacy_id=? AND status='active'";$p=[hn590_tid(),$pharmacyId];if($q!==''){$sql.=' AND (name LIKE ? OR generic_name LIKE ? OR category LIKE ?)';$s='%'.$q.'%';array_push($p,$s,$s,$s);} $sql.=' ORDER BY stock_qty>0 DESC,name LIMIT 120';$st=db()->prepare($sql);$st->execute($p);return $st->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_labs(bool $public=true): array {try{$sql="SELECT * FROM health_labs_v590 WHERE tenant_id=?".($public?" AND status='active' AND verified=1":"")." ORDER BY featured DESC,name";$q=db()->prepare($sql);$q->execute([hn590_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_lab(int $id): ?array {try{$q=db()->prepare('SELECT * FROM health_labs_v590 WHERE id=? AND tenant_id=? LIMIT 1');$q->execute([$id,hn590_tid()]);return $q->fetch()?:null;}catch(Throwable $e){return null;} }
function hn590_lab_tests(int $labId): array {try{$q=db()->prepare("SELECT * FROM health_lab_tests_v590 WHERE tenant_id=? AND lab_id=? AND status='active' ORDER BY category,name");$q->execute([hn590_tid(),$labId]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_ambulances(bool $availableOnly=false): array {try{$sql="SELECT a.*,COALESCE(u.name,'Driver') driver_name FROM health_ambulances_v590 a LEFT JOIN users u ON u.id=a.driver_user_id WHERE a.tenant_id=? AND a.status<>'disabled'".($availableOnly?" AND a.availability='available'":"")." ORDER BY a.availability='available' DESC,a.vehicle_no";$q=db()->prepare($sql);$q->execute([hn590_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_user_prescriptions(int $uid): array {if(!hn590_table_exists('health_prescriptions_v580'))return [];try{$q=db()->prepare("SELECT p.id,p.prescription_no,p.created_at,d.display_name doctor_name FROM health_prescriptions_v580 p LEFT JOIN health_doctors_v580 d ON d.id=p.doctor_id WHERE p.patient_user_id=? AND p.tenant_id=? ORDER BY p.created_at DESC LIMIT 30");$q->execute([$uid,hn590_tid()]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_create_pharmacy_order(int $userId,int $pharmacyId,int $productId,int $qty,?int $prescriptionId,string $fulfillment,string $address=''): int {
    $qty=max(1,min(25,$qty));$p=hn590_pharmacy($pharmacyId);if(!$p||$p['status']!=='active')throw new RuntimeException('Pharmacy is unavailable.');
    if(!in_array($fulfillment,['pickup','delivery'],true))$fulfillment='pickup';if($fulfillment==='delivery'&&!$p['delivery_available'])throw new RuntimeException('Delivery is not available from this pharmacy.');if($fulfillment==='pickup'&&!$p['pickup_available'])throw new RuntimeException('Pickup is not available from this pharmacy.');
    db()->beginTransaction();try{
        $q=db()->prepare("SELECT * FROM health_pharmacy_products_v590 WHERE id=? AND pharmacy_id=? AND tenant_id=? AND status='active' LIMIT 1 FOR UPDATE");$q->execute([$productId,$pharmacyId,hn590_tid()]);$prod=$q->fetch();if(!$prod)throw new RuntimeException('Product is unavailable.');if((int)$prod['stock_qty']<$qty)throw new RuntimeException('Requested quantity is not available.');
        if((int)$prod['prescription_required']===1){if(!$prescriptionId)throw new RuntimeException('A valid prescription must be selected for this item.');$valid=false;foreach(hn590_user_prescriptions($userId) as $rx)if((int)$rx['id']===$prescriptionId){$valid=true;break;}if(!$valid)throw new RuntimeException('Selected prescription is not available for this account.');}
        $total=(float)$prod['price']*$qty;$no=hn590_next_no('PH','health_pharmacy_orders_v590');
        db()->prepare("INSERT INTO health_pharmacy_orders_v590(tenant_id,order_no,user_id,pharmacy_id,prescription_id,total_amount,status,payment_status,fulfillment,delivery_address,created_at,updated_at) VALUES(?,?,?,?,?,?,'pending','unpaid',?,?,NOW(),NOW())")->execute([hn590_tid(),$no,$userId,$pharmacyId,$prescriptionId,$total,$fulfillment,$address]);$oid=(int)db()->lastInsertId();
        db()->prepare('INSERT INTO health_pharmacy_order_items_v590(order_id,product_id,item_name,unit_price,qty,total) VALUES(?,?,?,?,?,?)')->execute([$oid,$productId,$prod['name'],$prod['price'],$qty,$total]);
        $up=db()->prepare('UPDATE health_pharmacy_products_v590 SET stock_qty=stock_qty-?,updated_at=NOW() WHERE id=? AND stock_qty>=?');$up->execute([$qty,$productId,$qty]);if($up->rowCount()!==1)throw new RuntimeException('Stock changed while ordering. Please try again.');
        db()->commit();hn590_track('pharmacy_order','pharmacy_order',$oid,['pharmacy_id'=>$pharmacyId]);return $oid;
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}
}
function hn590_create_lab_booking(int $uid,int $labId,int $testId,string $when,bool $home,string $address=''): int {$lab=hn590_lab($labId);if(!$lab||$lab['status']!=='active')throw new RuntimeException('Lab is unavailable.');$q=db()->prepare("SELECT * FROM health_lab_tests_v590 WHERE id=? AND lab_id=? AND tenant_id=? AND status='active' LIMIT 1");$q->execute([$testId,$labId,hn590_tid()]);$t=$q->fetch();if(!$t)throw new RuntimeException('Test is unavailable.');$ts=strtotime($when);if(!$ts||$ts<time()-300)throw new RuntimeException('Choose a future booking time.');if($home&&!$lab['home_collection'])throw new RuntimeException('This lab does not offer home sample collection.');$no=hn590_next_no('LAB','health_lab_bookings_v590');db()->prepare("INSERT INTO health_lab_bookings_v590(tenant_id,booking_no,user_id,lab_id,test_id,scheduled_at,home_collection,collection_address,amount,status,payment_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'requested','unpaid',NOW(),NOW())")->execute([hn590_tid(),$no,$uid,$labId,$testId,date('Y-m-d H:i:s',$ts),$home?1:0,$address,(float)$t['price']]);$id=(int)db()->lastInsertId();hn590_track('lab_booking','lab_booking',$id,['lab_id'=>$labId]);return $id;}
function hn590_create_ambulance_request(int $uid,string $pickup,string $destination,string $phone,string $note='',?float $lat=null,?float $lon=null): int {if(trim($pickup)===''||trim($phone)==='')throw new RuntimeException('Pickup location and contact number are required.');$no=hn590_next_no('AMB','health_ambulance_requests_v590');db()->prepare("INSERT INTO health_ambulance_requests_v590(tenant_id,request_no,user_id,pickup_address,destination,contact_phone,request_note,pickup_lat,pickup_lng,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'requested',NOW(),NOW())")->execute([hn590_tid(),$no,$uid,$pickup,$destination,$phone,$note,$lat,$lon]);$id=(int)db()->lastInsertId();hn590_track('ambulance_request','ambulance_request',$id);return $id;}

function hn590_staff_rows(int $uid): array {try{$q=db()->prepare('SELECT * FROM health_network_staff_v590 WHERE tenant_id=? AND user_id=? AND status=1');$q->execute([hn590_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function hn590_staff_scope(?array $u=null): array {$u=$u?:current_user();$o=['all'=>false,'roles'=>[],'pharmacy_ids'=>[],'lab_ids'=>[],'ambulance_ids'=>[]];if(!$u)return $o;if(function_exists('is_super_admin')&&is_super_admin($u)){$o['all']=true;return $o;}foreach(hn590_staff_rows((int)$u['id']) as $r){$o['roles'][]=$r['access_role'];if($r['access_role']==='network_admin')$o['all']=true;if($r['pharmacy_id'])$o['pharmacy_ids'][]=(int)$r['pharmacy_id'];if($r['lab_id'])$o['lab_ids'][]=(int)$r['lab_id'];if($r['ambulance_id'])$o['ambulance_ids'][]=(int)$r['ambulance_id'];}$o['roles']=array_values(array_unique($o['roles']));$o['pharmacy_ids']=array_values(array_unique($o['pharmacy_ids']));$o['lab_ids']=array_values(array_unique($o['lab_ids']));$o['ambulance_ids']=array_values(array_unique($o['ambulance_ids']));return $o;}
function hn590_scope_allows(string $type,int $id,?array $u=null): bool {$s=hn590_staff_scope($u);if($s['all'])return true;$key=$type.'_ids';return in_array($id,$s[$key]??[],true);}
function hn590_stats(): array {$s=['pharmacies'=>0,'labs'=>0,'ambulances'=>0,'available_ambulances'=>0,'orders_30'=>0,'lab_bookings_30'=>0,'ambulance_requests_30'=>0,'reports_ready'=>0];try{$tid=hn590_tid();$one=function($sql)use($tid){$q=db()->prepare($sql);$q->execute([$tid]);return (int)$q->fetchColumn();};$s['pharmacies']=$one("SELECT COUNT(*) FROM health_pharmacies_v590 WHERE tenant_id=? AND status='active'");$s['labs']=$one("SELECT COUNT(*) FROM health_labs_v590 WHERE tenant_id=? AND status='active'");$s['ambulances']=$one("SELECT COUNT(*) FROM health_ambulances_v590 WHERE tenant_id=? AND status<>'disabled'");$s['available_ambulances']=$one("SELECT COUNT(*) FROM health_ambulances_v590 WHERE tenant_id=? AND status<>'disabled' AND availability='available'");$s['orders_30']=$one("SELECT COUNT(*) FROM health_pharmacy_orders_v590 WHERE tenant_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");$s['lab_bookings_30']=$one("SELECT COUNT(*) FROM health_lab_bookings_v590 WHERE tenant_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");$s['ambulance_requests_30']=$one("SELECT COUNT(*) FROM health_ambulance_requests_v590 WHERE tenant_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");$s['reports_ready']=$one("SELECT COUNT(*) FROM health_lab_reports_v590 WHERE tenant_id=? AND status='published'");}catch(Throwable $e){}return $s;}
function hn590_activity_days(int $days=14): array {$out=[];try{$q=db()->prepare("SELECT DATE(created_at) d,COUNT(*) n FROM health_network_activity_v590 WHERE tenant_id=? AND created_at>=DATE_SUB(CURDATE(),INTERVAL ? DAY) GROUP BY DATE(created_at) ORDER BY d");$q->execute([hn590_tid(),$days]);$m=[];foreach($q->fetchAll()?:[] as $r)$m[$r['d']]=(int)$r['n'];for($i=$days-1;$i>=0;$i--){$d=date('Y-m-d',strtotime('-'.$i.' day'));$out[]=['d'=>$d,'n'=>$m[$d]??0];}}catch(Throwable $e){}return $out;}

function hn590_public_header(string $title='Healthcare Network',string $desc='Pharmacy, labs and ambulance services.'): void {global $config;$brand=function_exists('gb704_brand_name')?gb704_brand_name('ShahkotPK'):(function_exists('tenant_brand')?tenant_brand('site_name','ShahkotPK'):($config['app_name']??'ShahkotPK'));$logo=function_exists('gb704_picture')?gb704_picture('healthnet',$brand):'';$brandMarkup=$logo!==''?$logo.'<span class="gb704-module-label">Healthcare</span>':'<i>✦</i><span><b>Healthcare Network</b><small>'.e($brand).' Health Services</small></span>';$em=hn590_setting('health_network_v590_emergency_number',hn590_setting('doctor_online_v580_emergency_number','1122'));echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="'.e(csrf_token()).'"><title>'.e($title).' - '.e($brand).'</title><meta name="description" content="'.e($desc).'"><link rel="stylesheet" href="/assets/health-network-5.9.0.css?v=590">'.(function_exists('gb704_asset_tag')?gb704_asset_tag():'').'<script defer src="/assets/health-network-5.9.0.js?v=590"></script></head><body class="hn590-body">'; require_once __DIR__.'/views/header.php'; }
function hn590_public_footer(): void { require_once __DIR__.'/views/footer.php'; echo '</body></html>';}
