<?php
declare(strict_types=1);
require_once __DIR__.'/global_brand_v704.php';

function sc630_tid(): int { return function_exists('tenant_id') ? (int)tenant_id() : 0; }
function sc630_city_id(): int { try{return function_exists('current_city_id')?(int)(current_city_id()?:0):0;}catch(Throwable $e){return 0;} }
function sc630_setting(string $key,string $default=''): string { try{return function_exists('setting')?(string)setting($key,$default):$default;}catch(Throwable $e){return $default;} }
function sc630_bool(string $key,bool $default=true): bool { try{return function_exists('setting_bool')?setting_bool($key,$default):$default;}catch(Throwable $e){return $default;} }
function sc630_enabled(): bool { return sc630_bool('smart_city_v630_enabled',true); }
function sc630_money(float $n): string { return 'Rs '.number_format($n,2); }
function sc630_table(string $table): bool { static $c=[];if(isset($c[$table]))return $c[$table];try{$q=db()->prepare('SHOW TABLES LIKE ?');$q->execute([$table]);return $c[$table]=(bool)$q->fetchColumn();}catch(Throwable $e){return $c[$table]=false;} }
function sc630_columns(string $table): array { static $c=[];if(isset($c[$table]))return $c[$table];try{$q=db()->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`');$out=[];foreach($q->fetchAll()?:[] as $r)$out[(string)$r['Field']]=true;return $c[$table]=$out;}catch(Throwable $e){return $c[$table]=[];} }
function sc630_next_no(string $prefix): string { return strtoupper($prefix).'-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(6)),0,10)); }
function sc630_emergency_number(): string { return sc630_setting('smart_city_v630_emergency_number',sc630_setting('health_network_v590_emergency_number','1122')); }
function sc630_user(): ?array { return function_exists('current_user')?current_user():null; }
function sc630_login_url(string $return='/citizen.php'): string { return '/login.php?return='.rawurlencode($return); }
function sc630_require_user(): array { $u=sc630_user();if(!$u){header('Location: '.sc630_login_url($_SERVER['REQUEST_URI']??'/citizen.php'),true,302);exit;}return $u; }
function sc630_visitor_hash(): string { $day=date('Y-m-d');$raw=(string)($_SERVER['REMOTE_ADDR']??'').'|'.(string)($_SERVER['HTTP_USER_AGENT']??'').'|'.$day.'|'.sc630_tid();return hash('sha256',$raw); }
function sc630_track(string $module,string $action,string $entityType='',?int $entityId=null,array $meta=[]): void { try{$u=sc630_user();$q=db()->prepare('INSERT INTO smart_recommendation_events_v630(tenant_id,user_id,visitor_hash,module,action,entity_type,entity_id,meta_json,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())');$q->execute([sc630_tid(),$u?(int)$u['id']:null,$u?null:sc630_visitor_hash(),mb_substr($module,0,80),mb_substr($action,0,80),$entityType?:null,$entityId,$meta?json_encode($meta,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null]);}catch(Throwable $e){} }

function sc630_wallet_ensure(int $uid): array {
    $tid=sc630_tid();
    db()->prepare("INSERT IGNORE INTO citizen_wallet_accounts_v630(tenant_id,user_id,balance,loyalty_points,status,created_at,updated_at) VALUES(?,?,0,0,'active',NOW(),NOW())")->execute([$tid,$uid]);
    $q=db()->prepare('SELECT * FROM citizen_wallet_accounts_v630 WHERE tenant_id=? AND user_id=? LIMIT 1');$q->execute([$tid,$uid]);return $q->fetch()?:['balance'=>0,'loyalty_points'=>0,'status'=>'active'];
}
function sc630_wallet_ledger(int $uid,int $limit=30): array { try{$q=db()->prepare('SELECT * FROM citizen_wallet_transactions_v630 WHERE tenant_id=? AND user_id=? ORDER BY id DESC LIMIT '.max(1,min(100,$limit)));$q->execute([sc630_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function sc630_wallet_post(int $uid,string $direction,float $amount,int $pointsDelta,string $category,string $note='',?int $actor=null,?string $referenceType=null,?int $referenceId=null,?string $referenceKey=null): array {
    if(!in_array($direction,['credit','debit'],true))throw new RuntimeException('Invalid wallet direction.');$amount=round(max(0,$amount),2);$tid=sc630_tid();
    db()->beginTransaction();try{
        db()->prepare("INSERT IGNORE INTO citizen_wallet_accounts_v630(tenant_id,user_id,balance,loyalty_points,status,created_at,updated_at) VALUES(?,?,0,0,'active',NOW(),NOW())")->execute([$tid,$uid]);
        $q=db()->prepare('SELECT * FROM citizen_wallet_accounts_v630 WHERE tenant_id=? AND user_id=? FOR UPDATE');$q->execute([$tid,$uid]);$a=$q->fetch();if(!$a||$a['status']!=='active')throw new RuntimeException('Wallet is not active.');
        $balance=(float)$a['balance'];$points=(int)$a['loyalty_points'];$next=$direction==='credit'?$balance+$amount:$balance-$amount;if($next<-0.001)throw new RuntimeException('Insufficient wallet balance.');$nextPoints=$points+$pointsDelta;if($nextPoints<0)throw new RuntimeException('Insufficient loyalty points.');
        $no=sc630_next_no('WAL');$q=db()->prepare('INSERT INTO citizen_wallet_transactions_v630(tenant_id,user_id,transaction_no,direction,amount,points_delta,category,reference_type,reference_id,reference_key,note,balance_after,points_after,actor_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())');$q->execute([$tid,$uid,$no,$direction,$amount,$pointsDelta,mb_substr($category,0,80),$referenceType,$referenceId,$referenceKey,mb_substr($note,0,500),$next,$nextPoints,$actor]);
        db()->prepare('UPDATE citizen_wallet_accounts_v630 SET balance=?,loyalty_points=?,updated_at=NOW() WHERE tenant_id=? AND user_id=?')->execute([$next,$nextPoints,$tid,$uid]);db()->commit();return ['transaction_no'=>$no,'balance'=>$next,'points'=>$nextPoints];
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();if($referenceKey&&str_contains(strtolower($e->getMessage()),'duplicate'))return sc630_wallet_ensure($uid);throw $e;}
}
function sc630_loyalty_rule(string $event): ?array { try{$q=db()->prepare('SELECT * FROM loyalty_rules_v630 WHERE event_key=? AND status=1 AND tenant_id IN (0,?) ORDER BY tenant_id DESC LIMIT 1');$q->execute([$event,sc630_tid()]);return $q->fetch()?:null;}catch(Throwable $e){return null;} }
function sc630_award_points(int $uid,string $event,string $ref): int { $r=sc630_loyalty_rule($event);if(!$r)return 0;try{$q=db()->prepare('SELECT COUNT(*) FROM loyalty_events_v630 WHERE tenant_id=? AND user_id=? AND event_key=? AND DATE(created_at)=CURDATE()');$q->execute([sc630_tid(),$uid,$event]);if((int)$q->fetchColumn()>=(int)$r['max_per_day'])return 0;db()->prepare('INSERT INTO loyalty_events_v630(tenant_id,user_id,event_key,event_ref,points,created_at) VALUES(?,?,?,?,?,NOW())')->execute([sc630_tid(),$uid,$event,mb_substr($ref,0,190),(int)$r['points']]);sc630_wallet_post($uid,'credit',0,(int)$r['points'],'loyalty','Loyalty: '.$r['name'],null,'loyalty_event',null,'loyalty:'.$event.':'.$ref);return (int)$r['points'];}catch(Throwable $e){return 0;} }
function sc630_sync_user_rewards(int $uid): void {
    $jobs=[
      ['marketplace_orders_v550','marketplace_order',"buyer_user_id=? AND status IN ('delivered','completed')"],
      ['health_appointments_v580','health_booking',"patient_user_id=? AND status='completed'"],
      ['property_leads_v560','property_inquiry',"user_id=?"]
    ];
    foreach($jobs as [$table,$event,$where]){if(!sc630_table($table))continue;try{$q=db()->prepare('SELECT id FROM `'.$table.'` WHERE '.$where.' ORDER BY id DESC LIMIT 20');$q->execute([$uid]);foreach($q->fetchAll()?:[] as $r)sc630_award_points($uid,$event,(string)$r['id']);}catch(Throwable $e){}}
}
function sc630_redeem_points(int $uid,int $points): array { if(!sc630_bool('smart_city_v630_loyalty_enabled',true))throw new RuntimeException('Loyalty redemption is disabled.');$min=max(1,(int)sc630_setting('smart_city_v630_min_redeem_points','500'));if($points<$min)throw new RuntimeException('Minimum redemption is '.$min.' points.');$rate=max(1,(int)sc630_setting('smart_city_v630_points_per_rupee','10'));$amount=floor($points/$rate*100)/100;return sc630_wallet_post($uid,'credit',$amount,-$points,'loyalty_redemption','Converted '.$points.' points into wallet credit.',$uid,'loyalty_redeem',null,'redeem:'.bin2hex(random_bytes(7))); }

function sc630_municipal_categories(): array { try{$q=db()->prepare('SELECT * FROM municipal_categories_v630 WHERE status=1 AND tenant_id IN(0,?) ORDER BY tenant_id DESC,sort_order,name');$q->execute([sc630_tid()]);$seen=[];$out=[];foreach($q->fetchAll()?:[] as $r){if(isset($seen[$r['slug']]))continue;$seen[$r['slug']]=1;$out[]=$r;}return $out;}catch(Throwable $e){return [];} }
function sc630_create_request(int $uid,array $d): int { $type=in_array($d['request_type']??'complaint',['complaint','service_request','lost_found'],true)?$d['request_type']:'complaint';$title=trim((string)($d['title']??''));$desc=trim((string)($d['description']??''));if(mb_strlen($title)<5||mb_strlen($desc)<10)throw new RuntimeException('Please add a clear title and description.');$cat=(int)($d['category_id']??0)?:null;$ref=sc630_next_no('CITY');$q=db()->prepare("INSERT INTO municipal_requests_v630(tenant_id,city_id,reference_no,user_id,request_type,category_id,title,description,address,area,latitude,longitude,priority,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'submitted',NOW(),NOW())");$q->execute([sc630_tid(),sc630_city_id(),$ref,$uid,$type,$cat,mb_substr($title,0,220),$desc,trim((string)($d['address']??''))?:null,trim((string)($d['area']??''))?:null,($d['latitude']??'')!==''?(float)$d['latitude']:null,($d['longitude']??'')!==''?(float)$d['longitude']:null,($d['priority']??'normal')==='urgent'?'urgent':'normal']);$id=(int)db()->lastInsertId();db()->prepare("INSERT INTO municipal_request_updates_v630(request_id,actor_user_id,status,note,public_note,created_at) VALUES(?,?,'submitted','Request received by the citizen service portal.',1,NOW())")->execute([$id,$uid]);sc630_notify($uid,'Citizen request received','Your request '.$ref.' has been submitted.','/complaints.php?id='.$id,'normal','◫');sc630_award_points($uid,'municipal_request',(string)$id);sc630_track('municipal','submit','request',$id);return $id; }
function sc630_user_requests(int $uid,int $limit=50): array { try{$q=db()->prepare('SELECT r.*,c.name category_name,c.icon category_icon FROM municipal_requests_v630 r LEFT JOIN municipal_categories_v630 c ON c.id=r.category_id WHERE r.tenant_id=? AND r.user_id=? ORDER BY r.id DESC LIMIT '.max(1,min(100,$limit)));$q->execute([sc630_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function sc630_request(int $id,?int $uid=null): ?array { try{$sql='SELECT r.*,c.name category_name,c.icon category_icon,u.name assigned_name FROM municipal_requests_v630 r LEFT JOIN municipal_categories_v630 c ON c.id=r.category_id LEFT JOIN users u ON u.id=r.assigned_user_id WHERE r.id=? AND r.tenant_id=?';$p=[$id,sc630_tid()];if($uid!==null){$sql.=' AND r.user_id=?';$p[]=$uid;}$q=db()->prepare($sql.' LIMIT 1');$q->execute($p);$r=$q->fetch();if(!$r)return null;$q=db()->prepare('SELECT x.*,u.name actor_name FROM municipal_request_updates_v630 x LEFT JOIN users u ON u.id=x.actor_user_id WHERE x.request_id=? AND (x.public_note=1 OR ? IS NULL) ORDER BY x.id');$q->execute([$id,$uid]);$r['updates']=$q->fetchAll()?:[];return $r;}catch(Throwable $e){return null;} }

function sc630_notify(?int $uid,string $title,string $message,string $url='',string $priority='normal',string $icon='◇',string $audience='user'): int { try{$q=db()->prepare('INSERT INTO smart_notifications_v630(tenant_id,user_id,audience,channel,title,message,action_url,icon,priority,created_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())');$q->execute([sc630_tid(),$uid,$audience,'in_app',mb_substr($title,0,220),$message,$url?:null,mb_substr($icon,0,40),in_array($priority,['normal','important','urgent'],true)?$priority:'normal']);return (int)db()->lastInsertId();}catch(Throwable $e){return 0;} }
function sc630_notifications(int $uid,int $limit=30): array { try{$q=db()->prepare("SELECT n.*,IF(r.id IS NULL,0,1) is_read FROM smart_notifications_v630 n LEFT JOIN smart_notification_reads_v630 r ON r.notification_id=n.id AND r.user_id=? WHERE n.tenant_id=? AND (n.user_id=? OR (n.user_id IS NULL AND n.audience IN ('all','citizen'))) AND (n.expires_at IS NULL OR n.expires_at>NOW()) ORDER BY n.id DESC LIMIT ".max(1,min(100,$limit)));$q->execute([$uid,sc630_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function sc630_mark_notification(int $id,int $uid): void { try{db()->prepare('INSERT IGNORE INTO smart_notification_reads_v630(notification_id,user_id,read_at) SELECT id,?,NOW() FROM smart_notifications_v630 WHERE id=? AND tenant_id=? AND (user_id=? OR user_id IS NULL)')->execute([$uid,$id,sc630_tid(),$uid]);}catch(Throwable $e){} }
function sc630_unread_count(int $uid): int { try{$q=db()->prepare("SELECT COUNT(*) FROM smart_notifications_v630 n LEFT JOIN smart_notification_reads_v630 r ON r.notification_id=n.id AND r.user_id=? WHERE n.tenant_id=? AND (n.user_id=? OR (n.user_id IS NULL AND n.audience IN ('all','citizen'))) AND r.id IS NULL AND (n.expires_at IS NULL OR n.expires_at>NOW())");$q->execute([$uid,sc630_tid(),$uid]);return (int)$q->fetchColumn();}catch(Throwable $e){return 0;} }

function sc630_addresses(int $uid): array { try{$q=db()->prepare('SELECT * FROM citizen_addresses_v630 WHERE tenant_id=? AND user_id=? ORDER BY is_default DESC,id DESC');$q->execute([sc630_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }
function sc630_contacts(int $uid): array { try{$q=db()->prepare('SELECT * FROM citizen_emergency_contacts_v630 WHERE tenant_id=? AND user_id=? ORDER BY is_primary DESC,id DESC');$q->execute([sc630_tid(),$uid]);return $q->fetchAll()?:[];}catch(Throwable $e){return [];} }

function sc630_safe_count(string $table,string $where='1=1',array $params=[]): int { if(!sc630_table($table))return 0;try{$q=db()->prepare('SELECT COUNT(*) FROM `'.$table.'` WHERE '.$where);$q->execute($params);return (int)$q->fetchColumn();}catch(Throwable $e){return 0;} }
function sc630_user_modules(int $uid): array {
    $tid=sc630_tid();$out=[];
    $out['orders']=sc630_safe_count('marketplace_orders_v550','buyer_user_id=?',[$uid]);
    $out['appointments']=sc630_safe_count('health_appointments_v580','patient_user_id=?',[$uid]);
    $out['blood_requests']=sc630_safe_count('blood_requests_v570','requester_user_id=?',[$uid]);
    $out['lab_bookings']=sc630_safe_count('health_lab_bookings_v590','user_id=?',[$uid]);
    $out['pharmacy_orders']=sc630_safe_count('health_pharmacy_orders_v590','user_id=?',[$uid]);
    $out['ambulance_requests']=sc630_safe_count('health_ambulance_requests_v590','user_id=?',[$uid]);
    $out['property_leads']=sc630_safe_count('property_leads_v560','user_id=?',[$uid]);
    $out['municipal']=sc630_safe_count('municipal_requests_v630','tenant_id=? AND user_id=?',[$tid,$uid]);
    return $out;
}
function sc630_dashboard_stats(): array { $tid=sc630_tid();$s=[];$s['citizen_requests']=sc630_safe_count('municipal_requests_v630','tenant_id=?',[$tid]);$s['open_requests']=sc630_safe_count('municipal_requests_v630',"tenant_id=? AND status NOT IN ('resolved','closed','rejected')",[$tid]);$s['wallets']=sc630_safe_count('citizen_wallet_accounts_v630','tenant_id=?',[$tid]);try{$q=db()->prepare('SELECT COALESCE(SUM(balance),0),COALESCE(SUM(loyalty_points),0) FROM citizen_wallet_accounts_v630 WHERE tenant_id=?');$q->execute([$tid]);$r=$q->fetch(PDO::FETCH_NUM)?:[0,0];$s['wallet_balance']=(float)$r[0];$s['points']=(int)$r[1];}catch(Throwable $e){$s['wallet_balance']=0;$s['points']=0;}$s['notifications']=sc630_safe_count('smart_notifications_v630','tenant_id=?',[$tid]);$s['assistant_messages']=sc630_safe_count('smart_assistant_messages_v630','tenant_id=?',[$tid]);return $s; }

function sc630_search_table(string $table,string $titleCol,array $bodyCols,string $urlPrefix,string $type,string $q,int $limit=5,?string $statusWhere=null): array { if(!sc630_table($table))return [];$cols=sc630_columns($table);if(!isset($cols[$titleCol]))return [];$searchCols=array_values(array_filter(array_merge([$titleCol],$bodyCols),fn($x)=>isset($cols[$x])));if(!$searchCols)return [];$where=[];$p=[];foreach($searchCols as $c){$where[]='`'.$c.'` LIKE ?';$p[]='%'.$q.'%';}$tenant='';if(isset($cols['tenant_id'])){$tenant=' AND (`tenant_id`=0 OR `tenant_id`=?)';$p[]=sc630_tid();}$status=$statusWhere?' AND '.$statusWhere:'';$idCol=isset($cols['slug'])?'slug':'id';try{$sql='SELECT `'.$idCol.'` ref,`'.$titleCol.'` title'.(isset($cols['area'])?',`area`':'').(isset($cols['address'])?',`address`':'').' FROM `'.$table.'` WHERE ('.implode(' OR ',$where).')'.$tenant.$status.' LIMIT '.max(1,min(10,$limit));$st=db()->prepare($sql);$st->execute($p);$out=[];foreach($st->fetchAll()?:[] as $r){$ref=(string)$r['ref'];$url=$urlPrefix.(str_contains($urlPrefix,'?')?'':'?').(str_ends_with($urlPrefix,'=')?'':'id=').rawurlencode($ref);$out[]=['type'=>$type,'title'=>$r['title'],'subtitle'=>$r['area']??$r['address']??'','url'=>$url];}return $out;}catch(Throwable $e){return [];} }
function sc630_super_search(string $q,int $limit=24): array { $q=trim($q);if(mb_strlen($q)<2)return [];$all=[];$all=array_merge($all,sc630_search_table('businesses','name',['address','area'],'/business.php?','Business',$q,4,"status='active'"));$all=array_merge($all,sc630_search_table('health_doctors_v580','display_name',['qualification','bio'],'/doctor-profile.php?slug=','Doctor',$q,4,"approval_status='approved'"));$all=array_merge($all,sc630_search_table('blood_banks_v570','name',['address','area'],'/blood-bank.php?bank=','Blood Bank',$q,3,"status='active'"));$all=array_merge($all,sc630_search_table('health_pharmacies_v590','name',['address','area'],'/pharmacy.php?id=','Pharmacy',$q,3,"status='active'"));$all=array_merge($all,sc630_search_table('health_labs_v590','name',['address','area'],'/lab.php?id=','Lab',$q,3,"status='active'"));$all=array_merge($all,sc630_search_table('store_products','title',['short_description','description'],'/product.php?slug=','Product',$q,5,"status='published'"));$all=array_merge($all,sc630_search_table('edu_institutions_v700','name',['tagline','description','area'],'/institution.php?id=','Education',$q,4,"status='active'"));$all=array_merge($all,sc630_search_table('tourism_hotels_v700','name',['description','area'],'/hotel.php?id=','Hotel',$q,4,"status='active'"));$all=array_merge($all,sc630_search_table('tourism_restaurants_v700','name',['cuisine','area'],'/restaurant.php?id=','Restaurant',$q,4,"status='active'"));$all=array_merge($all,sc630_search_table('tourism_attractions_v700','name',['category','description','area'],'/tourism.php?place=','Tourism',$q,4,"status='active'"));return array_slice($all,0,max(1,min(50,$limit))); }

function sc630_detect_intent(string $text): string { $t=mb_strtolower($text);$sets=['emergency'=>['emergency','ambulance','rescue','حادث','ایمرجنسی'],'doctor'=>['doctor','appointment','checkup','consult','ڈاکٹر'],'blood'=>['blood','donor','donation','خون'],'pharmacy'=>['pharmacy','medicine','فارمیسی'],'lab'=>['lab','test','report','لیب'],'education'=>['school','college','academy','course','admission','education','تعلیم','سکول'],'transport'=>['bus','transport','ride','taxi','rickshaw','delivery','travel','سفر'],'tourism'=>['hotel','restaurant','tourism','tour','visit','stay','booking','ہوٹل'],'property'=>['property','house','plot','rent','گھر','پلاٹ'],'marketplace'=>['product','shop','buy','order','deal','shopping'],'municipal'=>['complaint','street','road','waste','water','light','municipal','شکایت'],'wallet'=>['wallet','points','loyalty','balance','earning'],'jobs'=>['job','vacancy','career','نوکری'],'events'=>['event','festival','program']];foreach($sets as $intent=>$words)foreach($words as $w)if(mb_strpos($t,$w)!==false)return $intent;return 'general'; }
function sc630_assistant_reply(string $text,?array $u=null): array {
    $intent=sc630_detect_intent($text);$em=sc630_emergency_number();$links=[];$reply='I can help you navigate ShahkotPK services and find the right module.';
    switch($intent){
      case 'emergency':$reply='For a life-threatening emergency, contact local emergency services now. The portal can also open the ambulance and emergency service pages, but a web request should not delay emergency help.';$links=[['Call '.$em,'tel:'.preg_replace('/[^0-9+]/','',$em)],['Ambulance','/ambulance.php'],['Emergency Help','/health-network.php']];break;
      case 'doctor':$reply='You can find city doctors, check availability and book online or in-person appointments from Doctor Online.';$links=[['Find Doctor','/find-doctor.php'],['My Health','/my-health.php']];break;
      case 'blood':$reply='Use Blood Bank to check participating banks, register as a donor or submit a blood request. Medical suitability and matching remain with authorized blood-bank staff.';$links=[['Blood Bank','/blood-bank.php'],['Donate Blood','/blood-donate.php'],['Request Blood','/blood-request.php']];break;
      case 'pharmacy':$reply='Browse the verified pharmacy network and submit medicine order requests. Prescription-required items remain subject to pharmacy verification.';$links=[['Pharmacies','/pharmacies.php'],['My Health Network','/health-network-account.php']];break;
      case 'lab':$reply='Browse diagnostic labs, published tests and available home sample collection, then manage bookings and reports privately.';$links=[['Diagnostic Labs','/labs.php'],['My Health Network','/health-network-account.php']];break;
      case 'education':$reply='Use the Education platform to discover schools, colleges and academies, compare programs and submit admission applications online.';$links=[['Education','/education.php'],['My Education','/education-account.php']];break;
      case 'transport':$reply='Use the Transport network for scheduled trips, ride requests, rickshaws, taxis and city delivery.';$links=[['Transport','/transport.php'],['Request Ride','/ride.php'],['My Travel','/transport-account.php']];break;
      case 'tourism':$reply='Explore local attractions, hotels, restaurants and tour packages, then manage bookings from your tourism dashboard.';$links=[['Tourism','/tourism.php'],['My Bookings','/tourism-account.php']];break;
      case 'property':$reply='Property Marketplace Pro lets you search, compare, save listings and request visits or inquiries.';$links=[['Property','/property.php'],['My Properties','/my-properties.php']];break;
      case 'marketplace':$reply='Use the marketplace to find products, deals, auctions and seller stores, and track your orders from your citizen dashboard.';$links=[['Marketplace','/shop.php'],['My Orders','/my-orders.php'],['Auctions','/auctions.php']];break;
      case 'municipal':$reply='You can submit a non-emergency city complaint or service request and track every status update with a reference number.';$links=[['City Services','/complaints.php'],['Citizen Dashboard','/citizen.php']];break;
      case 'wallet':$reply='Your Citizen Wallet keeps portal credits and loyalty points in an auditable ledger. You can view activity and redeem eligible loyalty points when enabled.';$links=[['Wallet & Loyalty','/wallet.php'],['Citizen Dashboard','/citizen.php']];break;
      case 'jobs':$reply='Browse current local opportunities from the ShahkotPK Jobs section.';$links=[['Jobs','/jobs.php']];break;
      case 'events':$reply='Browse current city events and activities from the Events section.';$links=[['Events','/events.php']];break;
      default:$hits=sc630_super_search($text,6);if($hits){$reply='I found a few relevant ShahkotPK results. Choose one below or refine your search.';foreach($hits as $h)$links[]=[$h['type'].' · '.$h['title'],$h['url']];}else{$links=[['Citizen Dashboard','/citizen.php'],['Super Search','/smart-assistant.php'],['City Services','/complaints.php'],['Healthcare','/health-network.php']];}
    }
    $session=session_id()?:bin2hex(random_bytes(8));try{$uid=$u?(int)$u['id']:null;$q=db()->prepare("INSERT INTO smart_assistant_messages_v630(tenant_id,user_id,session_key,role,intent,message,created_at) VALUES(?,?,?,'user',?,?,NOW()),(?,?,?,'assistant',?,?,NOW())");$q->execute([sc630_tid(),$uid,$session,$intent,$text,sc630_tid(),$uid,$session,$intent,$reply]);}catch(Throwable $e){}sc630_track('assistant','message','intent',null,['intent'=>$intent]);return ['intent'=>$intent,'reply'=>$reply,'links'=>$links];
}
function sc630_recommendations(?int $uid=null): array { $scores=[];if($uid){try{$q=db()->prepare('SELECT module,COUNT(*) n FROM smart_recommendation_events_v630 WHERE tenant_id=? AND user_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 60 DAY) GROUP BY module ORDER BY n DESC LIMIT 5');$q->execute([sc630_tid(),$uid]);foreach($q->fetchAll()?:[] as $r)$scores[$r['module']]=(int)$r['n'];}catch(Throwable $e){}}$catalog=['education'=>['Education','Schools, academies, programs and admissions','/education.php','▤'],'transport'=>['Transport','Trips, rides and city delivery','/transport.php','↔'],'tourism'=>['Tourism','Hotels, restaurants and city experiences','/tourism.php','✦'],'health'=>['Doctor Online','Book or manage a consultation','/doctor-online.php','✚'],'marketplace'=>['Marketplace','Shop local products and deals','/shop.php','◇'],'property'=>['Property','Explore homes, plots and commercial listings','/property.php','⌂'],'municipal'=>['City Services','Submit and track a city request','/complaints.php','◫'],'blood'=>['Blood Bank','Donation and blood request services','/blood-bank.php','♥'],'healthnet'=>['Healthcare Network','Pharmacy, labs and ambulance','/health-network.php','✦'],'jobs'=>['Jobs','Discover local opportunities','/jobs.php','▣']];$order=array_keys($scores);foreach(array_keys($catalog) as $k)if(!in_array($k,$order,true))$order[]=$k;$out=[];foreach(array_slice($order,0,6) as $k)if(isset($catalog[$k]))$out[]=['module'=>$k,'title'=>$catalog[$k][0],'text'=>$catalog[$k][1],'url'=>$catalog[$k][2],'icon'=>$catalog[$k][3]];return $out; }

function sc630_staff_permissions(int $uid): array { if($uid<1||!sc630_table('smart_city_staff_v630'))return [];try{$tid=sc630_tid();$q=db()->prepare('SELECT access_role,permissions_json FROM smart_city_staff_v630 WHERE user_id=? AND status=1 AND tenant_id=?');$q->execute([$uid,$tid]);$roles=['smartcity_admin'=>['smartcity.dashboard','smartcity.municipal.manage','smartcity.wallet.manage','smartcity.loyalty.manage','smartcity.notifications.manage','smartcity.ai.manage','smartcity.staff.manage','smartcity.analytics','smartcity.settings'],'municipal_manager'=>['smartcity.dashboard','smartcity.municipal.manage','smartcity.analytics'],'municipal_officer'=>['smartcity.dashboard','smartcity.municipal.manage'],'wallet_manager'=>['smartcity.dashboard','smartcity.wallet.manage','smartcity.loyalty.manage','smartcity.analytics'],'citizen_service'=>['smartcity.dashboard','smartcity.municipal.manage','smartcity.notifications.manage'],'ai_manager'=>['smartcity.dashboard','smartcity.ai.manage','smartcity.analytics'],'analyst'=>['smartcity.dashboard','smartcity.analytics']];$out=[];foreach($q->fetchAll()?:[] as $r){$p=json_decode((string)($r['permissions_json']??''),true);if(!is_array($p)||!$p)$p=$roles[$r['access_role']]??$roles['analyst'];$out=array_merge($out,$p);}return array_values(array_unique($out));}catch(Throwable $e){return [];} }

function sc630_public_header(string $title='Smart City Super App',string $desc='One account for city services.'): void { global $config;$brand=function_exists('gb704_brand_name')?gb704_brand_name('ShahkotPK'):(function_exists('tenant_brand')?tenant_brand('site_name','ShahkotPK'):($config['app_name']??'ShahkotPK'));$u=sc630_user();$unread=$u?sc630_unread_count((int)$u['id']):0;$logo=function_exists('gb704_picture')?gb704_picture('smartcity',$brand):'';$brandMarkup=$logo!==''?$logo.'<span class="gb704-module-label">Smart City</span>':'<i>S</i><span><b>'.e($brand).' Super App</b><small>Smart City Citizen Network</small></span>';echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#071a25"><meta name="description" content="'.e($desc).'"><meta name="csrf-token" content="'.e(csrf_token()).'"><link rel="manifest" href="/super-app-manifest.webmanifest"><link rel="stylesheet" href="/assets/smart-city-6.3.0.css?v=630">'.(function_exists('gb704_asset_tag')?gb704_asset_tag():'').'<script defer src="/assets/smart-city-6.3.0.js?v=630"></script><title>'.e($title).' - '.e($brand).'</title></head><body class="sc630-body">'; require_once __DIR__.'/views/header.php'; }
function sc630_public_footer(): void { require_once __DIR__.'/views/footer.php'; echo '</body></html>'; }
