-- ShahkotPK v2.8.0 Admin Control Center
INSERT INTO settings(setting_key,setting_value) VALUES
('city_location_features_enabled','1'),
('browser_geolocation_enabled','1'),
('default_map_provider','google'),
('default_map_zoom','14'),
('cms_media_uploads_enabled','1'),
('cms_theme_uploads_enabled','1'),
('cms_custom_css_enabled','1'),
('cms_revisions_limit','30'),
('subscription_invoice_due_days','7'),
('subscription_tax_percent','0'),
('subscription_auto_expire','1'),
('subscription_expiry_reminder_days','30'),
('advertisement_auto_schedule','1'),
('ad_default_priority','10'),
('ad_default_frequency_cap','0'),
('ad_allow_external_urls','1'),
('payment_reference_prefix','SHP'),
('payment_proof_max_mb','5'),
('payment_proof_required','0'),
('accounts_manual_journal_enabled','1'),
('accounts_csv_export_enabled','1'),
('accounts_business_ledger_enabled','1'),
('search_results_limit','100'),
('password_min_length','8'),
('recovery_update_history_limit','150'),
('recovery_backup_history_limit','200'),
('maintenance_message','Website is temporarily under maintenance. Please check again shortly.')
ON DUPLICATE KEY UPDATE setting_value=setting_value;
