-- ShahkotPK v5.7.0 Blood Bank & Donation Management Pro
-- Additive/idempotent migration. No existing tables are dropped or truncated.

CREATE TABLE IF NOT EXISTS blood_banks_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  city_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  license_no VARCHAR(120) NULL,
  manager_name VARCHAR(190) NULL,
  phone VARCHAR(80) NULL,
  emergency_phone VARCHAR(80) NULL,
  email VARCHAR(190) NULL,
  address TEXT NULL,
  area VARCHAR(190) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  map_url TEXT NULL,
  logo_url TEXT NULL,
  hero_image_url TEXT NULL,
  operating_hours_json LONGTEXT NULL,
  facilities_json LONGTEXT NULL,
  emergency_available TINYINT(1) NOT NULL DEFAULT 0,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bb570_bank_tenant_status (tenant_id,status),
  KEY idx_bb570_bank_city (city_id),
  KEY idx_bb570_bank_slug (tenant_id,slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_bank_staff_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  access_role VARCHAR(40) NOT NULL DEFAULT 'viewer',
  permissions_json LONGTEXT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  assigned_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bb570_staff_user (tenant_id,user_id,status),
  KEY idx_bb570_staff_bank (tenant_id,bank_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_donors_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  city_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id BIGINT UNSIGNED NULL,
  preferred_bank_id BIGINT UNSIGNED NULL,
  donor_code VARCHAR(80) NOT NULL,
  full_name VARCHAR(190) NOT NULL,
  phone VARCHAR(80) NOT NULL,
  email VARCHAR(190) NULL,
  blood_group VARCHAR(5) NOT NULL,
  date_of_birth DATE NULL,
  gender VARCHAR(30) NULL,
  address TEXT NULL,
  area VARCHAR(190) NULL,
  emergency_contact_name VARCHAR(190) NULL,
  emergency_contact_phone VARCHAR(80) NULL,
  donor_status VARCHAR(30) NOT NULL DEFAULT 'active',
  screening_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  screening_note TEXT NULL,
  contact_opt_in TINYINT(1) NOT NULL DEFAULT 0,
  public_registry_opt_in TINYINT(1) NOT NULL DEFAULT 0,
  consent_at DATETIME NULL,
  last_donation_date DATE NULL,
  total_donations INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bb570_donor_code (donor_code),
  KEY idx_bb570_donor_tenant_group (tenant_id,blood_group,donor_status),
  KEY idx_bb570_donor_user (user_id),
  KEY idx_bb570_donor_bank (preferred_bank_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_donation_appointments_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NOT NULL,
  donor_id BIGINT UNSIGNED NULL,
  camp_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  phone VARCHAR(80) NOT NULL,
  blood_group VARCHAR(5) NOT NULL,
  scheduled_at DATETIME NOT NULL,
  source VARCHAR(30) NOT NULL DEFAULT 'public',
  note TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'requested',
  assigned_to BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bb570_appt_tenant_date (tenant_id,scheduled_at,status),
  KEY idx_bb570_appt_bank (bank_id,status),
  KEY idx_bb570_appt_user (user_id),
  KEY idx_bb570_appt_donor (donor_id),
  KEY idx_bb570_appt_camp (camp_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_donations_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NOT NULL,
  donor_id BIGINT UNSIGNED NULL,
  appointment_id BIGINT UNSIGNED NULL,
  donation_no VARCHAR(80) NOT NULL,
  blood_group VARCHAR(5) NOT NULL,
  component VARCHAR(40) NOT NULL DEFAULT 'whole_blood',
  quantity_ml INT UNSIGNED NOT NULL DEFAULT 450,
  collected_at DATETIME NOT NULL,
  screening_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  status VARCHAR(30) NOT NULL DEFAULT 'collected',
  notes TEXT NULL,
  recorded_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bb570_donation_no (donation_no),
  KEY idx_bb570_donation_tenant_date (tenant_id,collected_at),
  KEY idx_bb570_donation_bank (bank_id),
  KEY idx_bb570_donation_donor (donor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_stock_batches_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NOT NULL,
  donation_id BIGINT UNSIGNED NULL,
  bag_code VARCHAR(100) NOT NULL,
  blood_group VARCHAR(5) NOT NULL,
  component VARCHAR(40) NOT NULL DEFAULT 'whole_blood',
  volume_ml INT UNSIGNED NOT NULL DEFAULT 450,
  collected_at DATETIME NULL,
  expires_at DATETIME NOT NULL,
  screening_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  stock_status VARCHAR(30) NOT NULL DEFAULT 'quarantine',
  storage_location VARCHAR(190) NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bb570_bag_code (bag_code),
  KEY idx_bb570_stock_live (tenant_id,bank_id,blood_group,component,stock_status,screening_status,expires_at),
  KEY idx_bb570_stock_donation (donation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_requests_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  city_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  preferred_bank_id BIGINT UNSIGNED NULL,
  requester_user_id BIGINT UNSIGNED NULL,
  request_no VARCHAR(80) NOT NULL,
  patient_name VARCHAR(190) NULL,
  hospital_name VARCHAR(190) NOT NULL,
  hospital_area VARCHAR(190) NULL,
  blood_group VARCHAR(5) NOT NULL,
  component VARCHAR(40) NOT NULL DEFAULT 'red_cells',
  units_needed SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  units_fulfilled SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  urgency VARCHAR(30) NOT NULL DEFAULT 'urgent',
  needed_at DATETIME NULL,
  contact_name VARCHAR(190) NOT NULL,
  contact_phone VARCHAR(80) NOT NULL,
  contact_email VARCHAR(190) NULL,
  address TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  clinical_note TEXT NULL,
  verification_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  request_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  is_public TINYINT(1) NOT NULL DEFAULT 0,
  verified_by BIGINT UNSIGNED NULL,
  verified_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bb570_request_no (request_no),
  KEY idx_bb570_request_queue (tenant_id,request_status,verification_status,urgency),
  KEY idx_bb570_request_bank (preferred_bank_id),
  KEY idx_bb570_request_user (requester_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_request_allocations_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  stock_batch_id BIGINT UNSIGNED NOT NULL,
  bank_id BIGINT UNSIGNED NOT NULL,
  allocation_status VARCHAR(30) NOT NULL DEFAULT 'reserved',
  allocated_by BIGINT UNSIGNED NULL,
  allocated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  issued_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bb570_allocation_batch (stock_batch_id),
  KEY idx_bb570_allocation_request (request_id,allocation_status),
  KEY idx_bb570_allocation_bank (bank_id,allocation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_camps_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  organizer VARCHAR(190) NULL,
  venue VARCHAR(190) NOT NULL,
  address TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NULL,
  capacity INT UNSIGNED NOT NULL DEFAULT 0,
  registered_count INT UNSIGNED NOT NULL DEFAULT 0,
  image_url TEXT NULL,
  description TEXT NULL,
  contact_phone VARCHAR(80) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'published',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bb570_camp_tenant_date (tenant_id,status,starts_at),
  KEY idx_bb570_camp_bank (bank_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blood_activity_v570 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  bank_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  visitor_hash CHAR(64) NULL,
  event_type VARCHAR(80) NOT NULL,
  entity_type VARCHAR(60) NULL,
  entity_id BIGINT UNSIGNED NULL,
  meta_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bb570_activity_tenant_date (tenant_id,created_at),
  KEY idx_bb570_activity_event (event_type,created_at),
  KEY idx_bb570_activity_bank (bank_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
