<?php
declare(strict_types=1);
// Auto-generated by ShahkotPK Business Importer. Do not expose or commit this file.
return ['business_importer_master_key'=>'GqkTjK67UxMe/wWI32rabDzReOqwd3xiN0ebCbhD7Ng='];
