<?php
require __DIR__.'/../app/bootstrap.php';
require_permission('logs.manage');
require_once __DIR__.'/../app/layout.php';

$view=(string)($_GET['view']??'overview');if(!in_array($view,['overview','activity','locations','logins','settings'],true))$view='overview';
$success=$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{csrf_check();$action=(string)($_POST['action']??'');
        if($action==='save_settings'){
            save_setting('activity_tracking_enabled',isset($_POST['activity_tracking_enabled'])?'1':'0');
            save_setting('activity_request_logging_enabled',isset($_POST['activity_request_logging_enabled'])?'1':'0');
            save_setting('activity_store_raw_ip',isset($_POST['activity_store_raw_ip'])?'1':'0');
            save_setting('activity_trust_cloudflare_ip',isset($_POST['activity_trust_cloudflare_ip'])?'1':'0');
            save_setting('activity_trust_forwarded_ip',isset($_POST['activity_trust_forwarded_ip'])?'1':'0');
            save_setting('ip_location_tracking_enabled',isset($_POST['ip_location_tracking_enabled'])?'1':'0');
            $provider=(string)($_POST['ip_location_provider']??'ipwhois');if(!in_array($provider,['ipwhois','disabled'],true))$provider='disabled';save_setting('ip_location_provider',$provider);
            save_setting('activity_log_retention_days',(string)max(7,min(730,(int)($_POST['activity_log_retention_days']??180))));
            save_setting('ip_location_retention_days',(string)max(7,min(730,(int)($_POST['ip_location_retention_days']??180))));
            save_setting('activity_get_throttle_seconds',(string)max(15,min(600,(int)($_POST['activity_get_throttle_seconds']??60))));
            activity_log_event('logs.settings.updated','security');$success='Log & location settings saved.';
        }elseif($action==='cleanup'){$r=activity_cleanup();$success='Cleanup complete: '.array_sum($r).' old records removed.';}
        elseif($action==='refresh_ip'){$ip=trim((string)($_POST['ip']??''));if(!filter_var($ip,FILTER_VALIDATE_IP))throw new RuntimeException('Enter a valid IP address.');activity_geolocate_ip($ip,true);$success='IP location cache refreshed.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}

$q=trim((string)($_GET['q']??''));$country=trim((string)($_GET['country']??''));$city=trim((string)($_GET['city']??''));$event=trim((string)($_GET['event']??''));$userId=(int)($_GET['user_id']??0);$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));
function logs_filter_sql(array &$params,string $alias='a'): string {global $q,$country,$city,$event,$userId,$from,$to;$w=[];if($q!==''){$w[]="({$alias}.event_name LIKE ? OR {$alias}.route LIKE ? OR {$alias}.ip_address LIKE ? OR {$alias}.city LIKE ? OR {$alias}.country LIKE ?)";$x='%'.$q.'%';array_push($params,$x,$x,$x,$x,$x);}if($country!==''){$w[]="{$alias}.country=?";$params[]=$country;}if($city!==''){$w[]="{$alias}.city=?";$params[]=$city;}if($event!==''){$w[]="{$alias}.event_name=?";$params[]=$event;}if($userId>0){$w[]="{$alias}.user_id=?";$params[]=$userId;}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)){$w[]="{$alias}.created_at>=?";$params[]=$from.' 00:00:00';}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)){$w[]="{$alias}.created_at<=?";$params[]=$to.' 23:59:59';}return $w?' WHERE '.implode(' AND ',$w):'';}

if(isset($_GET['export'])&&in_array($_GET['export'],['activity','locations'],true)){
    header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="shahkotpk-'.$_GET['export'].'-'.date('Ymd-His').'.csv"');$out=fopen('php://output','w');
    if($_GET['export']==='activity'){$p=[];$where=logs_filter_sql($p,'a');$st=db()->prepare("SELECT a.*,u.name user_name,u.email user_email FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id {$where} ORDER BY a.id DESC LIMIT 10000");$st->execute($p);fputcsv($out,['Time','User','Email','Event','Category','Route','Method','Status','IP','City','Region','Country','Timezone','ISP','Device','Browser','OS']);foreach($st as $r)fputcsv($out,[$r['created_at'],$r['user_name'],$r['user_email'],$r['event_name'],$r['event_category'],$r['route'],$r['method'],$r['status_code'],$r['ip_address'],$r['city'],$r['region_name'],$r['country'],$r['timezone_name'],$r['isp'],$r['device_type'],$r['browser_name'],$r['os_name']]);}
    else{$st=db()->query("SELECT l.*,u.name user_name,u.email user_email FROM user_location_history l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.last_seen_at DESC LIMIT 10000");fputcsv($out,['User','Email','IP','City','Region','Country','Timezone','ISP','ASN','Device','Browser','OS','First Seen','Last Seen','Visits']);foreach($st as $r)fputcsv($out,[$r['user_name'],$r['user_email'],$r['ip_address'],$r['city'],$r['region_name'],$r['country'],$r['timezone_name'],$r['isp'],$r['asn'],$r['device_type'],$r['browser_name'],$r['os_name'],$r['first_seen_at'],$r['last_seen_at'],$r['visit_count']]);}fclose($out);exit;
}

$stats=['today'=>0,'users'=>0,'ips'=>0,'countries'=>0,'failed'=>0,'locations'=>0];
try{$stats['today']=(int)db()->query("SELECT COUNT(*) FROM activity_logs WHERE created_at>=CURDATE()")->fetchColumn();$stats['users']=(int)db()->query("SELECT COUNT(DISTINCT user_id) FROM activity_logs WHERE user_id IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)")->fetchColumn();$stats['ips']=(int)db()->query("SELECT COUNT(DISTINCT ip_hash) FROM activity_logs WHERE ip_hash IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)")->fetchColumn();$stats['countries']=(int)db()->query("SELECT COUNT(DISTINCT country_code) FROM activity_logs WHERE country_code IS NOT NULL AND country_code<>'' AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)")->fetchColumn();$stats['failed']=(int)db()->query("SELECT COUNT(*) FROM activity_logs WHERE event_name='login.failed' AND created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)")->fetchColumn();$stats['locations']=(int)db()->query("SELECT COUNT(*) FROM user_location_history")->fetchColumn();}catch(Throwable $e){}
$topCities=[];$topCountries=[];$recent=[];$locations=[];$logins=[];
try{$topCities=db()->query("SELECT city,country,COUNT(*) total FROM activity_logs WHERE city IS NOT NULL AND city<>'' AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY city,country ORDER BY total DESC LIMIT 10")->fetchAll();$topCountries=db()->query("SELECT country,country_code,COUNT(*) total FROM activity_logs WHERE country IS NOT NULL AND country<>'' AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY country,country_code ORDER BY total DESC LIMIT 10")->fetchAll();}catch(Throwable $e){}
try{$p=[];$where=logs_filter_sql($p,'a');$st=db()->prepare("SELECT a.*,u.name user_name,u.email user_email FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id {$where} ORDER BY a.id DESC LIMIT 250");$st->execute($p);$recent=$st->fetchAll();}catch(Throwable $e){}
try{$st=db()->query("SELECT l.*,u.name user_name,u.email user_email FROM user_location_history l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.last_seen_at DESC LIMIT 250");$locations=$st->fetchAll();}catch(Throwable $e){}
try{$st=db()->query("SELECT e.*,u.name user_name FROM security_login_events e LEFT JOIN users u ON u.id=e.user_id ORDER BY e.id DESC LIMIT 250");$logins=$st->fetchAll();}catch(Throwable $e){}

page_start('Logs & Location History',true);
?>
<link rel="stylesheet" href="/assets/activity-logs-4.0.2.css?v=402">
<div class="loghero"><div><span class="logeyebrow">SECURITY · AUDIT · LOCATION INTELLIGENCE</span><h2>Logs & Location History</h2><p>Account activity, login security, device history and coarse IP-based city/region/country intelligence in one searchable dashboard.</p></div><div class="privacy-badge">◉ IP LOCATION<br><b>COARSE ONLY</b></div></div>
<?php if($success):?><div class="success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="error"><?=e($error)?></div><?php endif;?>
<div class="logstats"><div><b><?=number_format($stats['today'])?></b><span>Events Today</span></div><div><b><?=number_format($stats['users'])?></b><span>Users / 30d</span></div><div><b><?=number_format($stats['ips'])?></b><span>Unique IPs / 30d</span></div><div><b><?=number_format($stats['countries'])?></b><span>Countries / 30d</span></div><div class="warn"><b><?=number_format($stats['failed'])?></b><span>Failed Logins / 24h</span></div><div><b><?=number_format($stats['locations'])?></b><span>Location Snapshots</span></div></div>
<nav class="logtabs"><a class="<?=$view==='overview'?'active':''?>" href="?view=overview">Overview</a><a class="<?=$view==='activity'?'active':''?>" href="?view=activity">Activity Logs</a><a class="<?=$view==='locations'?'active':''?>" href="?view=locations">Location History</a><a class="<?=$view==='logins'?'active':''?>" href="?view=logins">Login Security</a><a class="<?=$view==='settings'?'active':''?>" href="?view=settings">Settings & Privacy</a></nav>
<?php if($view==='overview'):?>
<div class="loggrid"><section class="card"><h3>Recent Account Activity</h3><div class="loglist"><?php foreach(array_slice($recent,0,12) as $r):?><div class="logitem"><span class="logdot"></span><div><b><?=e($r['event_name'])?></b><small><?=e($r['user_name']?:'Guest/Security')?> · <?=e($r['route']?:'-')?></small></div><div class="logwhere"><?=e(trim(($r['city']?:'').(($r['city']&&$r['country'])?', ':'').($r['country']?:''))?:'Location unavailable')?><small><?=e($r['created_at'])?></small></div></div><?php endforeach;?></div></section>
<section class="card"><h3>Top Cities · 30 Days</h3><?php foreach($topCities as $r):?><div class="barrow"><span><?=e($r['city'])?><?=!empty($r['country'])?' · '.e($r['country']):''?></span><b><?=number_format((int)$r['total'])?></b></div><?php endforeach;?><?php if(!$topCities):?><p class="muted">City estimates will appear after public-IP account activity is recorded.</p><?php endif;?></section>
<section class="card"><h3>Top Countries · 30 Days</h3><?php foreach($topCountries as $r):?><div class="barrow"><span><?=e($r['country'])?> <small><?=e($r['country_code'])?></small></span><b><?=number_format((int)$r['total'])?></b></div><?php endforeach;?></section>
<section class="card privacy-card"><h3>Privacy Boundary</h3><p><b>No silent GPS tracking.</b> This module estimates city/region/country from the connection IP. It does not use <code>navigator.geolocation</code>, GPS, Wi‑Fi positioning or background device location without explicit browser permission.</p><p>Use your Privacy Policy to disclose IP/security logging and set an appropriate retention period.</p></section></div>
<?php elseif($view==='activity'):?>
<form class="card filterbar" method="get"><input type="hidden" name="view" value="activity"><input name="q" value="<?=e($q)?>" placeholder="Search event, route, IP, city..."><input name="event" value="<?=e($event)?>" placeholder="Event name"><input name="city" value="<?=e($city)?>" placeholder="City"><input name="country" value="<?=e($country)?>" placeholder="Country"><input type="date" name="from" value="<?=e($from)?>"><input type="date" name="to" value="<?=e($to)?>"><button class="btn">Filter</button><a class="btn secondary" href="?view=activity&export=activity">Export CSV</a></form>
<div class="card tablewrap"><table><thead><tr><th>Time</th><th>User</th><th>Event</th><th>Route</th><th>IP / Location</th><th>Device</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=e($r['created_at'])?></td><td><b><?=e($r['user_name']?:'—')?></b><small><?=e($r['user_email']?:'')?></small></td><td><span class="pill"><?=e($r['event_name'])?></span><small><?=e($r['event_category'])?></small></td><td><?=e($r['method'])?> · <?=e($r['route'])?><small><?=e($r['module'])?> · <?=number_format((int)($r['duration_ms']??0))?> ms</small></td><td><code><?=e($r['ip_address']?:'hidden')?></code><small><?=e(trim(($r['city']?:'').', '.($r['region_name']?:'').', '.($r['country']?:''),', '))?></small></td><td><?=e($r['device_type'])?><small><?=e($r['browser_name'].' · '.$r['os_name'])?></small></td><td><span class="status s<?=e((string)$r['status_code'])?>"><?=e($r['status_code'])?></span></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($view==='locations'):?>
<div class="card location-head"><div><h3>User Location History</h3><p>IP-based approximate location snapshots. Same user/IP/city is merged and visit count increases.</p></div><a class="btn" href="?view=locations&export=locations">Export CSV</a></div>
<div class="location-cards"><?php foreach($locations as $r):?><article class="loccard"><div class="locicon">⌖</div><div class="locbody"><h4><?=e($r['user_name']?:'User #'.$r['user_id'])?></h4><p><?=e(trim(($r['city']?:'Unknown city').', '.($r['region_name']?:'').', '.($r['country']?:''),', '))?></p><div class="locmeta"><span>IP <code><?=e($r['ip_address']?:'hidden')?></code></span><span><?=e($r['timezone_name']?:'Timezone n/a')?></span><span><?=e($r['isp']?:'ISP n/a')?></span><span><?=e($r['device_type'].' · '.$r['browser_name'].' · '.$r['os_name'])?></span></div><small>First <?=e($r['first_seen_at'])?> · Last <?=e($r['last_seen_at'])?> · <?=number_format((int)$r['visit_count'])?> visits</small></div></article><?php endforeach;?><?php if(!$locations):?><div class="card muted">No location history yet.</div><?php endif;?></div>
<?php elseif($view==='logins'):?>
<div class="card tablewrap"><table><thead><tr><th>Time</th><th>User / Identifier</th><th>Source</th><th>IP</th><th>Result</th><th>Reason</th></tr></thead><tbody><?php foreach($logins as $r):?><tr><td><?=e($r['created_at'])?></td><td><b><?=e($r['user_name']?:$r['login_identifier']?:'Unknown')?></b></td><td><?=e($r['source'])?></td><td><code><?=e($r['ip_address']?:'—')?></code></td><td><?=$r['success']?'<span class="ok">SUCCESS</span>':'<span class="bad">FAILED</span>'?></td><td><?=e($r['failure_reason']?:'—')?></td></tr><?php endforeach;?></tbody></table></div>
<?php else:?>
<div class="settings-grid"><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_settings"><h3>Logging & IP Location</h3><label class="switchrow"><input type="checkbox" name="activity_tracking_enabled" <?=setting_bool('activity_tracking_enabled',true)?'checked':''?>><span>Enable account/security activity logging</span></label><label class="switchrow"><input type="checkbox" name="activity_request_logging_enabled" <?=setting_bool('activity_request_logging_enabled',true)?'checked':''?>><span>Log authenticated page/request activity</span></label><label class="switchrow"><input type="checkbox" name="ip_location_tracking_enabled" <?=setting_bool('ip_location_tracking_enabled',true)?'checked':''?>><span>Resolve coarse IP location automatically</span></label><label>Location provider<select name="ip_location_provider"><option value="ipwhois" <?=setting('ip_location_provider','ipwhois')==='ipwhois'?'selected':''?>>ipwho.is (HTTPS)</option><option value="disabled" <?=setting('ip_location_provider','')==='disabled'?'selected':''?>>Disabled</option></select></label><label class="switchrow"><input type="checkbox" name="activity_store_raw_ip" <?=setting_bool('activity_store_raw_ip',true)?'checked':''?>><span>Store raw IP in security logs</span></label><label>Activity retention days<input type="number" min="7" max="730" name="activity_log_retention_days" value="<?=e(setting_int('activity_log_retention_days',180))?>"></label><label>Location retention days<input type="number" min="7" max="730" name="ip_location_retention_days" value="<?=e(setting_int('ip_location_retention_days',180))?>"></label><label>Repeat GET log throttle (seconds)<input type="number" min="15" max="600" name="activity_get_throttle_seconds" value="<?=e(setting_int('activity_get_throttle_seconds',60))?>"></label><h4>Reverse proxy</h4><label class="switchrow"><input type="checkbox" name="activity_trust_cloudflare_ip" <?=setting_bool('activity_trust_cloudflare_ip',false)?'checked':''?>><span>Trust Cloudflare CF-Connecting-IP</span></label><label class="switchrow"><input type="checkbox" name="activity_trust_forwarded_ip" <?=setting_bool('activity_trust_forwarded_ip',false)?'checked':''?>><span>Trust X-Forwarded-For first IP (only behind trusted proxy)</span></label><button class="btn">Save Settings</button></form>
<div><section class="card privacy-card"><h3>What this tracks</h3><p>IP address (optional raw storage), approximate city/region/country, timezone, ISP/ASN, browser, OS, device class, login outcomes, authenticated routes and admin/account actions.</p><h3>What this does not track</h3><p>Exact GPS coordinates, continuous background device location, Wi‑Fi SSIDs, contacts, photos or microphone/camera data.</p></section><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="cleanup"><h3>Retention Cleanup</h3><p>Remove records older than configured retention limits now.</p><button class="btn secondary">Run Cleanup</button></form></div></div>
<?php endif;?>
<?php require __DIR__.'/../app/end.php';?>
