<?php
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
$me=current_user();
if(!$me || !(has_permission('settings.manage',$me)||has_permission('updates.manage',$me)||has_permission('tenants.manage',$me))){http_response_code(403);exit('Forbidden');}
require_once __DIR__.'/../app/admin_tools_lock_v975.php';sk975_admin_tools_gate($me);
require_once __DIR__.'/../app/backup_restore_v990.php';
$uid=(int)$me['id'];$flash='';$error='';$result=null;
try{
 if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
  csrf_check();$action=(string)($_POST['action']??'');
  if($action==='create'){$result=sk990_create_snapshot('manual',!empty($_POST['db']),!empty($_POST['files']),!empty($_POST['uploads']),$uid,!empty($_POST['remote']));$flash='Backup snapshot created successfully.';}
  elseif($action==='verify'){$result=sk990_verify_snapshot((int)$_POST['id']);$flash=$result['ok']?'Backup verification passed.':'Backup verification found a problem.';}
  elseif($action==='remote'){$result=sk990_send_snapshot_remote((int)$_POST['id'],$uid);$flash=$result?'Backup copied to remote storage.':'No enabled Storage Center backup route is configured.';}
  elseif($action==='delete'){if((string)($_POST['confirm']??'')!=='DELETE BACKUP')throw new RuntimeException('Type DELETE BACKUP to confirm.');$result=sk990_delete_snapshot((int)$_POST['id'],$uid);$flash='Backup snapshot deleted.';}
  elseif($action==='restore_db'){if((string)($_POST['confirm']??'')!=='RESTORE DATABASE')throw new RuntimeException('Type RESTORE DATABASE to confirm.');$result=sk990_restore_database((int)$_POST['id'],$uid);$flash='Database restore completed. A safety snapshot was created first.';}
  elseif($action==='restore_files'){if((string)($_POST['confirm']??'')!=='RESTORE FILES')throw new RuntimeException('Type RESTORE FILES to confirm.');$result=sk990_restore_files((int)$_POST['id'],$uid);$flash='File rollback completed. A safety snapshot was created first.';}
  elseif($action==='save_schedule'){$freq=in_array($_POST['frequency']??'daily',['daily','weekly'],true)?$_POST['frequency']:'daily';sk990_save_setting('backup_schedule_enabled_v990',!empty($_POST['enabled'])?'1':'0');sk990_save_setting('backup_schedule_frequency_v990',$freq);sk990_save_setting('backup_schedule_files_v990',!empty($_POST['include_files'])?'1':'0');sk990_save_setting('backup_schedule_uploads_v990',!empty($_POST['include_uploads'])?'1':'0');sk990_save_setting('backup_schedule_remote_v990',!empty($_POST['remote'])?'1':'0');sk990_save_setting('backup_retention_days_v990',(string)max(1,min(365,(int)($_POST['retention_days']??30))));sk990_save_setting('backup_retention_count_v990',(string)max(1,min(100,(int)($_POST['retention_count']??10))));$flash='Backup schedule and retention settings saved.';}
  elseif($action==='run_scheduled'){$result=sk990_create_snapshot('scheduled-manual',true,true,false,$uid,true);sk990_save_setting('backup_schedule_last_run_v990',date('Y-m-d H:i:s'));$flash='Scheduled-style backup run completed.';}
  elseif($action==='cleanup'){$result=sk990_cleanup_retention($uid);$flash='Retention cleanup completed.';}
  elseif($action==='install_hook'){if((string)($_POST['confirm']??'')!=='ENABLE ROLLBACK')throw new RuntimeException('Type ENABLE ROLLBACK to confirm.');$result=sk990_install_update_hook();$flash='Pre-update restore-point hook enabled.';}
  elseif($action==='uninstall_hook'){$result=sk990_uninstall_update_hook();$flash='Pre-update restore-point hook removed/restored from backup where available.';}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$snapshots=sk990_snapshots(80);$schedule=sk990_schedule_settings();$hook=sk990_update_hook_installed();$backupDir=sk990_backup_root();
$total=0;foreach($snapshots as $s)$total+=(int)$s['db_bytes']+(int)$s['files_bytes'];
page_start('Backup, Restore & Rollback',true);
?>
<link rel="stylesheet" href="/assets/admin-backup-v990.css?v=990">
<script defer src="/assets/admin-backup-v990.js?v=990"></script>
<div class="sk990-wrap">
<section class="sk990-hero"><div><small>SHAHKOTPK v9.9.0</small><h2>Backup, Restore & Rollback Center</h2><p>Create verified restore points before risky changes, back up database/project files, send copies through Storage Control, and restore with an automatic safety snapshot first.</p></div><div class="sk990-stat"><b><?=count($snapshots)?></b><span>restore points</span><strong><?=e(sk990_fmt_bytes($total))?></strong></div></section>
<?php if($flash):?><div class="sk990-alert ok"><?=e($flash)?></div><?php endif;?><?php if($error):?><div class="sk990-alert bad"><?=e($error)?></div><?php endif;?>
<section class="sk990-grid sk990-top">
<article class="sk990-card"><h3>Create restore point</h3><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><label><input type="checkbox" name="db" value="1" checked> Database</label><label><input type="checkbox" name="files" value="1" checked> Project code/config/assets</label><label><input type="checkbox" name="uploads" value="1"> Include uploads (can be large)</label><label><input type="checkbox" name="remote" value="1" checked> Copy to configured remote backup route</label><button class="primary">Create Backup Now</button></form></article>
<article class="sk990-card"><h3>Updater rollback protection</h3><p class="muted">Status: <b class="<?= $hook?'good':'warn' ?>"><?= $hook?'Enabled':'Not enabled' ?></b>. When enabled, POST requests to the admin updater create one database + code restore point before the update, rate-limited to one per 15 minutes.</p><?php if(!$hook):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="install_hook"><input name="confirm" placeholder="Type ENABLE ROLLBACK" required><button>Enable Pre-Update Restore Point</button></form><?php else:?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="uninstall_hook"><button class="ghost">Disable Hook</button></form><?php endif;?></article>
</section>
<section class="sk990-card"><div class="head"><div><small>SCHEDULE</small><h3>Automatic backups & retention</h3></div><code><?=e(PHP_BINARY?:'php')?> <?=e(sk990_root().'/cron/backup-v990.php')?></code></div><form method="post" class="schedule"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_schedule"><label><input type="checkbox" name="enabled" value="1" <?=$schedule['enabled']?'checked':''?>> Enable scheduled backups</label><label>Frequency<select name="frequency"><option value="daily" <?=$schedule['frequency']==='daily'?'selected':''?>>Daily</option><option value="weekly" <?=$schedule['frequency']==='weekly'?'selected':''?>>Weekly</option></select></label><label><input type="checkbox" name="include_files" value="1" <?=$schedule['include_files']?'checked':''?>> Include project files</label><label><input type="checkbox" name="include_uploads" value="1" <?=$schedule['include_uploads']?'checked':''?>> Include uploads</label><label><input type="checkbox" name="remote" value="1" <?=$schedule['remote']?'checked':''?>> Remote copy</label><label>Retention days<input type="number" name="retention_days" min="1" max="365" value="<?=e(sk990_setting('backup_retention_days_v990','30'))?>"></label><label>Minimum copies<input type="number" name="retention_count" min="1" max="100" value="<?=e(sk990_setting('backup_retention_count_v990','10'))?>"></label><button>Save Schedule</button></form><div class="inline"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="run_scheduled"><button class="ghost">Run Backup Now</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="cleanup"><button class="ghost">Apply Retention Cleanup</button></form><span>Last scheduled run: <?=e($schedule['last_run']?:'Never')?></span></div></section>
<section class="sk990-card"><div class="head"><div><small>RESTORE POINTS</small><h3>Backup history</h3></div><span><?=e($backupDir)?></span></div><div class="table-wrap"><table><thead><tr><th>ID / Type</th><th>Version</th><th>Database</th><th>Files</th><th>Remote</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php if(!$snapshots):?><tr><td colspan="7">No restore point yet.</td></tr><?php endif;?><?php foreach($snapshots as $s):?><tr><td><b>#<?=(int)$s['id']?></b><small><?=e((string)$s['snapshot_type'])?> · <?=e((string)$s['status'])?></small></td><td><?=e((string)$s['app_version'])?></td><td><?=!empty($s['db_path'])?e(sk990_fmt_bytes((int)$s['db_bytes'])):'—'?></td><td><?=!empty($s['files_path'])?e(sk990_fmt_bytes((int)$s['files_bytes'])):'—'?></td><td><?=e((string)($s['remote_status']?:'local'))?></td><td><?=e((string)$s['created_at'])?></td><td class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="verify"><input type="hidden" name="id" value="<?=(int)$s['id']?>"><button class="mini">Verify</button></form><?php if(!empty($s['db_path'])):?><button class="mini warn js-restore" data-id="<?=(int)$s['id']?>" data-kind="db">Restore DB</button><?php endif;?><?php if(!empty($s['files_path'])):?><button class="mini warn js-restore" data-id="<?=(int)$s['id']?>" data-kind="files">Rollback Files</button><?php endif;?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="remote"><input type="hidden" name="id" value="<?=(int)$s['id']?>"><button class="mini">Remote Copy</button></form><button class="mini danger js-delete" data-id="<?=(int)$s['id']?>">Delete</button></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if($result!==null):?><section class="sk990-card"><h3>Last operation</h3><pre><?=e(json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></section><?php endif;?>
</div>
<div id="sk990-modal" class="sk990-modal" hidden><div class="box"><h3 id="sk990-modal-title">Confirm</h3><p id="sk990-modal-text"></p><form method="post" id="sk990-modal-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" id="sk990-action"><input type="hidden" name="id" id="sk990-id"><input name="confirm" id="sk990-confirm" autocomplete="off" required><div><button type="button" id="sk990-cancel" class="ghost">Cancel</button><button class="danger">Confirm</button></div></form></div></div>
<?php require __DIR__.'/../app/end.php'; ?>