<?php
require __DIR__.'/../app/bootstrap.php';require_permission('banners.manage');require __DIR__.'/../app/homepage.php';require __DIR__.'/../app/banners.php';
$success=$error=null;$slides=banner_slides();
if($_SERVER['REQUEST_METHOD']==='POST'){try{csrf_check();$action=$_POST['action']??'save';if($action==='delete'){$id=$_POST['id']??'';$slides=array_values(array_filter($slides,fn($s)=>($s['id']??'')!==$id));save_banner_slides($slides);$success='Banner deleted.';}elseif($action==='duplicate'){$id=$_POST['id']??'';foreach($slides as $s)if(($s['id']??'')===$id){$s['id']='banner_'.bin2hex(random_bytes(4));$s['title'].=' Copy';$s['order']=(int)$s['order']+5;$slides[]=$s;break;}save_banner_slides($slides);$success='Banner duplicated.';}else{$id=trim($_POST['id']??'')?:'banner_'.bin2hex(random_bytes(4));$slide=['id'=>$id,'enabled'=>isset($_POST['enabled'])?1:0,'order'=>(int)($_POST['order']??10),'title'=>trim($_POST['title']??''),'subtitle'=>trim($_POST['subtitle']??''),'text'=>trim($_POST['text']??''),'button_text'=>trim($_POST['button_text']??''),'button_url'=>trim($_POST['button_url']??''),'image'=>trim($_POST['image']??'')];if(!$slide['title'])throw new RuntimeException('Title required.');if(isset($_FILES['banner_image'])){$u=upload_homepage_image($_FILES['banner_image']);if($u)$slide['image']=$u;}$found=false;foreach($slides as $i=>$x)if(($x['id']??'')===$id){$slides[$i]=$slide;$found=true;break;}if(!$found)$slides[]=$slide;save_banner_slides($slides);$success='Banner saved.';}$slides=banner_slides();}catch(Throwable $e){$error=$e->getMessage();}}
$edit=null;if(isset($_GET['edit']))foreach($slides as $s)if(($s['id']??'')===$_GET['edit']){$edit=$s;break;}require __DIR__.'/../app/layout.php';page_start('Banner Manager',true);
?>
<div class="admin-page-hero"><h2>Banner Manager</h2><p>Premium slider management with image upload, CTA, duplicate, ordering and visual cards.</p></div><?php if($success):?><div class="success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="error"><?=e($error)?></div><?php endif;?>
<div class="admin-split"><div class="card"><h3><?=$edit?'Edit Banner':'Create Banner'?></h3><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e($edit['id']??'')?>"><div class="admin-form-grid"><div><label>Order</label><input class="input" type="number" name="order" value="<?=e($edit['order']??10)?>"></div><div><label>Active</label><label class="switch"><input type="checkbox" name="enabled" <?=($edit['enabled']??1)?'checked':''?>><span class="slider"></span></label></div><div class="full"><label>Title</label><input class="input" name="title" value="<?=e($edit['title']??'')?>" required></div><div class="full"><label>Subtitle</label><input class="input" name="subtitle" value="<?=e($edit['subtitle']??'')?>"></div><div class="full"><label>Description</label><textarea class="input" rows="4" name="text"><?=e($edit['text']??'')?></textarea></div><div><label>Button Text</label><input class="input" name="button_text" value="<?=e($edit['button_text']??'Explore')?>"></div><div><label>Button URL</label><input class="input" name="button_url" value="<?=e($edit['button_url']??'/search.php')?>"></div><div class="full"><label>Image URL</label><input class="input" name="image" value="<?=e($edit['image']??'')?>"></div><div class="full"><label>Upload Image</label><input class="input" type="file" name="banner_image"></div></div><br><button class="btn">Save Banner</button></form></div>
<div><div class="admin-toolbar"><a class="btn ghost" href="/" target="_blank">Preview ↗</a><span class="muted"><?=count($slides)?> slides</span></div><div class="v2-banner-grid"><?php foreach($slides as $s):?><div class="v2-banner-card"><div class="v2-banner-cover" <?=$s['image']?'style="background-image:url(\''.e($s['image']).'\')"':''?>></div><div class="v2-banner-body"><span class="badge <?=$s['enabled']?'success':'slate'?>"><?=$s['enabled']?'Active':'Hidden'?></span><h3><?=e($s['title'])?></h3><p class="muted"><?=e($s['subtitle'])?></p><div class="admin-toolbar"><a class="btn ghost" href="?edit=<?=urlencode($s['id'])?>">Edit</a><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="duplicate"><input type="hidden" name="id" value="<?=e($s['id'])?>"><button class="btn ghost">Duplicate</button></form><form method="post" onsubmit="return confirm('Delete banner?')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($s['id'])?>"><button class="btn danger">Delete</button></form></div></div></div><?php endforeach;?></div></div></div>
<?php require __DIR__.'/../app/end.php';?>
