<?php
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
require_once __DIR__.'/../app/customer_utility_v1030.php';
$me=current_user();
if(!$me || !(has_permission('settings.manage',$me)||has_permission('tenants.manage',$me)||has_permission('updates.manage',$me))){http_response_code(403);exit('Forbidden');}
$uid=(int)$me['id'];$tid=sk1030_tid();$flash='';$error='';
try{
 if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
  csrf_check();$a=(string)($_POST['action']??'');
  if($a==='settings'){
   $keys=['hub','smart_request','price_compare','nearby','daily_cards','emergency','reminders','lost_found','homepage_section'];
   $vals=[];foreach($keys as $k)$vals[$k.'_enabled']=!empty($_POST[$k.'_enabled'])?1:0;
   $q=db()->prepare('INSERT INTO customer_utility_settings_v1030(tenant_id,hub_enabled,smart_request_enabled,price_compare_enabled,nearby_enabled,daily_cards_enabled,emergency_enabled,reminders_enabled,lost_found_enabled,homepage_section_enabled,requests_per_hour,offers_per_request,nearby_radius_km,request_auto_route_limit,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE hub_enabled=VALUES(hub_enabled),smart_request_enabled=VALUES(smart_request_enabled),price_compare_enabled=VALUES(price_compare_enabled),nearby_enabled=VALUES(nearby_enabled),daily_cards_enabled=VALUES(daily_cards_enabled),emergency_enabled=VALUES(emergency_enabled),reminders_enabled=VALUES(reminders_enabled),lost_found_enabled=VALUES(lost_found_enabled),homepage_section_enabled=VALUES(homepage_section_enabled),requests_per_hour=VALUES(requests_per_hour),offers_per_request=VALUES(offers_per_request),nearby_radius_km=VALUES(nearby_radius_km),request_auto_route_limit=VALUES(request_auto_route_limit),updated_by=VALUES(updated_by),updated_at=NOW()');
   $q->execute([$tid,$vals['hub_enabled'],$vals['smart_request_enabled'],$vals['price_compare_enabled'],$vals['nearby_enabled'],$vals['daily_cards_enabled'],$vals['emergency_enabled'],$vals['reminders_enabled'],$vals['lost_found_enabled'],$vals['homepage_section_enabled'],max(1,min(30,(int)($_POST['requests_per_hour']??5))),max(1,min(30,(int)($_POST['offers_per_request']??8))),max(1,min(100,(float)($_POST['nearby_radius_km']??20))),max(1,min(12,(int)($_POST['request_auto_route_limit']??5))),$uid]);
   if(sk1030_table_exists('homepage_sections_v1010'))db()->prepare("UPDATE homepage_sections_v1010 SET enabled=? WHERE tenant_id=? AND section_key='daily_utility'")->execute([$vals['homepage_section_enabled'],$tid]);
   $flash='Customer Utility settings saved.';
  }elseif($a==='daily_add'){
   $q=db()->prepare('INSERT INTO customer_daily_cards_v1030(tenant_id,card_key,icon,title,value_text,subtitle,source_label,source_url,target_url,sort_order,enabled,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,NOW(),NOW())');
   $q->execute([$tid,substr(preg_replace('/[^a-z0-9_.-]/i','',(string)($_POST['card_key']??'info')),0,90),mb_substr((string)($_POST['icon']??'•'),0,16),mb_substr(trim((string)($_POST['title']??'')),0,120),mb_substr(trim((string)($_POST['value_text']??'')),0,190),mb_substr(trim((string)($_POST['subtitle']??'')),0,255),mb_substr(trim((string)($_POST['source_label']??'')),0,120),mb_substr(trim((string)($_POST['source_url']??'')),0,500),mb_substr(trim((string)($_POST['target_url']??'')),0,500),(int)($_POST['sort_order']??100),$uid]);$flash='Daily information card added.';
  }elseif($a==='daily_delete'){
   db()->prepare('DELETE FROM customer_daily_cards_v1030 WHERE tenant_id=? AND id=?')->execute([$tid,(int)($_POST['id']??0)]);$flash='Daily card deleted.';
  }elseif($a==='emergency_add'){
   $label=trim((string)($_POST['label']??''));$phone=trim((string)($_POST['phone']??''));if($label===''||$phone==='')throw new InvalidArgumentException('Emergency label and phone are required.');
   $q=db()->prepare('INSERT INTO customer_emergency_contacts_v1030(tenant_id,category_key,icon,label,phone,whatsapp,address,note,sort_order,enabled,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,NOW(),NOW())');$q->execute([$tid,mb_substr((string)($_POST['category_key']??'emergency'),0,60),mb_substr((string)($_POST['icon']??'☎'),0,16),mb_substr($label,0,140),mb_substr($phone,0,50),mb_substr(trim((string)($_POST['whatsapp']??'')),0,50),mb_substr(trim((string)($_POST['address']??'')),0,255),mb_substr(trim((string)($_POST['note']??'')),0,255),(int)($_POST['sort_order']??100),$uid]);$flash='Emergency contact added.';
  }elseif($a==='emergency_delete'){
   db()->prepare('DELETE FROM customer_emergency_contacts_v1030 WHERE tenant_id=? AND id=?')->execute([$tid,(int)($_POST['id']??0)]);$flash='Emergency contact deleted.';
  }elseif($a==='request_status'){
   $st=in_array((string)($_POST['status']??''),['open','in_progress','fulfilled','closed','rejected'],true)?(string)$_POST['status']:'open';db()->prepare('UPDATE customer_service_requests_v1030 SET status=?,updated_at=NOW() WHERE tenant_id=? AND id=?')->execute([$st,$tid,(int)($_POST['id']??0)]);$flash='Request status updated.';
  }elseif($a==='reroute'){
   $id=(int)($_POST['id']??0);$q=db()->prepare('SELECT category_key,need_text FROM customer_service_requests_v1030 WHERE tenant_id=? AND id=? LIMIT 1');$q->execute([$tid,$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('Request not found.');$n=sk1030_auto_route($id,(string)$r['category_key'],(string)$r['need_text']);$flash='Auto-routing completed: '.$n.' new business route(s).';
  }elseif($a==='lost_moderate'){
   $st=in_array((string)($_POST['status']??''),['approved','rejected','resolved'],true)?(string)$_POST['status']:'rejected';db()->prepare('UPDATE customer_lost_found_v1030 SET status=?,moderated_by=?,moderated_at=NOW(),updated_at=NOW() WHERE tenant_id=? AND id=?')->execute([$st,$uid,$tid,(int)($_POST['id']??0)]);$flash='Lost & Found item updated.';
  }
 }
}catch(Throwable $e){$error=$e->getMessage();}
$cfg=sk1030_settings(true);$stats=sk1030_stats();$daily=sk1030_daily_cards(50);$emergency=sk1030_emergency(50);$requests=[];$lost=[];
try{$q=db()->prepare("SELECT r.*,(SELECT COUNT(*) FROM customer_request_routes_v1030 rr WHERE rr.request_id=r.id) route_count,(SELECT COUNT(*) FROM customer_request_offers_v1030 o WHERE o.request_id=r.id AND o.status='active') offer_count FROM customer_service_requests_v1030 r WHERE r.tenant_id=? ORDER BY r.id DESC LIMIT 60");$q->execute([$tid]);$requests=$q->fetchAll()?:[];}catch(Throwable $e){}
try{$q=db()->prepare("SELECT * FROM customer_lost_found_v1030 WHERE tenant_id=? ORDER BY (status='pending') DESC,id DESC LIMIT 40");$q->execute([$tid]);$lost=$q->fetchAll()?:[];}catch(Throwable $e){}
page_start('Customer Utility Hub',true);
?><link rel="stylesheet" href="/assets/admin-customer-utility-v1030.css?v=1030"><div class="cu-admin"><section class="cu-hero"><div><span>SHAHKOTPK v10.3.0 · CUSTOMER & SERVICES</span><h2>Customer Utility & Local Services Hub</h2><p>Turn ShahkotPK into a daily-use city platform: smart customer requests, nearby help, price comparison, emergency shortcuts, utility reminders and local information.</p></div><a class="cu-btn" href="/my-shahkot.php" target="_blank">Open My Shahkot ↗</a></section><?php if($flash):?><div class="cu-alert ok"><?=e($flash)?></div><?php endif;?><?php if($error):?><div class="cu-alert bad"><?=e($error)?></div><?php endif;?><div class="cu-stats"><article><small>OPEN REQUESTS</small><b><?=number_format($stats['open_requests'])?></b></article><article><small>ACTIVE OFFERS</small><b><?=number_format($stats['offers'])?></b></article><article><small>SAVED REMINDERS</small><b><?=number_format($stats['reminders'])?></b></article><article><small>LOST/FOUND PENDING</small><b><?=number_format($stats['pending_lost_found'])?></b></article></div>
<section class="cu-card"><h3>Feature controls</h3><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="settings"><div class="cu-toggles"><?php foreach(['hub','smart_request','price_compare','nearby','daily_cards','emergency','reminders','lost_found','homepage_section'] as $k):?><label><input type="checkbox" name="<?=$k?>_enabled" value="1" <?=!empty($cfg[$k.'_enabled'])?'checked':''?>> <?=e(ucwords(str_replace('_',' ',$k)))?></label><?php endforeach;?></div><div class="cu-form"><label>Requests / hour<input type="number" name="requests_per_hour" min="1" max="30" value="<?=(int)$cfg['requests_per_hour']?>"></label><label>Offers / request<input type="number" name="offers_per_request" min="1" max="30" value="<?=(int)$cfg['offers_per_request']?>"></label><label>Nearby radius km<input type="number" name="nearby_radius_km" min="1" max="100" step="1" value="<?=e((string)$cfg['nearby_radius_km'])?>"></label><label>Auto route businesses<input type="number" name="request_auto_route_limit" min="1" max="12" value="<?=(int)$cfg['request_auto_route_limit']?>"></label></div><button class="cu-btn">Save Settings</button></form></section>
<div class="cu-grid"><section class="cu-card"><h3>Daily information cards</h3><form method="post" class="cu-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="daily_add"><label>Key<input name="card_key" placeholder="fuel_price"></label><label>Icon<input name="icon" value="•"></label><label>Title<input name="title" required placeholder="Petrol Price"></label><label>Value<input name="value_text" required placeholder="PKR ..."></label><label class="wide">Subtitle<input name="subtitle" placeholder="Updated today"></label><label>Source label<input name="source_label"></label><label>Source URL<input name="source_url"></label><label>Target URL<input name="target_url"></label><label>Order<input type="number" name="sort_order" value="100"></label><div class="wide"><button class="cu-btn">Add Card</button></div></form><?php foreach($daily as $x):?><div class="cu-row"><div><b><?=e((string)$x['icon'])?> <?=e((string)$x['title'])?></b><small><?=e((string)$x['value_text'])?> · <?=e((string)($x['subtitle']??''))?></small></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="daily_delete"><input type="hidden" name="id" value="<?=(int)$x['id']?>"><button class="cu-link danger">Delete</button></form></div><?php endforeach;?></section>
<section class="cu-card"><h3>Emergency & useful contacts</h3><form method="post" class="cu-form"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="emergency_add"><label>Category<input name="category_key" value="emergency"></label><label>Icon<input name="icon" value="☎"></label><label>Label<input name="label" required></label><label>Phone<input name="phone" required></label><label>WhatsApp<input name="whatsapp"></label><label>Order<input type="number" name="sort_order" value="100"></label><label class="wide">Address<input name="address"></label><label class="wide">Note<input name="note"></label><div class="wide"><button class="cu-btn">Add Contact</button></div></form><?php foreach($emergency as $x):?><div class="cu-row"><div><b><?=e((string)$x['icon'])?> <?=e((string)$x['label'])?></b><small><?=e((string)$x['phone'])?> · <?=e((string)($x['address']??''))?></small></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="emergency_delete"><input type="hidden" name="id" value="<?=(int)$x['id']?>"><button class="cu-link danger">Delete</button></form></div><?php endforeach;?></section></div>
<section class="cu-card"><div class="cu-head"><div><small>SMART REQUESTS</small><h3>Customer needs & business routing</h3></div><a href="/service-leads-v1030.php" target="_blank">Business Leads Portal ↗</a></div><div class="cu-table-wrap"><table><thead><tr><th>Request</th><th>Customer</th><th>Budget</th><th>Routes / Offers</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($requests as $r):?><tr><td><b>#<?=(int)$r['id']?> · <?=e((string)$r['category_key'])?></b><small><?=e(mb_strimwidth((string)$r['need_text'],0,120,'…'))?> · <?=e((string)($r['area']??''))?></small></td><td><?=e((string)$r['contact_name'])?><small><?=e((string)$r['contact_phone'])?></small></td><td><?=((float)$r['budget_min']>0?'PKR '.number_format((float)$r['budget_min']):'—')?><?php if((float)$r['budget_max']>0):?><small>to <?=number_format((float)$r['budget_max'])?></small><?php endif;?></td><td><?=(int)$r['route_count']?> / <?=(int)$r['offer_count']?></td><td><?=e((string)$r['status'])?></td><td><form method="post" class="cu-inline"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button name="action" value="reroute" class="cu-link">Auto Route</button><select name="status"><?php foreach(['open','in_progress','fulfilled','closed','rejected'] as $st):?><option <?=$st===$r['status']?'selected':''?>><?=$st?></option><?php endforeach;?></select><button name="action" value="request_status" class="cu-link">Save</button></form></td></tr><?php endforeach;?><?php if(!$requests):?><tr><td colspan="6">No customer requests yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="cu-card"><h3>Lost & Found moderation</h3><?php foreach($lost as $x):?><div class="cu-row"><div><b><?=e(strtoupper((string)$x['item_type']))?> · <?=e((string)$x['title'])?></b><small><?=e(mb_strimwidth((string)$x['description'],0,140,'…'))?> · <?=e((string)($x['area']??''))?> · <?=e((string)$x['status'])?></small></div><form method="post" class="cu-inline"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="lost_moderate"><input type="hidden" name="id" value="<?=(int)$x['id']?>"><button name="status" value="approved" class="cu-link">Approve</button><button name="status" value="resolved" class="cu-link">Resolve</button><button name="status" value="rejected" class="cu-link danger">Reject</button></form></div><?php endforeach;?><?php if(!$lost):?><p class="muted">No Lost & Found posts yet.</p><?php endif;?></section>
<section class="cu-card"><h3>Reminder worker</h3><p>Run once daily from Cron Manager to create customer bill/utility reminders:</p><code>php <?=e(dirname(__DIR__).'/cron/customer-utility-v1030.php')?></code></section></div><?php require __DIR__.'/../app/end.php';?>
