<?php
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
require_once __DIR__.'/../app/admin_database_v960.php';
$me=current_user();
if(!$me || !(has_permission('settings.manage',$me)||has_permission('updates.manage',$me)||has_permission('tenants.manage',$me))){http_response_code(403);exit('Forbidden');}
require_once __DIR__.'/../app/admin_tools_lock_v975.php';
sk975_admin_tools_gate($me);
require_once __DIR__.'/../app/admin_sidebar_installer_v974.php';
$sk974SidebarInstall=shahkotpk_install_admin_sidebar_v974();
$uid=(int)$me['id'];$super=sk960_is_super_admin($me);$flash='';$error='';$result=null;

if(isset($_GET['download'])&&$_GET['download']==='backup'){
    if(!$super){http_response_code(403);exit('Super-admin required.');}
    sk960_audit('backup_download',[], $uid);sk960_export_database();
}
try{
    if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
        csrf_check();$action=(string)($_POST['action']??'');
        if($action==='clear_cache'){$result=sk960_clear_caches();sk960_audit('clear_cache',$result,$uid);$flash='Application cache cleared successfully.';}
        elseif($action==='reset_opcache'){$ok=function_exists('opcache_reset')?(bool)opcache_reset():false;$result=['opcache_reset'=>$ok];sk960_audit('reset_opcache',$result,$uid);$flash=$ok?'OPcache reset successfully.':'OPcache reset is not available on this server.';}
        elseif(in_array($action,['check_table','analyze_table','optimize_table'],true)){
            if(!$super)throw new RuntimeException('Super-admin permission required.');$table=(string)($_POST['table']??'');$map=['check_table'=>'CHECK','analyze_table'=>'ANALYZE','optimize_table'=>'OPTIMIZE'];$result=sk960_run_table_command($map[$action],[$table]);sk960_audit($action,['table'=>$table],$uid);$flash=$map[$action].' completed for '.$table.'.';
        }
        elseif(in_array($action,['check_all','analyze_all','optimize_all'],true)){
            if(!$super)throw new RuntimeException('Super-admin permission required.');if((string)($_POST['confirm_text']??'')!=='MAINTAIN DATABASE')throw new RuntimeException('Confirmation text did not match.');$tables=array_map(fn($x)=>(string)$x['TABLE_NAME'],sk960_tables());$map=['check_all'=>'CHECK','analyze_all'=>'ANALYZE','optimize_all'=>'OPTIMIZE'];$result=sk960_run_table_command($map[$action],$tables);sk960_audit($action,['table_count'=>count($tables)],$uid);$flash=$map[$action].' completed for '.count($tables).' tables.';
        }
        elseif($action==='delete_row'){
            if(!$super)throw new RuntimeException('Super-admin permission required.');$table=(string)($_POST['table']??'');$pk=sk960_primary_key($table);if(!$pk)throw new RuntimeException('This table has no single primary key.');$id=(string)($_POST['pk_value']??'');if((string)($_POST['confirm_text']??'')!=='DELETE ROW')throw new RuntimeException('Confirmation text did not match.');$q=db()->prepare('DELETE FROM '.sk960_ident($table).' WHERE '.sk960_ident($pk).'=? LIMIT 1');$q->execute([$id]);$result=['deleted'=>$q->rowCount(),'table'=>$table,'pk'=>$pk,'value'=>$id];sk960_audit('delete_row',$result,$uid);$flash='Row delete operation completed.';
        }
        elseif($action==='truncate_table'){
            if(!$super)throw new RuntimeException('Super-admin permission required.');$table=(string)($_POST['table']??'');if((string)($_POST['confirm_text']??'')!=='TRUNCATE '.$table)throw new RuntimeException('Type exactly: TRUNCATE '.$table);db()->exec('TRUNCATE TABLE '.sk960_ident($table));$result=['table'=>$table,'truncated'=>true];sk960_audit('truncate_table',$result,$uid);$flash='Table '.$table.' truncated.';
        }
        elseif($action==='readonly_sql'){$sql=(string)($_POST['sql']??'');$result=sk960_readonly_sql($sql);sk960_audit('readonly_sql',['query'=>mb_substr($sql,0,500),'rows'=>count($result['rows']??[])],$uid);}
    }
}catch(Throwable $e){$error=$e->getMessage();}

$summary=sk960_db_summary();$tables=sk960_tables();$cacheDirs=sk960_cache_dirs();$cacheBytes=0;foreach($cacheDirs as $d){try{$cacheBytes+=sk960_dir_size($d);}catch(Throwable $e){}}
$table=(string)($_GET['table']??'');$search=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$browse=null;
if($table!==''){try{$browse=sk960_browse($table,$search,$page,50);}catch(Throwable $e){$error=$e->getMessage();$table='';}}
page_start('Database & Maintenance Center',true);
?>
<link rel="stylesheet" href="/assets/admin-sidebar-tools-v974.css?v=974">
<script defer src="/assets/admin-sidebar-tools-v974.js?v=974"></script>
<link rel="stylesheet" href="/assets/admin-db-v960.css?v=960">
<div class="db960"><div style="text-align:right;margin-bottom:8px"><a href="/admin/admin-tools.php?sk975_lock=1" style="font-weight:800;text-decoration:none">🔒 Lock Admin Tools</a></div>
<section class="db960-hero"><div><span>SHAHKOTPK v9.6.0 · PRO ADMIN TOOL</span><h2>Database & Maintenance Center</h2><p>Inspect the complete project database, browse tables, check structure, export SQL backups, run maintenance, clear application cache and review server health without leaving the admin panel.</p></div><div class="db960-status"><b><?=e($summary['database'])?></b><small>MySQL <?=e($summary['version'])?></small><em><?=$super?'Super-admin maintenance enabled':'Safe mode'?></em></div></section>
<?php if($flash):?><div class="db960-alert ok"><?=e($flash)?></div><?php endif;?><?php if($error):?><div class="db960-alert bad"><?=e($error)?></div><?php endif;?>
<section class="db960-stats"><article><span>TABLES</span><b><?=number_format($summary['tables'])?></b><small>project tables</small></article><article><span>EST. ROWS</span><b><?=number_format($summary['rows'])?></b><small>database records</small></article><article><span>DATABASE SIZE</span><b><?=e(sk960_fmt_bytes($summary['total']))?></b><small>data + indexes</small></article><article><span>CACHE SIZE</span><b><?=e(sk960_fmt_bytes($cacheBytes))?></b><small><?=count($cacheDirs)?> cache locations</small></article></section>

<section class="db960-grid2">
<article class="db960-card"><div class="head"><div><span>STORAGE</span><h3>External Storage Center</h3></div><strong>v9.7</strong></div><p>Move hosting-heavy images, videos, documents, backups and exports to Google Cloud, Google Drive, FTP/SFTP, S3-compatible storage, Azure Blob, WebDAV or a mounted/local disk.</p><a class="button primary" href="/admin/storage-manager.php">Open Storage Control Center →</a></article>
<article class="db960-card"><div class="head"><div><span>QUICK MAINTENANCE</span><h3>Cache & runtime</h3></div><strong>Safe</strong></div><p>Clears only detected application cache folders. Config, uploads and database data are not selected.</p><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="clear_cache"><button class="primary">⚡ Clear Application Cache</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reset_opcache"><button>↻ Reset PHP OPcache</button></form></div><?php if($cacheDirs):?><div class="chips"><?php foreach($cacheDirs as $d):?><span><?=e(str_replace(realpath(__DIR__.'/..')?:dirname(__DIR__), '', $d))?></span><?php endforeach;?></div><?php endif;?></article>
<article class="db960-card"><div class="head"><div><span>BACKUP</span><h3>Full SQL export</h3></div><strong><?=$super?'Enabled':'Locked'?></strong></div><p>Streams a complete SQL backup including table structures and data. No database password is written into the backup.</p><?php if($super):?><a class="button primary" href="?download=backup">⇩ Download Full Database Backup</a><?php else:?><p class="muted">Super-admin permission is required for full database export.</p><?php endif;?></article>
</section>

<section class="db960-card"><div class="head"><div><span>DATABASE TABLES</span><h3>All project tables</h3></div><strong><?=number_format(count($tables))?> tables</strong></div><div class="table-wrap"><table><thead><tr><th>Table</th><th>Engine</th><th>Rows</th><th>Data</th><th>Indexes</th><th>Free</th><th>Actions</th></tr></thead><tbody><?php foreach($tables as $t):$tn=(string)$t['TABLE_NAME'];?><tr><td><a href="?table=<?=urlencode($tn)?>"><b><?=e($tn)?></b></a><small><?=e((string)$t['TABLE_COLLATION'])?></small></td><td><?=e((string)$t['ENGINE'])?></td><td><?=number_format((int)$t['TABLE_ROWS'])?></td><td><?=e(sk960_fmt_bytes((int)$t['DATA_LENGTH']))?></td><td><?=e(sk960_fmt_bytes((int)$t['INDEX_LENGTH']))?></td><td><?=e(sk960_fmt_bytes((int)$t['DATA_FREE']))?></td><td class="row-actions"><a class="mini" href="?table=<?=urlencode($tn)?>">Browse</a><?php if($super):?><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="analyze_table"><input type="hidden" name="table" value="<?=e($tn)?>"><button class="mini">Analyze</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="optimize_table"><input type="hidden" name="table" value="<?=e($tn)?>"><button class="mini">Optimize</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php if($browse):?>
<section class="db960-card"><div class="head"><div><span>TABLE BROWSER</span><h3><?=e($table)?></h3></div><strong><?=number_format($browse['total'])?> rows</strong></div><form method="get" class="search"><input type="hidden" name="table" value="<?=e($table)?>"><input name="q" value="<?=e($search)?>" placeholder="Search text columns..."><button>Search</button><a class="button" href="?table=<?=urlencode($table)?>">Reset</a></form><div class="schema"><details><summary>View table structure</summary><div class="table-wrap"><table><thead><tr><th>Column</th><th>Type</th><th>Null</th><th>Key</th><th>Default</th><th>Extra</th></tr></thead><tbody><?php foreach($browse['columns'] as $c):?><tr><td><b><?=e((string)$c['COLUMN_NAME'])?></b></td><td><?=e((string)$c['COLUMN_TYPE'])?></td><td><?=e((string)$c['IS_NULLABLE'])?></td><td><?=e((string)$c['COLUMN_KEY'])?></td><td><?=e((string)($c['COLUMN_DEFAULT']??'NULL'))?></td><td><?=e((string)$c['EXTRA'])?></td></tr><?php endforeach;?></tbody></table></div></details></div>
<div class="table-wrap"><table class="data"><thead><tr><?php foreach($browse['columns'] as $c):?><th><?=e((string)$c['COLUMN_NAME'])?></th><?php endforeach;?><?php if($super&&$browse['pk']):?><th>Action</th><?php endif;?></tr></thead><tbody><?php foreach($browse['rows'] as $r):?><tr><?php foreach($browse['columns'] as $c):$cn=(string)$c['COLUMN_NAME'];$v=$r[$cn]??null;?><td><?php if(sk960_sensitive_column($cn)):?><span class="masked">••••••••</span><?php else:?><span title="<?=e(is_scalar($v)?(string)$v:json_encode($v))?>"><?=e(mb_strimwidth($v===null?'NULL':(string)$v,0,120,'…'))?></span><?php endif;?></td><?php endforeach;?><?php if($super&&$browse['pk']):?><td><form method="post" class="danger-form" data-confirm="DELETE ROW"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_row"><input type="hidden" name="table" value="<?=e($table)?>"><input type="hidden" name="pk_value" value="<?=e((string)$r[$browse['pk']])?>"><input type="hidden" name="confirm_text" value=""><button class="mini danger">Delete</button></form></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><div class="pager"><span>Page <?=number_format($browse['page'])?> of <?=number_format($browse['pages'])?></span><?php if($browse['page']>1):?><a class="button" href="?table=<?=urlencode($table)?>&q=<?=urlencode($search)?>&page=<?=$browse['page']-1?>">← Previous</a><?php endif;?><?php if($browse['page']<$browse['pages']):?><a class="button" href="?table=<?=urlencode($table)?>&q=<?=urlencode($search)?>&page=<?=$browse['page']+1?>">Next →</a><?php endif;?></div>
<?php if($super):?><div class="danger-zone"><h4>Danger zone</h4><p>Truncate permanently removes every row from this table. Type <code>TRUNCATE <?=e($table)?></code> when prompted.</p><form method="post" class="danger-form" data-confirm="TRUNCATE <?=e($table)?>"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="truncate_table"><input type="hidden" name="table" value="<?=e($table)?>"><input type="hidden" name="confirm_text" value=""><button class="danger">Truncate <?=e($table)?></button></form></div><?php endif;?></section>
<?php endif;?>

<section class="db960-grid2"><article class="db960-card"><div class="head"><div><span>DATABASE HEALTH</span><h3>Whole database maintenance</h3></div><strong><?=$super?'Super-admin':'Locked'?></strong></div><p>For all-table maintenance, type <code>MAINTAIN DATABASE</code> when prompted. Optimize can take time on large tables.</p><?php if($super):?><div class="actions"><?php foreach([['check_all','Check All'],['analyze_all','Analyze All'],['optimize_all','Optimize All']] as $a):?><form method="post" class="danger-form" data-confirm="MAINTAIN DATABASE"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="<?=$a[0]?>"><input type="hidden" name="confirm_text" value=""><button><?=$a[1]?></button></form><?php endforeach;?></div><?php endif;?></article>
<article class="db960-card"><div class="head"><div><span>SQL CONSOLE</span><h3>Read-only query</h3></div><strong>SELECT only</strong></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="readonly_sql"><textarea name="sql" rows="5" placeholder="SELECT * FROM settings LIMIT 20"><?=e((string)($_POST['action']??'')==='readonly_sql'?(string)($_POST['sql']??''):'')?></textarea><button class="primary">Run Read-only Query</button></form></article></section>

<?php if(is_array($result)):?><section class="db960-card"><div class="head"><div><span>LAST OPERATION</span><h3>Result</h3></div></div><?php if(isset($result['rows'])&&isset($result['columns'])):?><div class="table-wrap"><table><thead><tr><?php foreach($result['columns'] as $c):?><th><?=e((string)$c)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($result['rows'] as $r):?><tr><?php foreach($result['columns'] as $c):?><td><?=e(mb_strimwidth((string)($r[$c]??'NULL'),0,160,'…'))?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php else:?><pre><?=e(json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></pre><?php endif;?></section><?php endif;?>
<p class="db960-foot">Direct URL: <code>/admin/database-manager.php</code> · Sensitive credential/password/token columns are masked in the browser.</p>
</div>
<script defer src="/assets/admin-db-v960.js?v=960"></script>
<?php require __DIR__.'/../app/end.php';?>
