<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
if(is_file(__DIR__.'/../app/core_sync_v1301.php'))require_once __DIR__.'/../app/core_sync_v1301.php';
require_once __DIR__.'/../app/data_consistency_v1305.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
$me=current_user();$ok=false;if($me){if(function_exists('sk1300_super_admin')&&sk1300_super_admin($me))$ok=true;elseif(function_exists('sk1300_tenant_admin')&&sk1300_tenant_admin($me))$ok=true;elseif(function_exists('has_permission')&&has_permission('settings.manage',$me))$ok=true;}if(!$ok){http_response_code(403);exit('Forbidden');}
$msg='';$err='';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    try{csrf_check();if((string)($_POST['action']??'')==='refresh_runtime'){$x=sk1305_refresh_public_runtime();$msg='Public runtime refresh complete: '.(int)$x['settings'].' setting row(s) touched · '.(int)$x['cache_rows'].' recommendation cache row(s) cleared · '.(int)$x['logged'].' audit record saved.'.(!empty($x['errors'])?' Notes: '.implode(' | ',$x['errors']):'');}}
    catch(Throwable $e){$err=$e->getMessage();}
}
$r=sk1305_scan();page_start('Data Consistency Center',true);
?>
<style>
.dc1305{max-width:1520px;margin:0 auto;padding:22px}.dc1305 .hero{padding:26px;border-radius:24px;background:linear-gradient(135deg,var(--sk-brand-primary,#0f2a4a),#235293);color:#fff;display:flex;justify-content:space-between;gap:20px}.dc1305 .score{font-size:46px;font-weight:900}.dc1305 .grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px;margin:18px 0}.dc1305 .card,.dc1305 .panel{background:#fff;border:1px solid #dce5ef;border-radius:18px;padding:18px}.dc1305 .card b{display:block;font-size:25px}.dc1305 .panel{margin:16px 0}.dc1305 table{width:100%;border-collapse:collapse}.dc1305 th,.dc1305 td{padding:10px;border-bottom:1px solid #e6edf5;text-align:left;vertical-align:top}.dc1305 .bad{color:#b42318;font-weight:800}.dc1305 .warn{color:#b54708;font-weight:800}.dc1305 .good{color:#067647;font-weight:800}.dc1305 .note{padding:12px;border-radius:12px;margin:12px 0;background:#eef5ff}.dc1305 .note.badbg{background:#fef3f2;color:#b42318}.dc1305 .note.goodbg{background:#ecfdf3;color:#067647}.dc1305 .btn{display:inline-flex;padding:11px 16px;border:0;border-radius:12px;background:#1769e0;color:#fff;font-weight:800;cursor:pointer}.dc1305 .scroll{overflow:auto}.dc1305 code{font-size:12px;white-space:nowrap}.dc1305 .pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2f6;font-size:12px;font-weight:800}.dc1305 .muted{color:#667085;font-size:13px}@media(max-width:1100px){.dc1305 .grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.dc1305 .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dc1305 .hero{display:block}}@media(max-width:520px){.dc1305{padding:12px}.dc1305 .grid{grid-template-columns:1fr}.dc1305 .hero{padding:19px;border-radius:18px}.dc1305 .score{font-size:38px}}
</style>
<div class="dc1305">
<section class="hero"><div><small>SHAHKOTPK v13.0.5.0 · STEP 5</small><h1>Admin CRUD ↔ Public Data Consistency</h1><p>Schema-aware audit of the content tables that actually exist on this installation. No content record is automatically deleted, published, unpublished or rewritten.</p></div><div><div class="score"><?=sk1301_h($r['score'])?>/100</div><small>Consistency score</small></div></section>
<?php if($msg):?><div class="note goodbg"><?=sk1301_h($msg)?></div><?php endif;?><?php if($err):?><div class="note badbg"><?=sk1301_h($err)?></div><?php endif;?>
<div class="grid"><div class="card"><b><?=count($r['modules'])?></b><span>Detected content modules</span></div><div class="card"><b><?=$r['totals']['records']?></b><span>Tenant/content records</span></div><div class="card"><b><?=$r['totals']['public']?></b><span>Public/active records</span></div><div class="card"><b class="<?=$r['high']?'bad':'good'?>"><?=$r['high']?></b><span>High-priority findings</span></div><div class="card"><b class="<?=$r['totals']['duplicate_slugs']?'warn':'good'?>"><?=$r['totals']['duplicate_slugs']?></b><span>Duplicate slug groups</span></div></div>
<section class="panel"><h2>Safe public runtime refresh</h2><p>Updates the public data cache version, clears only the tenant-scoped AI recommendation cache when that known table exists, and records an audit snapshot. It does not modify business/customer/content rows.</p><form method="post"><input type="hidden" name="_csrf" value="<?=sk1301_h(csrf_token())?>"><input type="hidden" name="action" value="refresh_runtime"><button class="btn">Refresh Public Runtime Safely</button></form></section>
<section class="panel"><h2>Detected module contracts</h2><div class="scroll"><table><thead><tr><th>Module</th><th>Table</th><th>Score</th><th>Total</th><th>Public</th><th>Hidden</th><th>Title</th><th>Media</th><th>Duplicate slug</th><th>Orphans</th><th>Visibility source</th></tr></thead><tbody><?php foreach($r['modules'] as $m):?><tr><td><b><?=sk1301_h($m['label'])?></b></td><td><code><?=sk1301_h($m['table'])?></code></td><td class="<?=$m['score']<80?'bad':($m['score']<95?'warn':'good')?>"><?=$m['score']?>/100</td><td><?=$m['total']?></td><td><?=$m['visible']?></td><td><?=$m['hidden']?></td><td class="<?=$m['missing_title']?'bad':'good'?>"><?=$m['missing_title']?></td><td class="<?=$m['missing_media']?'warn':'good'?>"><?=$m['missing_media']?></td><td class="<?=$m['duplicate_slugs']?'bad':'good'?>"><?=$m['duplicate_slugs']?></td><td class="<?=($m['orphan_user']+$m['orphan_category'])?'bad':'good'?>"><?=($m['orphan_user']+$m['orphan_category'])?></td><td><span class="pill"><?=sk1301_h($m['visibility_field']?:'all rows')?></span><div class="muted"><?=sk1301_h($m['visibility_mode'])?></div></td></tr><?php endforeach;?></tbody></table></div><?php if(!$r['modules']):?><div class="note">No supported content tables were detected. This page stays read-only and does not create fake content tables.</div><?php endif;?></section>
<section class="panel"><h2>Priority findings</h2><?php if(!$r['issues']):?><div class="note goodbg">No public-data consistency issue detected in the supported tables currently present.</div><?php else:?><?php foreach($r['issues'] as $i):?><div class="note <?=$i['severity']==='high'?'badbg':''?>"><b><?=sk1301_h(strtoupper($i['severity']))?> · <?=sk1301_h($i['module'])?> · <?=sk1301_h($i['type'])?></b><br><?=sk1301_h($i['message'])?> <span class="muted">Table: <?=sk1301_h($i['table'])?></span></div><?php endforeach;?><?php endif;?></section>
<section class="panel"><h2>How Step 5 reads your data</h2><p class="muted">For each detected module it automatically discovers the tenant column, public status/active field, title/name, slug and primary media field. A table or column that does not exist is skipped instead of causing a 500 error. Hidden/draft records are informational and are not treated as errors.</p></section>
</div>
<?php require __DIR__.'/../app/end.php';?>
