<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/lms_v1360.php';
require_once __DIR__.'/../app/layout.php';
$me=sk1360_user();if(!$me||!sk1360_admin()){http_response_code(403);exit('Forbidden');}

$msg='';$err='';try{$msg=sk1360_post_action('admin');}catch(Throwable $e){$err=$e->getMessage();}$pdo=sk1360_db();$tid=sk1360_tid();$q=$pdo->prepare('SELECT * FROM lms_teachers_v1360 WHERE tenant_id=? ORDER BY display_name');$q->execute([$tid]);$teachers=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$q=$pdo->prepare('SELECT * FROM lms_students_v1360 WHERE tenant_id=? ORDER BY id DESC LIMIT 300');$q->execute([$tid]);$students=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$inst=sk1360_institutes();$csrf=sk1360_csrf();page_start('LMS People',true);
?><link rel="stylesheet" href="/assets/lms-v1360.css?v=1360"><div class="lms-admin"><section class="lms-admin-hero compact"><div><span class="eyebrow">EDUCATION NETWORK</span><h1>Teachers & Students</h1><p>Teacher profiles connect existing ShahkotPK users to multi-teaching course roles. Student profiles are created on enrollment.</p></div><a class="btn" href="/admin/lms.php">← LMS Home</a></section><?php if($msg):?><div class="lms-alert ok"><?=sk1360_h($msg)?></div><?php endif;?><?php if($err):?><div class="lms-alert err"><?=sk1360_h($err)?></div><?php endif;?>
<div class="lms-admin-grid"><section class="lms-panel"><h2>Add / Update Teacher</h2><form method="post" class="lms-form"><input type="hidden" name="_csrf" value="<?=sk1360_h($csrf)?>"><input type="hidden" name="action" value="teacher.create"><label>Existing User ID<input type="number" min="1" name="user_id" required></label><label>Display Name<input name="display_name" placeholder="Leave blank to use account name"></label><label>Institute<select name="institute_id"><option value="0">Any / Independent</option><?php foreach($inst as $i):?><option value="<?=$i['id']?>"><?=sk1360_h($i['name'])?></option><?php endforeach;?></select></label><label>Bio<textarea name="bio" rows="4"></textarea></label><button>Save Teacher</button></form></section><section class="lms-panel"><h2>Teaching Team</h2><div class="people-list"><?php foreach($teachers as $t):?><div><span class="avatar">T</span><p><b><?=sk1360_h($t['display_name'])?></b><small>User #<?=$t['user_id']?> · <?=sk1360_h($t['status'])?></small></p></div><?php endforeach;?></div></section></div>
<section class="lms-panel"><h2>Students</h2><div class="course-table"><table><thead><tr><th>Student No.</th><th>User</th><th>Status</th><th>Joined</th></tr></thead><tbody><?php foreach($students as $s):?><tr><td><b><?=sk1360_h($s['student_no'])?></b></td><td><?=sk1360_h(sk1360_user_label((int)$s['user_id']))?><small>User #<?=$s['user_id']?></small></td><td><?=sk1360_h($s['status'])?></td><td><?=sk1360_h($s['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section></div><?php page_end();
