<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/lms_v1360.php';
require_once __DIR__.'/../app/layout.php';
$me=sk1360_user();if(!$me||!sk1360_admin()){http_response_code(403);exit('Forbidden');}

$msg='';$err='';try{$msg=sk1360_post_action('admin');}catch(Throwable $e){$err=$e->getMessage();}
$stats=sk1360_dashboard_stats();$institutes=sk1360_institutes();$courses=sk1360_courses();$csrf=sk1360_csrf();page_start('Education Network LMS',true);
?><link rel="stylesheet" href="/assets/lms-v1360.css?v=1360"><div class="lms-admin">
<section class="lms-admin-hero"><div><span class="eyebrow">▤ EDUCATION NETWORK · v13.6.0</span><h1>Multi-Teaching Learning Management System</h1><p>Courses, teachers, students, curriculum, assessments, attendance, gradebook and certificates in one tenant-safe LMS.</p></div><div class="hero-actions"><a href="/education-network.php" target="_blank">Public Catalog</a><a href="/teacher/lms.php" target="_blank">Teacher Portal</a><a href="/student/lms.php" target="_blank">Student Portal</a></div></section>
<?php if($msg):?><div class="lms-alert ok"><?=sk1360_h($msg)?></div><?php endif;?><?php if($err):?><div class="lms-alert err"><?=sk1360_h($err)?></div><?php endif;?>
<div class="lms-kpis"><div><b><?=$stats['courses']?></b><span>Courses</span></div><div><b><?=$stats['published']?></b><span>Published</span></div><div><b><?=$stats['teachers']?></b><span>Teachers</span></div><div><b><?=$stats['students']?></b><span>Students</span></div><div><b><?=$stats['enrollments']?></b><span>Enrollments</span></div></div>
<div class="lms-admin-grid"><section class="lms-panel"><h2>Create Institute / Academy</h2><form method="post" class="lms-form"><input type="hidden" name="_csrf" value="<?=sk1360_h($csrf)?>"><input type="hidden" name="action" value="institute.create"><label>Name<input name="name" required placeholder="e.g. Shahkot Academy"></label><label>Description<textarea name="description" rows="3"></textarea></label><button>Save Institute</button></form><div class="mini-list"><?php foreach($institutes as $i):?><span><b><?=sk1360_h($i['name'])?></b><small><?=sk1360_h($i['status'])?></small></span><?php endforeach;?></div></section>
<section class="lms-panel"><h2>Create Course</h2><form method="post" class="lms-form"><input type="hidden" name="_csrf" value="<?=sk1360_h($csrf)?>"><input type="hidden" name="action" value="course.create"><label>Institute<select name="institute_id"><option value="0">Independent</option><?php foreach($institutes as $i):?><option value="<?=$i['id']?>"><?=sk1360_h($i['name'])?></option><?php endforeach;?></select></label><label>Course Title<input name="title" required></label><div class="two"><label>Course Code<input name="code"></label><label>Category<input name="category"></label></div><div class="two"><label>Level<input name="level" value="All Levels"></label><label>Language<input name="language" value="English"></label></div><label>Short Summary<textarea name="summary" rows="2"></textarea></label><button>Create & Open Builder</button></form></section></div>
<section class="lms-panel"><div class="panel-title"><div><h2>Courses</h2><p>Open Course Builder for curriculum, teachers, batches, assessments and enrollment.</p></div><a href="/admin/lms-people.php">Manage Teachers & Students</a></div><div class="course-table"><table><thead><tr><th>Course</th><th>Institute</th><th>Status</th><th>Enrollment</th><th></th></tr></thead><tbody><?php foreach($courses as $c):?><tr><td><b><?=sk1360_h($c['title'])?></b><small><?=sk1360_h($c['code'])?> · <?=sk1360_h($c['category'])?></small></td><td><?=sk1360_h($c['institute_name']??'Independent')?></td><td><span class="status <?=$c['status']?>"><?=sk1360_h($c['status'])?></span></td><td><?=sk1360_h($c['enrollment_mode'])?></td><td><a class="btn small" href="/admin/lms-course.php?id=<?=$c['id']?>">Course Builder</a></td></tr><?php endforeach;?></tbody></table></div></section>
</div><?php page_end();
