<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
require_once __DIR__.'/../app/location_discovery_v54.php';
$me=require_permission('maps.manage');$flash='';$error='';
try{
 if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
  csrf_check();
  $def=max(.5,min(100,(float)($_POST['default_radius']??5)));$max=max($def,min(250,(float)($_POST['max_radius']??50)));$limit=max(5,min(100,(int)($_POST['results_limit']??30)));
  save_settings([
   'location_discovery_enabled'=>!empty($_POST['enabled'])?'1':'0','location_default_radius_km'=>(string)$def,'location_max_radius_km'=>(string)$max,'location_results_limit'=>(string)$limit,
   'location_live_results'=>!empty($_POST['live_results'])?'1':'0','location_auto_nearby'=>!empty($_POST['auto_nearby'])?'1':'0','location_show_distance'=>!empty($_POST['show_distance'])?'1':'0','location_directions_enabled'=>!empty($_POST['directions'])?'1':'0','location_analytics_enabled'=>!empty($_POST['analytics'])?'1':'0',
  ]);
  $flash='Advanced location discovery settings saved.';
  if(function_exists('tenant_audit'))tenant_audit('location_discovery_v54.saved','setting',null,'v5.4 location discovery settings updated');
 }
}catch(Throwable $e){$error=$e->getMessage();}
$stats=function_exists('google_maps_stats')?google_maps_stats():[];$searches=0;
try{if(v54_location_table_exists('location_search_events'))$searches=(int)db()->query("SELECT COUNT(*) FROM location_search_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)")->fetchColumn();}catch(Throwable $e){}
page_start('Advanced Location Discovery',true);
?>
<style>
.v54m-hero{padding:24px;border-radius:22px;background:radial-gradient(circle at 80% 20%,rgba(255,92,112,.28),transparent 34%),linear-gradient(135deg,#0a1935,#163765);color:#fff;margin-bottom:18px}.v54m-hero span{color:#ff7880;font-size:11px;font-weight:900;letter-spacing:.14em}.v54m-hero h2{font-size:30px;margin:8px 0}.v54m-hero p{max-width:860px;color:#cfdaea;line-height:1.6}.v54m-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:15px 0 0}.v54m-kpis div{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12);padding:13px;border-radius:14px}.v54m-kpis b{display:block;font-size:22px}.v54m-kpis small{color:#b9c7db}.v54m-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.v54m-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.v54m-form label{display:grid;gap:6px;font-weight:700}.v54m-form small{font-weight:400;color:#6c788b}.v54m-toggles{display:grid;gap:10px}.v54m-toggle{display:flex!important;grid-template-columns:none!important;align-items:flex-start;gap:10px;padding:11px;border:1px solid #e1e8f1;border-radius:12px}.v54m-toggle b,.v54m-toggle small{display:block}.v54m-type-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v54m-type-grid div{border:1px solid #e2e8f0;border-radius:12px;padding:11px}.v54m-type-grid b{display:block;font-size:18px}.v54m-alert{padding:12px 15px;border-radius:12px;margin-bottom:14px}.v54m-alert.ok{background:#ecfdf3;color:#17633d}.v54m-alert.err{background:#fff1f2;color:#9f253a}.v54m-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}@media(max-width:1050px){.v54m-grid,.v54m-form{grid-template-columns:1fr}.v54m-kpis{grid-template-columns:repeat(2,1fr)}}
</style>
<section class="v54m-hero"><span>SHAHKOTPK v5.4.0 · MAP & LOCATION</span><h2>Advanced Location Discovery</h2><p>Configure live nearby search, radius limits, map movement results, directions and location analytics. Results automatically respect the current tenant/city scope through the existing ShahkotPK map data layer.</p><div class="v54m-kpis"><div><b><?=google_maps_ready()?'Ready':'Needs Key'?></b><small>Google Maps</small></div><div><b><?=e((string)v54_location_default_radius())?> km</b><small>Default radius</small></div><div><b><?=e((string)v54_location_limit())?></b><small>Results per search</small></div><div><b><?=e((string)$searches)?></b><small>Searches · last 30 days</small></div></div></section>
<?php if($flash):?><div class="v54m-alert ok"><?=e($flash)?></div><?php endif;?><?php if($error):?><div class="v54m-alert err"><?=e($error)?></div><?php endif;?>
<form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><div class="v54m-grid"><section class="card"><h3>Discovery Search Settings</h3><div class="v54m-form"><label>Default search radius (km)<input type="number" min="0.5" max="100" step="0.5" name="default_radius" value="<?=e((string)v54_location_default_radius())?>"><small>Used on homepage and full discovery page.</small></label><label>Maximum radius (km)<input type="number" min="1" max="250" step="1" name="max_radius" value="<?=e((string)v54_location_max_radius())?>"><small>Upper limit users can select.</small></label><label>Results per search<input type="number" min="5" max="100" name="results_limit" value="<?=e((string)v54_location_limit())?>"><small>Keeps mobile and map performance controlled.</small></label></div><div class="v54m-toggles" style="margin-top:16px"><label class="v54m-toggle"><input type="checkbox" name="enabled" <?=v54_location_enabled()?'checked':''?>><span><b>Enable Advanced Discovery</b><small>Shows the v5.4 location experience on the homepage city-map section.</small></span></label><label class="v54m-toggle"><input type="checkbox" name="live_results" <?=setting_bool('location_live_results',true)?'checked':''?>><span><b>Live results when map moves</b><small>Refresh nearby results after the user pans the map.</small></span></label><label class="v54m-toggle"><input type="checkbox" name="auto_nearby" <?=setting_bool('location_auto_nearby',false)?'checked':''?>><span><b>Ask for location automatically</b><small>Recommended OFF; users can press Near Me when they want to share location.</small></span></label><label class="v54m-toggle"><input type="checkbox" name="show_distance" <?=setting_bool('location_show_distance',true)?'checked':''?>><span><b>Show distance</b><small>Displays calculated distance in kilometers on result cards.</small></span></label><label class="v54m-toggle"><input type="checkbox" name="directions" <?=setting_bool('location_directions_enabled',true)?'checked':''?>><span><b>Directions button</b><small>Opens Google Maps directions to the selected listing.</small></span></label><label class="v54m-toggle"><input type="checkbox" name="analytics" <?=setting_bool('location_analytics_enabled',true)?'checked':''?>><span><b>Location search analytics</b><small>Stores search area/radius/query and result count; no precise user identity is required.</small></span></label></div></section>
<section class="card"><h3>Mapped Content Coverage</h3><p style="color:#6c788b">These counts use the existing Map Control data. Add missing latitude/longitude from business or city-content editors.</p><div class="v54m-type-grid"><?php foreach($stats as $type=>$row):?><div><span><?=e(ucwords(str_replace('_',' ',$type)))?></span><b><?=e((string)($row['mapped']??0))?> / <?=e((string)($row['total']??0))?></b><small><?=e((string)($row['missing']??0))?> missing location</small></div><?php endforeach;?></div><div class="v54m-actions"><a class="btn" href="/admin/maps.php">Open Map Control</a><a class="btn" style="background:#475569" target="_blank" href="/city-discovery.php">Open Public Discovery ↗</a></div></section></div><div class="v54m-actions"><button class="btn" type="submit">Save Location Settings</button></div></form>
<?php page_end(); ?>
