<?php
require __DIR__.'/../app/bootstrap.php';require_permission('maps.manage');$msg=$err=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{csrf_check();$vals=['google_maps_enabled'=>isset($_POST['google_maps_enabled'])?'1':'0','google_maps_api_key'=>trim((string)($_POST['google_maps_api_key']??'')),'google_maps_default_lat'=>(string)(float)($_POST['google_maps_default_lat']??31.5709),'google_maps_default_lng'=>(string)(float)($_POST['google_maps_default_lng']??73.4853),'google_maps_default_zoom'=>(string)max(2,min(21,(int)($_POST['google_maps_default_zoom']??14))),'google_maps_map_type'=>in_array(($_POST['google_maps_map_type']??'roadmap'),['roadmap','satellite','hybrid','terrain'],true)?$_POST['google_maps_map_type']:'roadmap'];if($vals['google_maps_api_key']==='')$vals['google_maps_api_key']=google_maps_api_key();save_settings($vals);$msg='Google Maps settings saved.';}catch(Throwable $e){$err=$e->getMessage();}
}
$stats=google_maps_stats();$catalog=google_maps_type_catalog();$missing=google_maps_missing_records(120);$mappedTotal=0;$total=0;foreach($stats as $s){$mappedTotal+=(int)$s['mapped'];$total+=(int)$s['total'];}$missingTotal=max(0,$total-$mappedTotal);$center=google_maps_default_center();
require __DIR__.'/../app/layout.php';page_start('Map Control',true);
?><link rel="stylesheet" href="/assets/google-maps-3.1.1.css?v=311"><div class="admin-page-hero"><h2>Google Maps City Discovery</h2><p>One map control center for businesses, shops, City Guide places, deals, events, jobs and property. Search markers, inspect missing coordinates and configure the Google Maps API.</p></div><?php if($msg):?><div class="success"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="error"><?=e($err)?></div><?php endif;?>
<div class="map-admin-kpis"><article><b><?=e($total)?></b><span>Total map records</span><small>Businesses + city content</small></article><article><b><?=e($mappedTotal)?></b><span>Mapped</span><small>Coordinates available</small></article><article><b><?=e($missingTotal)?></b><span>Missing coordinates</span><small>Needs map pin assignment</small></article><article><b><?=google_maps_ready()?'READY':'SETUP'?></b><span>Google Maps API</span><small><?=google_maps_ready()?'Browser key configured':'Add API key below'?></small></article></div>
<?php if(!google_maps_ready()):?><div class="map-setup-alert"><b>Google Maps API key required.</b> Enter a Google Maps JavaScript API Browser Key below. In Google Cloud, enable Maps JavaScript API + Places/Geocoding as needed and restrict the browser key to your ShahkotPK domain.</div><?php endif;?>
<div class="map-key-status"><div><b>Browser API Key</b><small><?=e(google_maps_key_masked())?> · Google Maps <?=google_maps_enabled()?'enabled':'disabled'?></small></div><em class="<?=google_maps_ready()?'':'missing'?>"><?=google_maps_ready()?'INTERACTIVE READY':'KEY REQUIRED'?></em></div>
<div class="map-admin-grid" style="margin-top:14px"><section class="card"><div class="city-map-heading"><div><span>ADMIN LIVE MAP</span><h2>All mapped city records</h2><p>Use search and type filters to inspect what visitors will see.</p></div></div><?php if(google_maps_ready()):?><div class="city-map-module" style="padding:0;background:transparent"><div class="city-map-toolbar"><div class="city-map-search"><span>⌕</span><input data-map-search placeholder="Search mapped record..."></div><select data-map-type-filter><option value="">All Types</option><?php foreach($catalog as $k=>$m):?><option value="<?=e($k)?>"><?=e($m['label'])?></option><?php endforeach;?></select><button type="button" data-map-near>◎ Near Me</button></div><div class="shahkot-map" data-map-types="<?=e(implode(',',array_keys($catalog)))?>" style="height:560px"></div></div><?php else:?><div class="map-fallback-card"><div class="map-fallback-head"><div><span>BASE MAP PREVIEW</span><h3><?=e(setting('default_city','Shahkot'))?></h3><p>This preview works without the JavaScript API key. Add a Browser API key below to activate custom ShahkotPK markers, search, Near Me and map pickers.</p></div></div><iframe class="map-fallback-frame" loading="lazy" src="<?=e(google_maps_embed_url())?>" title="Google Map preview"></iframe></div><?php endif;?></section>
<aside><section class="card"><h3>Marker Coverage</h3><div class="map-missing-list"><?php foreach($stats as $k=>$s):$m=$catalog[$k]??['label'=>ucfirst($k)];?><div style="padding:9px;border-bottom:1px solid var(--admin-border,#e2e8f0)"><b><?=e($m['label'])?></b><small><?=e($s['mapped'])?> mapped / <?=e($s['total'])?> total · <?=e($s['missing'])?> missing</small></div><?php endforeach;?></div></section><section class="card" style="margin-top:14px"><h3>Missing Coordinates</h3><div class="map-missing-list"><?php foreach($missing as $r):?><a href="<?=e($r['edit_url'])?>"><span><b><?=e($r['title'])?></b><small><?=e(ucfirst((string)$r['type']))?> · <?=e($r['address']?:'No address')?></small></span><strong>Set Pin →</strong></a><?php endforeach;?><?php if(!$missing):?><div class="empty-state">Every tracked record has map coordinates.</div><?php endif;?></div></section></aside></div>
<section class="card" style="margin-top:14px"><h3>Google Maps Configuration</h3><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><div class="admin-form-grid"><div class="full"><label><input type="checkbox" name="google_maps_enabled" <?=google_maps_enabled()?'checked':''?>> Enable Google Maps</label></div><div class="full"><label>Google Maps Browser API Key</label><input class="input" type="password" name="google_maps_api_key" placeholder="<?=google_maps_api_key()!==''?'Saved — leave blank to keep':'AIza... Browser API key'?>" autocomplete="new-password"></div><div><label>Default Latitude</label><input class="input" name="google_maps_default_lat" value="<?=e($center['lat'])?>"></div><div><label>Default Longitude</label><input class="input" name="google_maps_default_lng" value="<?=e($center['lng'])?>"></div><div><label>Default Zoom</label><input class="input" type="number" min="2" max="21" name="google_maps_default_zoom" value="<?=e($center['zoom'])?>"></div><div><label>Map Type</label><select class="input" name="google_maps_map_type"><?php foreach(['roadmap'=>'Roadmap','satellite'=>'Satellite','hybrid'=>'Hybrid','terrain'=>'Terrain'] as $v=>$l):?><option value="<?=e($v)?>" <?=setting('google_maps_map_type','roadmap')===$v?'selected':''?>><?=e($l)?></option><?php endforeach;?></select></div></div><br><button class="btn">Save Map Configuration</button><a class="btn ghost" href="/admin/settings.php?module=maps">Advanced Map Settings</a><a class="btn ghost" target="_blank" href="/city-map.php">Open Public Map ↗</a></form></section>
<?php if(google_maps_ready())render_google_maps_assets();require __DIR__.'/../app/end.php';?>
