<?php
require __DIR__.'/../app/bootstrap.php';require_permission('payments.manage');require_once __DIR__.'/../app/payments.php';$msg=$err=null;$admin=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){try{csrf_check();$action=$_POST['action']??'gateway';
if($action==='gateway'){$id=(int)$_POST['id'];$enabled=isset($_POST['enabled'])?1:0;db()->prepare("UPDATE payment_gateways SET enabled=?,instructions=?,account_title=?,account_number=?,iban=?,merchant_id=?,secured_key=?,merchant_name=?,token_url=?,checkout_url=?,mode=?,sort_order=? WHERE id=?")->execute([$enabled,trim($_POST['instructions']??''),trim($_POST['account_title']??''),trim($_POST['account_number']??''),trim($_POST['iban']??''),trim($_POST['merchant_id']??''),trim($_POST['secured_key']??''),trim($_POST['merchant_name']??''),trim($_POST['token_url']??''),trim($_POST['checkout_url']??''),$_POST['mode']??'sandbox',(int)$_POST['sort_order'],$id]);$msg='Gateway saved.';}
elseif($action==='approve'){$txId=(int)$_POST['transaction_id'];$q=db()->prepare("SELECT * FROM payment_transactions WHERE id=?");$q->execute([$txId]);$tx=$q->fetch();if(!$tx)throw new RuntimeException('Transaction not found.');mark_payment_order_paid((int)$tx['order_id'],$tx['gateway_code'],$tx['customer_reference']?:'ADMIN-APPROVED',['manual_review'=>true],(int)$admin['id']);$msg='Payment approved; linked account/subscription effects activated.';}
elseif($action==='reject'){$txId=(int)$_POST['transaction_id'];db()->prepare("UPDATE payment_transactions SET status='failed',approved_by=? WHERE id=?")->execute([$admin['id'],$txId]);$msg='Payment rejected.';}
elseif($action==='order'){$id=create_payment_order((int)$_POST['user_id'],(float)$_POST['amount'],$_POST['purpose']??'other',(int)($_POST['business_id']??0)?:null,(int)($_POST['plan_id']??0)?:null,(int)($_POST['advertisement_id']??0)?:null,$_POST['approval_effect']??'none',['created_by_admin'=>$admin['id']]);$msg='Payment order #'.$id.' created.';}}
catch(Throwable $e){$err=$e->getMessage();}}
$gateways=get_payment_gateways(false);$txs=db()->query("SELECT pt.*,po.reference,po.purpose,u.name user_name,b.name business_name FROM payment_transactions pt JOIN payment_orders po ON po.id=pt.order_id JOIN users u ON u.id=po.user_id LEFT JOIN businesses b ON b.id=po.business_id ORDER BY pt.id DESC LIMIT 200")->fetchAll();$users=db()->query("SELECT id,name,email FROM users WHERE status='active' ORDER BY name")->fetchAll();$businesses=db()->query("SELECT id,name FROM businesses ORDER BY name")->fetchAll();$plans=db()->query("SELECT id,name,price FROM subscription_plans WHERE status=1 ORDER BY name")->fetchAll();$ads=db()->query("SELECT id,title FROM advertisements ORDER BY id DESC")->fetchAll();$stats=db()->query("SELECT COUNT(*) total,SUM(status='paid') paid_count,SUM(status='awaiting_payment') awaiting_count,COALESCE(SUM(IF(status='paid',amount,0)),0) revenue FROM payment_orders")->fetch();require __DIR__.'/../app/layout.php';page_start('Payments & Earnings',true);
?>
<div class="admin-page-hero"><h2>Payments & Earnings</h2><p>Configure JazzCash, Easypaisa, Raast/bank transfer and PayFast, review payment proofs, create orders and activate users/subscriptions after payment.</p></div><?php if($msg):?><div class="success"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="error"><?=e($err)?></div><?php endif;?>
<div class="admin-stat-row"><div class="admin-mini-stat"><span>Orders</span><strong><?=e($stats['total'])?></strong></div><div class="admin-mini-stat"><span>Paid</span><strong><?=e($stats['paid_count'])?></strong></div><div class="admin-mini-stat"><span>Awaiting</span><strong><?=e($stats['awaiting_count'])?></strong></div><div class="admin-mini-stat"><span>Revenue</span><strong>Rs <?=e(number_format((float)$stats['revenue'],0))?></strong></div></div>
<div class="card"><h3>Payment Gateways</h3><div class="grid"><?php foreach($gateways as $g):?><div class="payment-method-card"><span class="gateway-badge"><?=e($g['gateway_type'])?></span><h3><?=e($g['name'])?></h3><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="gateway"><input type="hidden" name="id" value="<?=e($g['id'])?>"><label><input type="checkbox" name="enabled" <?=$g['enabled']?'checked':''?>> Enable</label><label>Instructions</label><textarea class="input" rows="3" name="instructions"><?=e($g['instructions'])?></textarea>
<?php if($g['gateway_type']==='manual'):?><label>Account Title</label><input class="input" name="account_title" value="<?=e($g['account_title'])?>"><label>Account / Mobile / Raast ID</label><input class="input" name="account_number" value="<?=e($g['account_number'])?>"><label>IBAN</label><input class="input" name="iban" value="<?=e($g['iban'])?>"><input type="hidden" name="merchant_id" value=""><input type="hidden" name="secured_key" value=""><input type="hidden" name="merchant_name" value=""><input type="hidden" name="token_url" value=""><input type="hidden" name="checkout_url" value="">
<?php else:?><label>Merchant ID</label><input class="input" name="merchant_id" value="<?=e($g['merchant_id'])?>"><label>Merchant Name</label><input class="input" name="merchant_name" value="<?=e($g['merchant_name'])?>"><label>Secured Key</label><input class="input" type="password" name="secured_key" value="<?=e($g['secured_key'])?>"><label>Token URL</label><input class="input" name="token_url" value="<?=e($g['token_url'])?>"><label>Checkout URL</label><input class="input" name="checkout_url" value="<?=e($g['checkout_url'])?>"><input type="hidden" name="account_title" value=""><input type="hidden" name="account_number" value=""><input type="hidden" name="iban" value="">
<?php endif;?><label>Mode</label><select class="input" name="mode"><option value="sandbox" <?=$g['mode']==='sandbox'?'selected':''?>>Sandbox</option><option value="live" <?=$g['mode']==='live'?'selected':''?>>Live</option></select><label>Order</label><input class="input" type="number" name="sort_order" value="<?=e($g['sort_order'])?>"><br><button class="btn">Save</button></form></div><?php endforeach;?></div></div>
<div class="card"><h3>Create Payment Order</h3><form method="post" class="admin-form-grid"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="order"><div><label>User</label><select class="input" name="user_id"><?php foreach($users as $u):?><option value="<?=e($u['id'])?>"><?=e($u['name'])?> · <?=e($u['email'])?></option><?php endforeach;?></select></div><div><label>Purpose</label><select class="input" name="purpose"><option value="subscription">Subscription</option><option value="user_package">User Package</option><option value="advertisement">Advertisement</option><option value="other">Other</option></select></div><div><label>Amount</label><input class="input" type="number" step="0.01" name="amount" required></div><div><label>Effect</label><select class="input" name="approval_effect"><option value="none">None</option><option value="approve_user">Approve User</option><option value="activate_subscription">Activate Subscription</option></select></div><div><label>Plan</label><select class="input" name="plan_id"><option value="">None</option><?php foreach($plans as $p):?><option value="<?=e($p['id'])?>"><?=e($p['name'])?></option><?php endforeach;?></select></div><div><label>Business</label><select class="input" name="business_id"><option value="">None</option><?php foreach($businesses as $b):?><option value="<?=e($b['id'])?>"><?=e($b['name'])?></option><?php endforeach;?></select></div><div class="full"><label>Advertisement</label><select class="input" name="advertisement_id"><option value="">None</option><?php foreach($ads as $a):?><option value="<?=e($a['id'])?>"><?=e($a['title'])?></option><?php endforeach;?></select></div><div class="full"><button class="btn">Create Order</button></div></form></div>
<div class="card"><h3>Payment Review Queue</h3><table><tr><th>Reference</th><th>User</th><th>Method</th><th>Amount</th><th>Reference / Proof</th><th>Status</th><th>Review</th></tr><?php foreach($txs as $t):?><tr><td><?=e($t['reference'])?><br><span class="muted"><?=e($t['purpose'])?></span></td><td><?=e($t['user_name'])?><br><span class="muted"><?=e($t['business_name']?:'')?></span></td><td><?=e($t['gateway_code'])?></td><td>Rs <?=e(number_format((float)$t['amount'],0))?></td><td><?=e($t['customer_reference']?:'—')?><?php if($t['proof_url']):?><br><a target="_blank" href="<?=e($t['proof_url'])?>">View proof</a><?php endif;?></td><td><span class="badge <?=$t['status']==='paid'?'success':($t['status']==='review'?'warning':'slate')?>"><?=e($t['status'])?></span></td><td><?php if($t['status']==='review'):?><form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="approve"><input type="hidden" name="transaction_id" value="<?=e($t['id'])?>"><button class="btn success">Approve</button></form> <form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reject"><input type="hidden" name="transaction_id" value="<?=e($t['id'])?>"><button class="btn danger">Reject</button></form><?php endif;?></td></tr><?php endforeach;?></table></div>
<?php require __DIR__.'/../app/end.php';?>
