<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
if(is_file(__DIR__.'/../app/core_sync_v1301.php'))require_once __DIR__.'/../app/core_sync_v1301.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/production_hardening_v1315.php';
$me=current_user();$ok=false;if($me){if(function_exists('sk1300_super_admin')&&sk1300_super_admin($me))$ok=true;elseif(function_exists('sk1300_tenant_admin')&&sk1300_tenant_admin($me))$ok=true;elseif(function_exists('has_permission')&&has_permission('settings.manage',$me))$ok=true;}if(!$ok){http_response_code(403);exit('Forbidden');}
function sk1315h($v): string {return function_exists('sk1301_h')?sk1301_h((string)$v):htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$msg='';$err='';$r=null;if(($_SERVER['REQUEST_METHOD']??'')==='POST'){try{csrf_check();$a=(string)($_POST['action']??'');if($a==='fresh_audit'){$r=sk1315_fresh_audit();$msg='Fresh production readiness audit saved as run #'.(int)($r['run_id']??0).'.';}elseif($a==='safe_finalize'){$x=sk1315_safe_finalize();if($x['errors'])$err=implode(' | ',$x['errors']);$msg='Safe production finalize completed. Readiness status: '.strtoupper((string)$x['status']).' · Score '.(int)$x['score'].'/100.';$r=sk1315_fresh_audit();}}catch(Throwable $e){$err=$e->getMessage();}}
if(!$r)$r=sk1315_last_audit();page_start('Production Readiness',true);
?>
<style>.ph1315{max-width:1500px;margin:0 auto;padding:22px}.ph1315 .hero{padding:26px;border-radius:24px;background:linear-gradient(135deg,var(--sk-brand-primary,#102a43),#345d7e);color:#fff;display:flex;justify-content:space-between;gap:20px}.ph1315 .hero h1{margin:.3em 0}.ph1315 .score{font-size:46px;font-weight:900}.ph1315 .grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px;margin:18px 0}.ph1315 .card,.ph1315 .panel{background:#fff;border:1px solid #dce5ef;border-radius:18px;padding:18px}.ph1315 .card b{display:block;font-size:24px}.ph1315 .panel{margin:16px 0}.ph1315 table{width:100%;border-collapse:collapse}.ph1315 th,.ph1315 td{padding:10px;border-bottom:1px solid #e6edf5;text-align:left;vertical-align:top}.ph1315 .bad{color:#b42318;font-weight:800}.ph1315 .warn{color:#b54708;font-weight:800}.ph1315 .good{color:#067647;font-weight:800}.ph1315 .note{padding:12px;border-radius:12px;margin:12px 0;background:#eef5ff}.ph1315 .badbg{background:#fef3f2;color:#b42318}.ph1315 .goodbg{background:#ecfdf3;color:#067647}.ph1315 .btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 15px;border:0;border-radius:12px;background:#1769e0;color:#fff;font-weight:800;cursor:pointer}.ph1315 .btn.secondary{background:#344054}.ph1315 .actions{display:flex;gap:10px;flex-wrap:wrap}.ph1315 .scroll{overflow:auto}.ph1315 .muted{color:#667085;font-size:13px}.ph1315 code{overflow-wrap:anywhere}.ph1315 .links{display:flex;gap:8px;flex-wrap:wrap}.ph1315 .links a{padding:8px 10px;border:1px solid #dce5ef;border-radius:10px;text-decoration:none}@media(max-width:1200px){.ph1315 .grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.ph1315{padding:12px}.ph1315 .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ph1315 .hero{display:block;padding:19px}.ph1315 .score{font-size:38px}}@media(max-width:520px){.ph1315 .grid{grid-template-columns:1fr}}</style>
<div class="ph1315"><section class="hero"><div><small>SHAHKOTPK v13.0.15.2 · STABLE CLEANUP</small><h1>Production Hardening + Stable Release</h1><p>Final bounded production-readiness audit. Native front menu, content and user data remain untouched.</p></div><div><div class="score"><?=$r?sk1315h($r['score']).'/100':'—'?></div><small><?=$r?($r['ready']?'READY':'REVIEW REQUIRED'):'Run the first audit'?></small></div></section>
<?php if($msg):?><div class="note goodbg"><?=sk1315h($msg)?></div><?php endif;?><?php if($err):?><div class="note badbg"><?=sk1315h($err)?></div><?php endif;?>
<section class="panel"><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=sk1315h(csrf_token())?>"><input type="hidden" name="action" value="fresh_audit"><button class="btn">Run Production Readiness Audit</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=sk1315h(csrf_token())?>"><input type="hidden" name="action" value="safe_finalize"><button class="btn secondary">Safe Finalize Stable Baseline</button></form></div><p class="muted">Finalize only refreshes stable/version metadata and Step-15 audit history. It does not change hosting configuration automatically.</p></section>
<section class="panel"><h2>Integrity centers</h2><div class="links"><a href="/admin/regression-integrity.php">Full Regression</a><a href="/admin/runtime-integrity.php">Runtime</a><a href="/admin/security-integrity.php">Security</a><a href="/admin/database-integrity.php">Database</a><a href="/admin/public-seo-routing.php">Public SEO</a><a href="/admin/background-integrity.php">Background Jobs</a><a href="/admin/permissions-integrity.php">Permissions</a><a href="/admin/media-integrity.php">Media</a><a href="/admin/data-consistency.php">Data Consistency</a></div></section>
<?php if(!$r):?><section class="panel"><h2>No production readiness run saved yet</h2><p>Run the first audit after installation. The audit is on-demand only and does not run on normal requests.</p></section><?php else:$verBad=0;foreach($r['versions'] as $x)if(!$x['ok'])$verBad++;?>
<div class="grid"><div class="card"><b class="<?=$r['ready']?'good':'warn'?>"><?=$r['ready']?'READY':'REVIEW'?></b><span>Stable readiness</span></div><div class="card"><b class="<?=$r['high_count']?'bad':'good'?>"><?=$r['high_count']?></b><span>High findings</span></div><div class="card"><b class="<?=$r['medium_count']?'warn':'good'?>"><?=$r['medium_count']?></b><span>Medium findings</span></div><div class="card"><b class="<?=($r['manifest']['missing']||$r['manifest']['mismatch'])?'bad':'good'?>"><?=count($r['manifest']['missing'])+count($r['manifest']['mismatch'])?></b><span>Stable file drift</span></div><div class="card"><b class="<?=$r['uploads']['hits']?'bad':'good'?>"><?=count($r['uploads']['hits'])?></b><span>Executable upload hits</span></div><div class="card"><b class="<?=$verBad?'warn':'good'?>"><?=$verBad?></b><span>Version contract drift</span></div></div>
<section class="panel"><h2>Production findings</h2><?php if(!$r['findings']):?><p class="good">No high/medium/low production-hardening finding detected in the bounded audit.</p><?php else:?><div class="scroll"><table><thead><tr><th>Severity</th><th>Finding</th></tr></thead><tbody><?php foreach($r['findings'] as $f):?><tr><td class="<?=$f['severity']==='high'?'bad':($f['severity']==='medium'?'warn':'')?>"><?=sk1315h(strtoupper($f['severity']))?></td><td><?=sk1315h($f['message'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>Stable release SHA-256 manifest</h2><p>Manifest version: <b><?=sk1315h($r['manifest']['version']?:'—')?></b> · <?=number_format((int)$r['manifest']['checked'])?> package-owned files verified.</p><?php if(!$r['manifest']['missing']&&!$r['manifest']['mismatch']&&!$r['manifest']['invalid']):?><p class="good">Package-owned control/runtime files match the stable v13.0.15.2 baseline.</p><?php else:?><div class="scroll"><table><thead><tr><th>Type</th><th>Path</th></tr></thead><tbody><?php foreach($r['manifest']['missing'] as $x):?><tr><td class="bad">MISSING</td><td><code><?=sk1315h($x)?></code></td></tr><?php endforeach;?><?php foreach($r['manifest']['mismatch'] as $x):?><tr><td class="bad">CHANGED</td><td><code><?=sk1315h($x)?></code></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>PHP/session production settings</h2><div class="scroll"><table><thead><tr><th>Setting</th><th>Expected</th><th>Actual</th><th>Status</th></tr></thead><tbody><?php foreach($r['environment']['checks'] as $x):?><tr><td><code><?=sk1315h($x['name'])?></code></td><td><?=sk1315h($x['wanted'])?></td><td><?=sk1315h($x['actual'])?></td><td class="<?=$x['ok']?'good':($x['severity']==='high'?'bad':'warn')?>"><?=$x['ok']?'PASS':'REVIEW'?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">PHP <?=sk1315h($r['environment']['php_version'])?> · <?=sk1315h($r['environment']['sapi'])?> · Memory <?=sk1315h($r['environment']['memory_limit'])?> · OPcache <?=$r['environment']['opcache_enabled']?'enabled':'not detected'?>.</p></section>
<section class="panel"><h2>Filesystem / uploads safety</h2><p><?=number_format((int)$r['uploads']['checked'])?> upload files inspected (bounded to <?=number_format((int)$r['upload_scan_limit'])?>). <?=$r['uploads']['truncated']?'Scan limit reached.':''?></p><?php if($r['uploads']['hits']):?><div class="scroll"><table><thead><tr><th>Executable-looking upload</th></tr></thead><tbody><?php foreach($r['uploads']['hits'] as $x):?><tr><td class="bad"><code><?=sk1315h($x)?></code></td></tr><?php endforeach;?></tbody></table></div><?php else:?><p class="good">No PHP-like executable extension found in the bounded uploads scan.</p><?php endif;?></section>
<section class="panel"><h2>Version contract</h2><div class="scroll"><table><thead><tr><th>Setting</th><th>Expected ≥</th><th>Actual</th><th>Status</th></tr></thead><tbody><?php foreach($r['versions'] as $x):?><tr><td><code><?=sk1315h($x['key'])?></code></td><td><?=sk1315h($x['expected'])?></td><td><?=sk1315h($x['actual']?:'—')?></td><td class="<?=$x['ok']?'good':'warn'?>"><?=$x['ok']?'PASS':'REVIEW'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Latest control-plane audits</h2><div class="scroll"><table><thead><tr><th>Center</th><th>Table</th><th>Latest run</th><th>Score</th></tr></thead><tbody><?php foreach($r['history'] as $x):?><tr><td><?=sk1315h($x['label'])?></td><td><code><?=sk1315h($x['table'])?></code></td><td><?=sk1315h($x['created_at']?:'Not run')?></td><td><?=is_int($x['score'])?sk1315h((string)$x['score']).'/100':'—'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Stable safety contract</h2><p>No Step-15 scanner runs on normal requests. No automatic chmod, php.ini edit, `.htaccess` rewrite, password reset, role/permission rewrite, content/media deletion, queue execution or public-navigation generation is performed.</p></section>
<?php endif;?></div><?php require __DIR__.'/../app/end.php';?>
