<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/full_project_audit_v1383.php';
$u=function_exists('current_user')?current_user():null;$allowed=false;
try{$allowed=is_array($u)&&((function_exists('sk1300_super_admin')&&sk1300_super_admin($u))||(function_exists('sk1300_tenant_admin')&&sk1300_tenant_admin($u))||(function_exists('sk1300_can')&&sk1300_can('admin.project_audit',$u))||(function_exists('has_permission')&&has_permission('settings.manage')));}catch(Throwable $e){}
if(!$allowed){http_response_code(403);exit('Access denied.');}
$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{if(function_exists('csrf_check'))csrf_check();$a=(string)($_POST['action']??'');if($a==='cleanup'){$r=sk1383_cleanup(true);$msg='Safe cleanup completed: '.count($r['removed']).' stale files removed; '.(int)($r['source_repairs']['changed']??0).' conservative source repairs applied.';}elseif($a==='manifest'){$msg=sk1383_write_installed_manifest()?'Installed manifest refreshed.':'Manifest could not be written.';}}catch(Throwable $e){$err=$e->getMessage();}
}
$s=sk1383_snapshot();page_start('Full Project Audit',true);
?>
<style>.sk1383{max-width:1500px;margin:auto}.sk1383-hero{padding:24px;border-radius:18px;background:linear-gradient(135deg,#111827,#1e3a8a);color:white;margin-bottom:18px}.sk1383-hero h1{margin:4px 0 8px}.sk1383-kpis{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:12px;margin:16px 0}.sk1383-kpis article,.sk1383-card{background:#fff;border:1px solid #dfe7f1;border-radius:15px;padding:16px}.sk1383-kpis b{font-size:28px;display:block}.sk1383-list{display:grid;gap:8px}.sk1383-row{display:grid;grid-template-columns:30px minmax(220px,1fr) minmax(180px,1fr);gap:10px;align-items:center;padding:11px 12px;border:1px solid #e7edf5;border-radius:12px}.sk1383-row.ok i{color:#15803d}.sk1383-row.bad i{color:#b45309}.sk1383-actions{display:flex;gap:10px;flex-wrap:wrap}.sk1383-actions form{margin:0}.sk1383-note{padding:12px;border-radius:10px;background:#fffbeb;border:1px solid #fde68a}.sk1383-msg{padding:12px;border-radius:10px;background:#ecfdf5;border:1px solid #a7f3d0;margin-bottom:12px}.sk1383-err{background:#fef2f2;border-color:#fecaca}@media(max-width:760px){.sk1383-kpis{grid-template-columns:1fr}.sk1383-row{grid-template-columns:26px 1fr}.sk1383-row small{grid-column:2}}</style>
<div class="sk1383"><section class="sk1383-hero"><small>SHAHKOTPK v13.8.3 · PRODUCTION STABILIZATION</small><h1>Full Project Audit</h1><p>Bounded live checks for critical files, database contracts, version state, map migration, stale assets and safe compatibility repairs. It does not run a heavy full-tree scan on normal requests.</p></section>
<?php if($msg):?><div class="sk1383-msg"><?=sk1383_h($msg)?></div><?php endif;?><?php if($err):?><div class="sk1383-msg sk1383-err"><?=sk1383_h($err)?></div><?php endif;?>
<div class="sk1383-kpis"><article><span>Checks passed</span><b><?=$s['pass']?> / <?=$s['total']?></b></article><article><span>Attention</span><b><?=$s['attention']?></b></article><article><span>Source repairs</span><b><?=$s['source_repairs']?></b></article></div>
<section class="sk1383-card"><div class="sk1383-actions"><form method="post"><input type="hidden" name="_csrf" value="<?=sk1383_h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="action" value="cleanup"><button class="btn">Re-run Safe Stale Cleanup</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=sk1383_h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="action" value="manifest"><button class="btn">Refresh Installed Manifest</button></form><a class="btn" href="/admin/regression-integrity.php">Regression Center</a><a class="btn" href="/admin/database-integrity.php">Database Integrity</a></div></section>
<section class="sk1383-card"><h2>Current bounded checks</h2><div class="sk1383-list"><?php foreach($s['checks'] as $c):?><div class="sk1383-row <?=$c['ok']?'ok':'bad'?>"><i><?=$c['ok']?'✓':'!'?></i><b><?=sk1383_h($c['label'])?></b><small><?=sk1383_h($c['detail'])?></small></div><?php endforeach;?></div></section>
<section class="sk1383-card"><h2>Audit boundary</h2><div class="sk1383-note">Static/source audit cannot prove third-party SMTP delivery, payment gateway callbacks, real cron execution, browser geolocation permission, CDN/network availability, cPanel filesystem ownership or a real restore drill. Those remain live-environment checks.</div></section></div>
<?php page_end();
