<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
if(is_file(__DIR__.'/../app/core_sync_v1301.php'))require_once __DIR__.'/../app/core_sync_v1301.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/regression_integrity_v1314.php';
$me=current_user();$ok=false;if($me){if(function_exists('sk1300_super_admin')&&sk1300_super_admin($me))$ok=true;elseif(function_exists('sk1300_tenant_admin')&&sk1300_tenant_admin($me))$ok=true;elseif(function_exists('has_permission')&&has_permission('settings.manage',$me))$ok=true;}if(!$ok){http_response_code(403);exit('Forbidden');}
function sk1314h($v): string {return function_exists('sk1301_h')?sk1301_h((string)$v):htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$msg='';$err='';$r=null;if(($_SERVER['REQUEST_METHOD']??'')==='POST'){try{csrf_check();$a=(string)($_POST['action']??'');if($a==='fresh_audit'){$r=sk1314_fresh_audit();$msg='Fresh full regression audit saved as run #'.(int)($r['run_id']??0).'.';}elseif($a==='safe_cleanup'){$x=sk1314_safe_cleanup();if($x['errors'])$err=implode(' | ',$x['errors']);$msg='Safe regression cleanup completed. Application content/data was not modified.';$r=sk1314_fresh_audit();}}catch(Throwable $e){$err=$e->getMessage();}}
if(!$r)$r=sk1314_last_audit();page_start('Full Regression Integrity',true);
?>
<style>.ri1314{max-width:1500px;margin:0 auto;padding:22px}.ri1314 .hero{padding:26px;border-radius:24px;background:linear-gradient(135deg,var(--sk-brand-primary,#102a43),#3a5f86);color:#fff;display:flex;justify-content:space-between;gap:20px}.ri1314 .hero h1{margin:.3em 0}.ri1314 .score{font-size:46px;font-weight:900}.ri1314 .grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px;margin:18px 0}.ri1314 .card,.ri1314 .panel{background:#fff;border:1px solid #dce5ef;border-radius:18px;padding:18px}.ri1314 .card b{display:block;font-size:24px}.ri1314 .panel{margin:16px 0}.ri1314 table{width:100%;border-collapse:collapse}.ri1314 th,.ri1314 td{padding:10px;border-bottom:1px solid #e6edf5;text-align:left;vertical-align:top}.ri1314 .bad{color:#b42318;font-weight:800}.ri1314 .warn{color:#b54708;font-weight:800}.ri1314 .good{color:#067647;font-weight:800}.ri1314 .note{padding:12px;border-radius:12px;margin:12px 0;background:#eef5ff}.ri1314 .badbg{background:#fef3f2;color:#b42318}.ri1314 .goodbg{background:#ecfdf3;color:#067647}.ri1314 .btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 15px;border:0;border-radius:12px;background:#1769e0;color:#fff;font-weight:800;cursor:pointer}.ri1314 .btn.secondary{background:#344054}.ri1314 .actions{display:flex;gap:10px;flex-wrap:wrap}.ri1314 .scroll{overflow:auto}.ri1314 .muted{color:#667085;font-size:13px}.ri1314 code{overflow-wrap:anywhere}@media(max-width:1200px){.ri1314 .grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.ri1314{padding:12px}.ri1314 .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ri1314 .hero{display:block;padding:19px}.ri1314 .score{font-size:38px}}@media(max-width:520px){.ri1314 .grid{grid-template-columns:1fr}}</style>
<div class="ri1314"><section class="hero"><div><small>SHAHKOTPK v13.0.14.0 · STEP 14</small><h1>Full Regression Test + Broken Feature Cleanup</h1><p>Consolidated Steps 3–13 control-plane audit. Native front menu remains authoritative.</p></div><div><div class="score"><?=$r?sk1314h($r['score']).'/100':'—'?></div><small><?=$r?'Regression integrity score':'Run the first audit'?></small></div></section>
<?php if($msg):?><div class="note goodbg"><?=sk1314h($msg)?></div><?php endif;?><?php if($err):?><div class="note badbg"><?=sk1314h($err)?></div><?php endif;?>
<section class="panel"><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=sk1314h(csrf_token())?>"><input type="hidden" name="action" value="fresh_audit"><button class="btn">Run Full Regression Audit</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=sk1314h(csrf_token())?>"><input type="hidden" name="action" value="safe_cleanup"><button class="btn secondary">Run Safe Regression Cleanup</button></form></div><p class="muted">Safe cleanup refreshes Step-14/cache metadata and stale Module Linkage cache only. Known-good Step-3/4 runtime files are restored by the updater package itself.</p></section>
<?php if(!$r):?><section class="panel"><h2>No regression run saved yet</h2><p>Run the first audit after installation to verify the consolidated Step 3–13 baseline.</p></section><?php else:$srcBad=0;foreach($r['source_checks'] as $x)if(!$x['ok'])$srcBad++;$verBad=0;foreach($r['versions'] as $x)if(!$x['ok'])$verBad++;$tblBad=0;foreach($r['control_tables'] as $x)if(!$x['exists'])$tblBad++;?>
<div class="grid"><div class="card"><b><?=count($r['files']['rows'])?></b><span>Control/runtime files</span></div><div class="card"><b class="<?=$r['files']['missing_critical']?'bad':'good'?>"><?=$r['files']['missing_critical']?></b><span>Critical files missing</span></div><div class="card"><b class="<?=$srcBad?'bad':'good'?>"><?=$srcBad?></b><span>Source regressions</span></div><div class="card"><b class="<?=$r['manifests']['missing_routes']?'bad':'good'?>"><?=count($r['manifests']['missing_routes'])?></b><span>Broken admin routes</span></div><div class="card"><b class="<?=$verBad?'warn':'good'?>"><?=$verBad?></b><span>Version drift</span></div><div class="card"><b class="<?=$tblBad?'warn':'good'?>"><?=$tblBad?></b><span>Audit tables missing</span></div></div>
<section class="panel"><h2>Regression findings</h2><?php if(!$r['findings']):?><p class="good">No high/medium regression finding detected in the consolidated bounded audit.</p><?php else:?><div class="scroll"><table><thead><tr><th>Severity</th><th>Finding</th></tr></thead><tbody><?php foreach($r['findings'] as $f):?><tr><td class="<?=$f['severity']==='high'?'bad':($f['severity']==='medium'?'warn':'')?>"><?=sk1314h(strtoupper($f['severity']))?></td><td><?=sk1314h($f['message'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>Known-good runtime source checks</h2><div class="scroll"><table><thead><tr><th>Check</th><th>File</th><th>Status</th><th>Notes</th></tr></thead><tbody><?php foreach($r['source_checks'] as $x):?><tr><td><?=sk1314h($x['name'])?></td><td><code><?=sk1314h($x['file'])?></code></td><td class="<?=$x['ok']?'good':'bad'?>"><?=$x['ok']?'PASS':'FAIL'?></td><td><?=sk1314h(implode(' | ',$x['notes']))?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Step 3–13 file matrix</h2><div class="scroll"><table><thead><tr><th>Step</th><th>Path</th><th>Status</th><th>Bytes</th></tr></thead><tbody><?php foreach($r['files']['rows'] as $x):?><tr><td><?=sk1314h($x['step'])?></td><td><code><?=sk1314h($x['path'])?></code></td><td class="<?=$x['exists']?'good':'bad'?>"><?=$x['exists']?'Present':'Missing'?></td><td><?=number_format((int)$x['bytes'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Sidebar manifest / route regression</h2><p><?=number_format((int)$r['manifests']['files_scanned'])?> manifest files and <?=number_format((int)$r['manifests']['items'])?> items inspected.</p><?php if(!$r['manifests']['missing_routes']):?><p class="good">No missing physical `/admin/*.php` route in the bounded manifest scan.</p><?php else:?><div class="scroll"><table><thead><tr><th>Label</th><th>Route</th><th>Manifest</th></tr></thead><tbody><?php foreach($r['manifests']['missing_routes'] as $x):?><tr><td><?=sk1314h($x['label'])?></td><td><code><?=sk1314h($x['path'])?></code></td><td><?=sk1314h($x['manifest'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>Version contract</h2><div class="scroll"><table><thead><tr><th>Setting</th><th>Expected ≥</th><th>Actual</th><th>Status</th></tr></thead><tbody><?php foreach($r['versions'] as $x):?><tr><td><code><?=sk1314h($x['key'])?></code></td><td><?=sk1314h($x['expected'])?></td><td><?=sk1314h($x['actual']?:'—')?></td><td class="<?=$x['ok']?'good':'warn'?>"><?=$x['ok']?'PASS':'REVIEW'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Safety contract</h2><p>No regression scanner runs on normal requests. Step 14 does not delete or fabricate users, businesses, listings, media, jobs, notifications, roles or permissions. It does not redesign or generate the front-page main menu.</p></section>
<?php endif;?></div><?php require __DIR__.'/../app/end.php';?>
