<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/layout.php';
if(is_file(__DIR__.'/../app/core_sync_v1301.php'))require_once __DIR__.'/../app/core_sync_v1301.php';
if(is_file(__DIR__.'/../app/access_control_v1300.php'))require_once __DIR__.'/../app/access_control_v1300.php';
require_once __DIR__.'/../app/runtime_integrity_v1308.php';
$me=current_user();$ok=false;if($me){if(function_exists('sk1300_super_admin')&&sk1300_super_admin($me))$ok=true;elseif(function_exists('sk1300_tenant_admin')&&sk1300_tenant_admin($me))$ok=true;elseif(function_exists('has_permission')&&has_permission('settings.manage',$me))$ok=true;}if(!$ok){http_response_code(403);exit('Forbidden');}
function sk1308h($v): string {return function_exists('sk1301_h')?sk1301_h((string)$v):htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sk1308bytes(int $n): string {if($n<1024)return $n.' B';if($n<1048576)return number_format($n/1024,1).' KB';return number_format($n/1048576,1).' MB';}
$msg='';$err='';$r=null;
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    try{csrf_check();$action=(string)($_POST['action']??'');
        if($action==='fresh_audit'){$r=sk1308_fresh_audit();$msg='Fresh on-demand runtime audit complete and saved as run #'.(int)($r['run_id']??0).'.';}
        elseif($action==='safe_refresh'){$x=sk1308_safe_refresh();if(!empty($x['errors']))$err=implode(' | ',$x['errors']);$msg='Safe Runtime Refresh complete: '.(int)$x['settings_rows'].' setting row touch(es) · '.(int)$x['recommendation_cache_rows'].' tenant cache row(s) cleared.';$r=sk1308_fresh_audit();}
    }catch(Throwable $e){$err=$e->getMessage();}
}
if(!$r)$r=sk1308_last_audit();
page_start('Runtime Performance Integrity',true);
?>
<style>
.ri1308{max-width:1500px;margin:0 auto;padding:22px}.ri1308 .hero{padding:26px;border-radius:24px;background:linear-gradient(135deg,var(--sk-brand-primary,#0f2a4a),#235293);color:#fff;display:flex;justify-content:space-between;gap:20px}.ri1308 .hero h1{margin:.3em 0}.ri1308 .score{font-size:46px;font-weight:900}.ri1308 .grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px;margin:18px 0}.ri1308 .card,.ri1308 .panel{background:#fff;border:1px solid #dce5ef;border-radius:18px;padding:18px}.ri1308 .card b{display:block;font-size:24px}.ri1308 .panel{margin:16px 0}.ri1308 table{width:100%;border-collapse:collapse}.ri1308 th,.ri1308 td{padding:10px;border-bottom:1px solid #e6edf5;text-align:left;vertical-align:top}.ri1308 .bad{color:#b42318;font-weight:800}.ri1308 .warn{color:#b54708;font-weight:800}.ri1308 .good{color:#067647;font-weight:800}.ri1308 .note{padding:12px;border-radius:12px;margin:12px 0;background:#eef5ff}.ri1308 .badbg{background:#fef3f2;color:#b42318}.ri1308 .goodbg{background:#ecfdf3;color:#067647}.ri1308 .btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 15px;border:0;border-radius:12px;background:#1769e0;color:#fff;font-weight:800;cursor:pointer}.ri1308 .btn.secondary{background:#344054}.ri1308 .actions{display:flex;gap:10px;flex-wrap:wrap}.ri1308 .scroll{overflow:auto}.ri1308 .muted{color:#667085;font-size:13px}.ri1308 .pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2f6;font-size:12px;font-weight:800}@media(max-width:1100px){.ri1308 .grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){.ri1308{padding:12px}.ri1308 .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ri1308 .hero{display:block;padding:19px}.ri1308 .score{font-size:38px}}@media(max-width:520px){.ri1308 .grid{grid-template-columns:1fr}}
</style>
<div class="ri1308">
<section class="hero"><div><small>SHAHKOTPK v13.0.8.0 · STEP 8</small><h1>Cache, Session & Runtime Performance</h1><p>On-demand integrity checks only. No request-time profiler, background benchmark or continuous scanner is installed.</p></div><div><div class="score"><?=$r?sk1308h($r['score']).'/100':'—'?></div><small><?=$r?'Runtime score':'Run the first audit'?></small></div></section>
<?php if($msg):?><div class="note goodbg"><?=sk1308h($msg)?></div><?php endif;?><?php if($err):?><div class="note badbg"><?=sk1308h($err)?></div><?php endif;?>
<section class="panel"><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=sk1308h(csrf_token())?>"><input type="hidden" name="action" value="fresh_audit"><button class="btn">Run Fresh Runtime Audit</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=sk1308h(csrf_token())?>"><input type="hidden" name="action" value="safe_refresh"><button class="btn secondary">Safe Runtime Refresh</button></form></div><p class="muted">The benchmark performs only five SELECT 1 round-trips when you click Fresh Audit. Normal public/admin requests do not execute these checks.</p></section>
<?php if(!$r):?><section class="panel"><h2>No audit saved yet</h2><p>Run the first audit to measure the current live request environment.</p></section><?php else:$db=$r['db'];$se=$r['session'];$php=$r['php'];$vc=$r['versions'];?>
<div class="grid"><div class="card"><b class="<?=($db['avg_ms']??999)>75?'bad':(($db['avg_ms']??999)>20?'warn':'good')?>"><?=$db['avg_ms']===null?'—':sk1308h(number_format((float)$db['avg_ms'],2).' ms')?></b><span>DB avg round-trip</span></div><div class="card"><b class="<?=$se['bytes']>262144?'bad':($se['bytes']>65536?'warn':'good')?>"><?=sk1308h(sk1308bytes((int)$se['bytes']))?></b><span>Current session payload</span></div><div class="card"><b><?=sk1308h((string)$se['keys'])?></b><span>Session keys</span></div><div class="card"><b class="<?=$vc['mismatches']?'warn':'good'?>"><?=sk1308h((string)$vc['mismatches'])?></b><span>Version mismatches</span></div><div class="card"><b><?=is_array($php['opcache_status'])?(!empty($php['opcache_status']['enabled'])?'ON':'OFF'):($php['opcache_ini_enabled']?'Configured':'Not reported')?></b><span>PHP OPcache</span></div></div>
<section class="panel"><h2>Runtime findings</h2><?php if(empty($r['findings'])):?><p class="good">No high/medium runtime integrity finding in this audit.</p><?php else:?><div class="scroll"><table><thead><tr><th>Severity</th><th>Finding</th></tr></thead><tbody><?php foreach($r['findings'] as $f):?><tr><td class="<?=$f['severity']==='high'?'bad':($f['severity']==='medium'?'warn':'')?>"><?=sk1308h(strtoupper($f['severity']))?></td><td><?=sk1308h($f['message'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="panel"><h2>Cache / version contract</h2><div class="scroll"><table><thead><tr><th>Setting</th><th>Expected</th><th>Actual</th><th>Status</th></tr></thead><tbody><?php foreach($vc['rows'] as $x):?><tr><td><code><?=sk1308h($x['key'])?></code></td><td><?=sk1308h($x['expected'])?></td><td><?=sk1308h($x['actual']?:'—')?></td><td class="<?=$x['ok']?'good':'warn'?>"><?=$x['ok']?'OK':'STALE'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>PHP / request environment</h2><div class="scroll"><table><tbody><tr><th>PHP</th><td><?=sk1308h($php['php_version'].' · '.$php['sapi'])?></td></tr><tr><th>Memory limit</th><td><?=sk1308h($php['memory_limit'])?></td></tr><tr><th>Max execution time</th><td><?=sk1308h($php['max_execution_time'])?></td></tr><tr><th>Realpath cache</th><td><?=sk1308h($php['realpath_cache_size'].' · TTL '.$php['realpath_cache_ttl'])?></td></tr><tr><th>Session handler</th><td><?=sk1308h($se['handler'])?></td></tr></tbody></table></div></section>
<section class="panel"><h2>Largest current session entries</h2><div class="scroll"><table><thead><tr><th>Key</th><th>Approx size</th></tr></thead><tbody><?php foreach($se['largest'] as $x):?><tr><td><code><?=sk1308h($x['key'])?></code></td><td><?=sk1308h(sk1308bytes((int)$x['bytes']))?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">Step 8 reports large session values but does not delete authentication or application session data automatically.</p></section>
<?php if(!empty($r['cache_estimates'])):?><section class="panel"><h2>Known cache-table estimates</h2><div class="scroll"><table><thead><tr><th>Table</th><th>Estimated rows</th></tr></thead><tbody><?php foreach($r['cache_estimates'] as $t=>$n):?><tr><td><code><?=sk1308h($t)?></code></td><td><?=sk1308h(number_format((int)$n))?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">These are lightweight information_schema estimates, not full COUNT(*) scans.</p></section><?php endif;?>
<section class="panel"><h2>Safety contract</h2><p>Safe Runtime Refresh does not reset OPcache, does not delete sessions, does not alter the native public menu, and does not rewrite users, content, uploads or media. Tenant-scoped AI recommendation cache is cleared only when a tenant_id column and active tenant are both available.</p></section>
<?php endif;?>
</div>
