<?php
require __DIR__.'/../app/bootstrap.php';require_permission('ticker.manage');$msg=$err=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{csrf_check();$action=$_POST['action']??'save';$id=(int)($_POST['id']??0);if($action==='delete'){db()->prepare("DELETE FROM information_tickers WHERE id=?")->execute([$id]);$msg='Ticker deleted.';}else{$message=trim($_POST['message']??'');if(!$message)throw new RuntimeException('Message required.');$data=[trim($_POST['title']??'')?:null,$message,trim($_POST['link_url']??'')?:null,$_POST['scope']??'both',$_POST['style']??'info',$_POST['starts_at']?:null,$_POST['ends_at']?:null,isset($_POST['status'])?1:0,(int)($_POST['sort_order']??10)];if($id)db()->prepare("UPDATE information_tickers SET title=?,message=?,link_url=?,scope=?,style=?,starts_at=?,ends_at=?,status=?,sort_order=? WHERE id=?")->execute(array_merge($data,[$id]));else db()->prepare("INSERT INTO information_tickers(title,message,link_url,scope,style,starts_at,ends_at,status,sort_order) VALUES(?,?,?,?,?,?,?,?,?)")->execute($data);$msg='Ticker saved.';}}catch(Throwable $e){$err=$e->getMessage();}}
$edit=null;if(isset($_GET['edit'])){$q=db()->prepare("SELECT * FROM information_tickers WHERE id=?");$q->execute([(int)$_GET['edit']]);$edit=$q->fetch();}$rows=db()->query("SELECT * FROM information_tickers ORDER BY sort_order,id DESC")->fetchAll();require __DIR__.'/../app/layout.php';page_start('Information Ticker',true);
?>
<div class="admin-page-hero"><h2>Information Ticker</h2><p>Run offers, alerts, notices and city information on the front page and/or admin dashboard.</p></div><?php if($msg):?><div class="success"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="error"><?=e($err)?></div><?php endif;?>
<div class="admin-split"><div class="card"><h3><?=$edit?'Edit Ticker':'Add Ticker'?></h3><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><label>Title</label><input class="input" name="title" value="<?=e($edit['title']??'')?>"><label>Message</label><textarea class="input" rows="4" name="message" required><?=e($edit['message']??'')?></textarea><label>Link URL</label><input class="input" name="link_url" value="<?=e($edit['link_url']??'')?>"><div class="admin-form-grid"><div><label>Scope</label><select class="input" name="scope"><?php foreach(['public','admin','both'] as $v):?><option value="<?=e($v)?>" <?=($edit['scope']??'both')===$v?'selected':''?>><?=e(ucfirst($v))?></option><?php endforeach;?></select></div><div><label>Style</label><select class="input" name="style"><?php foreach(['info','success','warning','danger'] as $v):?><option value="<?=e($v)?>" <?=($edit['style']??'info')===$v?'selected':''?>><?=e(ucfirst($v))?></option><?php endforeach;?></select></div><div><label>Start</label><input class="input" type="datetime-local" name="starts_at"></div><div><label>End</label><input class="input" type="datetime-local" name="ends_at"></div><div><label>Order</label><input class="input" type="number" name="sort_order" value="<?=e($edit['sort_order']??10)?>"></div><div><label><input type="checkbox" name="status" <?=($edit['status']??1)?'checked':''?>> Active</label></div></div><br><button class="btn">Save Ticker</button></form></div>
<div class="card"><table><tr><th>Message</th><th>Scope</th><th>Schedule</th><th>Status</th><th></th></tr><?php foreach($rows as $r):?><tr><td><strong><?=e($r['title']?:'Notice')?></strong><br><span class="muted"><?=e($r['message'])?></span></td><td><?=e($r['scope'])?></td><td><?=e($r['starts_at']?:'Now')?> → <?=e($r['ends_at']?:'No expiry')?></td><td><?=$r['status']?'Active':'Hidden'?></td><td><a class="btn ghost" href="?edit=<?=e($r['id'])?>">Edit</a></td></tr><?php endforeach;?></table></div></div>
<?php require __DIR__.'/../app/end.php';?>
